// Code generated by `ubx sdk gen` from google_composer_user_workloads_config_map. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface UserWorkloadsConfigMap_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const UserWorkloadsConfigMap_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface UserWorkloadsConfigMapConfig {
  data?: Record<string, string> | Computed<Record<string, string>>;
  deletionPolicy?: string | Computed<string>;
  environment: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  region?: string | Computed<string>;
  timeouts?: UserWorkloadsConfigMap_Timeouts | Computed<UserWorkloadsConfigMap_Timeouts>;
}

export interface UserWorkloadsConfigMapAttrs {
  data: Record<string, string>;
  deletionPolicy: string;
  environment: string;
  id: string;
  name: string;
  project: string;
  region: string;
  timeouts: UserWorkloadsConfigMap_Timeouts;
}

export const UserWorkloadsConfigMap: ResourceBinding<UserWorkloadsConfigMapConfig, UserWorkloadsConfigMapAttrs> = {
  wireType: "google_composer_user_workloads_config_map",
  fields: {
    data: "data",
    deletionPolicy: "deletion_policy",
    environment: "environment",
    id: "id",
    name: "name",
    project: "project",
    region: "region",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: UserWorkloadsConfigMap_TimeoutsFields,
    },
  },
};
