// Code generated by `ubx sdk gen` from google_composer_user_workloads_secret. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface UserWorkloadsSecret_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const UserWorkloadsSecret_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface UserWorkloadsSecretConfig {
  data?: Record<string, string> | Computed<Record<string, string>>;
  deletionPolicy?: string | Computed<string>;
  environment: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  region?: string | Computed<string>;
  timeouts?: UserWorkloadsSecret_Timeouts | Computed<UserWorkloadsSecret_Timeouts>;
}

export interface UserWorkloadsSecretAttrs {
  data: Record<string, string>;
  deletionPolicy: string;
  environment: string;
  id: string;
  name: string;
  project: string;
  region: string;
  timeouts: UserWorkloadsSecret_Timeouts;
}

export const UserWorkloadsSecret: ResourceBinding<UserWorkloadsSecretConfig, UserWorkloadsSecretAttrs> = {
  wireType: "google_composer_user_workloads_secret",
  fields: {
    data: "data",
    deletionPolicy: "deletion_policy",
    environment: "environment",
    id: "id",
    name: "name",
    project: "project",
    region: "region",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: UserWorkloadsSecret_TimeoutsFields,
    },
  },
};
