// Code generated by `ubx sdk gen` from google_sql_user. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface User_SqlServerUserDetails {
  disabled: boolean;
  serverRoles: string[];
}

export interface User_PasswordPolicy_Status {
  locked: boolean;
  passwordExpirationTime: string;
}

export interface User_PasswordPolicy {
  allowedFailedAttempts: number;
  enableFailedAttemptsCheck: boolean;
  enablePasswordVerification: boolean;
  passwordExpirationDuration: string;
  status: User_PasswordPolicy_Status[];
}

export interface User_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const User_PasswordPolicy_StatusFields: FieldMap = {
  locked: "locked",
  passwordExpirationTime: "password_expiration_time",
};

const User_PasswordPolicyFields: FieldMap = {
  allowedFailedAttempts: "allowed_failed_attempts",
  enableFailedAttemptsCheck: "enable_failed_attempts_check",
  enablePasswordVerification: "enable_password_verification",
  passwordExpirationDuration: "password_expiration_duration",
  status: {
    wireName: "status",
    kind: "list",
    fields: User_PasswordPolicy_StatusFields,
  },
};

const User_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface UserConfig {
  databaseRoles?: string[] | Computed<string[]>;
  deletionPolicy?: string | Computed<string>;
  host?: string | Computed<string>;
  id?: string | Computed<string>;
  instance: string | Computed<string>;
  name: string | Computed<string>;
  password?: string | Computed<string>;
  passwordWo?: string | Computed<string>;
  passwordWoVersion?: number | Computed<number>;
  project?: string | Computed<string>;
  type?: string | Computed<string>;
  passwordPolicy?: User_PasswordPolicy[] | Computed<User_PasswordPolicy[]>;
  timeouts?: User_Timeouts | Computed<User_Timeouts>;
}

export interface UserAttrs {
  databaseRoles: string[];
  deletionPolicy: string;
  host: string;
  iamEmail: string;
  id: string;
  instance: string;
  name: string;
  password: string;
  passwordWo: string;
  passwordWoVersion: number;
  project: string;
  sqlServerUserDetails: User_SqlServerUserDetails[];
  type: string;
  passwordPolicy: User_PasswordPolicy[];
  timeouts: User_Timeouts;
}

export const User: ResourceBinding<UserConfig, UserAttrs> = {
  wireType: "google_sql_user",
  fields: {
    databaseRoles: "database_roles",
    deletionPolicy: "deletion_policy",
    host: "host",
    id: "id",
    instance: "instance",
    name: "name",
    password: "password",
    passwordWo: "password_wo",
    passwordWoVersion: "password_wo_version",
    project: "project",
    type: "type",
    passwordPolicy: {
      wireName: "password_policy",
      kind: "list",
      fields: User_PasswordPolicyFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: User_TimeoutsFields,
    },
  },
};
