// Code generated by `ubx sdk gen` from google_database_migration_service_migration_job. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MigrationServiceMigrationJob_Error {
  code: number;
  details: Record<string, string>[];
  message: string;
}

export interface MigrationServiceMigrationJob_DumpFlags_DumpFlags {
  name: string;
  value: string;
}

export interface MigrationServiceMigrationJob_DumpFlags {
  dumpFlags: MigrationServiceMigrationJob_DumpFlags_DumpFlags[];
}

export interface MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig_ObjectConfigs_ObjectIdentifier {
  database: string;
  schema: string;
  table: string;
  type: string;
}

export interface MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig_ObjectConfigs {
  objectIdentifier: MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig_ObjectConfigs_ObjectIdentifier[];
}

export interface MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig {
  objectsSelectionType: string;
  objectConfigs: MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig_ObjectConfigs[];
}

export interface MigrationServiceMigrationJob_ObjectsConfig {
  sourceObjectsConfig: MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig[];
}

export interface MigrationServiceMigrationJob_PerformanceConfig {
  dumpParallelLevel: string;
}

export interface MigrationServiceMigrationJob_PostgresHomogeneousConfig {
  isNativeLogical: boolean;
  maxAdditionalSubscriptions: number;
}

export interface MigrationServiceMigrationJob_ReverseSshConnectivity {
  vm: string;
  vmIp: string;
  vmPort: number;
  vpc: string;
}

export interface MigrationServiceMigrationJob_StaticIpConnectivity {
}

export interface MigrationServiceMigrationJob_Timeouts {
  create: string;
  delete: string;
  update: string;
}

export interface MigrationServiceMigrationJob_VpcPeeringConnectivity {
  vpc: string;
}

const MigrationServiceMigrationJob_DumpFlags_DumpFlagsFields: FieldMap = {
  name: "name",
  value: "value",
};

const MigrationServiceMigrationJob_DumpFlagsFields: FieldMap = {
  dumpFlags: {
    wireName: "dump_flags",
    kind: "list",
    fields: MigrationServiceMigrationJob_DumpFlags_DumpFlagsFields,
  },
};

const MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig_ObjectConfigs_ObjectIdentifierFields: FieldMap = {
  database: "database",
  schema: "schema",
  table: "table",
  type: "type",
};

const MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig_ObjectConfigsFields: FieldMap = {
  objectIdentifier: {
    wireName: "object_identifier",
    kind: "list",
    fields: MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig_ObjectConfigs_ObjectIdentifierFields,
  },
};

const MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfigFields: FieldMap = {
  objectsSelectionType: "objects_selection_type",
  objectConfigs: {
    wireName: "object_configs",
    kind: "list",
    fields: MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfig_ObjectConfigsFields,
  },
};

const MigrationServiceMigrationJob_ObjectsConfigFields: FieldMap = {
  sourceObjectsConfig: {
    wireName: "source_objects_config",
    kind: "list",
    fields: MigrationServiceMigrationJob_ObjectsConfig_SourceObjectsConfigFields,
  },
};

const MigrationServiceMigrationJob_PerformanceConfigFields: FieldMap = {
  dumpParallelLevel: "dump_parallel_level",
};

const MigrationServiceMigrationJob_PostgresHomogeneousConfigFields: FieldMap = {
  isNativeLogical: "is_native_logical",
  maxAdditionalSubscriptions: "max_additional_subscriptions",
};

const MigrationServiceMigrationJob_ReverseSshConnectivityFields: FieldMap = {
  vm: "vm",
  vmIp: "vm_ip",
  vmPort: "vm_port",
  vpc: "vpc",
};

const MigrationServiceMigrationJob_StaticIpConnectivityFields: FieldMap = {
};

const MigrationServiceMigrationJob_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

const MigrationServiceMigrationJob_VpcPeeringConnectivityFields: FieldMap = {
  vpc: "vpc",
};

export interface MigrationServiceMigrationJobConfig {
  deletionPolicy?: string | Computed<string>;
  desiredState?: string | Computed<string>;
  destination: string | Computed<string>;
  displayName?: string | Computed<string>;
  dumpPath?: string | Computed<string>;
  dumpType?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location?: string | Computed<string>;
  migrationJobId: string | Computed<string>;
  project?: string | Computed<string>;
  source: string | Computed<string>;
  stopOnWarnings?: boolean | Computed<boolean>;
  type: string | Computed<string>;
  dumpFlags?: MigrationServiceMigrationJob_DumpFlags[] | Computed<MigrationServiceMigrationJob_DumpFlags[]>;
  objectsConfig?: MigrationServiceMigrationJob_ObjectsConfig[] | Computed<MigrationServiceMigrationJob_ObjectsConfig[]>;
  performanceConfig?: MigrationServiceMigrationJob_PerformanceConfig[] | Computed<MigrationServiceMigrationJob_PerformanceConfig[]>;
  postgresHomogeneousConfig?: MigrationServiceMigrationJob_PostgresHomogeneousConfig[] | Computed<MigrationServiceMigrationJob_PostgresHomogeneousConfig[]>;
  reverseSshConnectivity?: MigrationServiceMigrationJob_ReverseSshConnectivity[] | Computed<MigrationServiceMigrationJob_ReverseSshConnectivity[]>;
  staticIpConnectivity?: MigrationServiceMigrationJob_StaticIpConnectivity[] | Computed<MigrationServiceMigrationJob_StaticIpConnectivity[]>;
  timeouts?: MigrationServiceMigrationJob_Timeouts | Computed<MigrationServiceMigrationJob_Timeouts>;
  vpcPeeringConnectivity?: MigrationServiceMigrationJob_VpcPeeringConnectivity[] | Computed<MigrationServiceMigrationJob_VpcPeeringConnectivity[]>;
}

export interface MigrationServiceMigrationJobAttrs {
  createTime: string;
  deletionPolicy: string;
  desiredState: string;
  destination: string;
  displayName: string;
  dumpPath: string;
  dumpType: string;
  effectiveLabels: Record<string, string>;
  error: MigrationServiceMigrationJob_Error[];
  id: string;
  labels: Record<string, string>;
  location: string;
  migrationJobId: string;
  name: string;
  phase: string;
  project: string;
  source: string;
  state: string;
  stopOnWarnings: boolean;
  terraformLabels: Record<string, string>;
  type: string;
  dumpFlags: MigrationServiceMigrationJob_DumpFlags[];
  objectsConfig: MigrationServiceMigrationJob_ObjectsConfig[];
  performanceConfig: MigrationServiceMigrationJob_PerformanceConfig[];
  postgresHomogeneousConfig: MigrationServiceMigrationJob_PostgresHomogeneousConfig[];
  reverseSshConnectivity: MigrationServiceMigrationJob_ReverseSshConnectivity[];
  staticIpConnectivity: MigrationServiceMigrationJob_StaticIpConnectivity[];
  timeouts: MigrationServiceMigrationJob_Timeouts;
  vpcPeeringConnectivity: MigrationServiceMigrationJob_VpcPeeringConnectivity[];
}

export const MigrationServiceMigrationJob: ResourceBinding<MigrationServiceMigrationJobConfig, MigrationServiceMigrationJobAttrs> = {
  wireType: "google_database_migration_service_migration_job",
  fields: {
    deletionPolicy: "deletion_policy",
    desiredState: "desired_state",
    destination: "destination",
    displayName: "display_name",
    dumpPath: "dump_path",
    dumpType: "dump_type",
    id: "id",
    labels: "labels",
    location: "location",
    migrationJobId: "migration_job_id",
    project: "project",
    source: "source",
    stopOnWarnings: "stop_on_warnings",
    type: "type",
    dumpFlags: {
      wireName: "dump_flags",
      kind: "list",
      fields: MigrationServiceMigrationJob_DumpFlagsFields,
    },
    objectsConfig: {
      wireName: "objects_config",
      kind: "list",
      fields: MigrationServiceMigrationJob_ObjectsConfigFields,
    },
    performanceConfig: {
      wireName: "performance_config",
      kind: "list",
      fields: MigrationServiceMigrationJob_PerformanceConfigFields,
    },
    postgresHomogeneousConfig: {
      wireName: "postgres_homogeneous_config",
      kind: "list",
      fields: MigrationServiceMigrationJob_PostgresHomogeneousConfigFields,
    },
    reverseSshConnectivity: {
      wireName: "reverse_ssh_connectivity",
      kind: "list",
      fields: MigrationServiceMigrationJob_ReverseSshConnectivityFields,
    },
    staticIpConnectivity: {
      wireName: "static_ip_connectivity",
      kind: "list",
      fields: MigrationServiceMigrationJob_StaticIpConnectivityFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: MigrationServiceMigrationJob_TimeoutsFields,
    },
    vpcPeeringConnectivity: {
      wireName: "vpc_peering_connectivity",
      kind: "list",
      fields: MigrationServiceMigrationJob_VpcPeeringConnectivityFields,
    },
  },
};
