// Code generated by `ubx sdk gen` from google_colab_runtime_template_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RuntimeTemplateIamPolicyConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  policyData: string | Computed<string>;
  project?: string | Computed<string>;
  runtimeTemplate: string | Computed<string>;
}

export interface RuntimeTemplateIamPolicyAttrs {
  etag: string;
  id: string;
  location: string;
  policyData: string;
  project: string;
  runtimeTemplate: string;
}

export const RuntimeTemplateIamPolicy: ResourceBinding<RuntimeTemplateIamPolicyConfig, RuntimeTemplateIamPolicyAttrs> = {
  wireType: "google_colab_runtime_template_iam_policy",
  fields: {
    id: "id",
    location: "location",
    policyData: "policy_data",
    project: "project",
    runtimeTemplate: "runtime_template",
  },
};
