// Code generated by `ubx sdk gen` from google_healthcare_hl7_v2_store. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Hl7V2Store_NotificationConfig {
  pubsubTopic: string;
}

export interface Hl7V2Store_NotificationConfigs {
  filter: string;
  pubsubTopic: string;
}

export interface Hl7V2Store_ParserConfig {
  allowNullHeader: boolean;
  schema: string;
  segmentTerminator: string;
  version: string;
}

export interface Hl7V2Store_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const Hl7V2Store_NotificationConfigFields: FieldMap = {
  pubsubTopic: "pubsub_topic",
};

const Hl7V2Store_NotificationConfigsFields: FieldMap = {
  filter: "filter",
  pubsubTopic: "pubsub_topic",
};

const Hl7V2Store_ParserConfigFields: FieldMap = {
  allowNullHeader: "allow_null_header",
  schema: "schema",
  segmentTerminator: "segment_terminator",
  version: "version",
};

const Hl7V2Store_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface Hl7V2StoreConfig {
  dataset: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  name: string | Computed<string>;
  rejectDuplicateMessage?: boolean | Computed<boolean>;
  notificationConfig?: Hl7V2Store_NotificationConfig[] | Computed<Hl7V2Store_NotificationConfig[]>;
  notificationConfigs?: Hl7V2Store_NotificationConfigs[] | Computed<Hl7V2Store_NotificationConfigs[]>;
  parserConfig?: Hl7V2Store_ParserConfig[] | Computed<Hl7V2Store_ParserConfig[]>;
  timeouts?: Hl7V2Store_Timeouts | Computed<Hl7V2Store_Timeouts>;
}

export interface Hl7V2StoreAttrs {
  dataset: string;
  deletionPolicy: string;
  effectiveLabels: Record<string, string>;
  id: string;
  labels: Record<string, string>;
  name: string;
  rejectDuplicateMessage: boolean;
  selfLink: string;
  terraformLabels: Record<string, string>;
  notificationConfig: Hl7V2Store_NotificationConfig[];
  notificationConfigs: Hl7V2Store_NotificationConfigs[];
  parserConfig: Hl7V2Store_ParserConfig[];
  timeouts: Hl7V2Store_Timeouts;
}

export const Hl7V2Store: ResourceBinding<Hl7V2StoreConfig, Hl7V2StoreAttrs> = {
  wireType: "google_healthcare_hl7_v2_store",
  fields: {
    dataset: "dataset",
    deletionPolicy: "deletion_policy",
    id: "id",
    labels: "labels",
    name: "name",
    rejectDuplicateMessage: "reject_duplicate_message",
    notificationConfig: {
      wireName: "notification_config",
      kind: "list",
      fields: Hl7V2Store_NotificationConfigFields,
    },
    notificationConfigs: {
      wireName: "notification_configs",
      kind: "list",
      fields: Hl7V2Store_NotificationConfigsFields,
    },
    parserConfig: {
      wireName: "parser_config",
      kind: "list",
      fields: Hl7V2Store_ParserConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Hl7V2Store_TimeoutsFields,
    },
  },
};
