// Code generated by `ubx sdk gen` from google_migration_center_import_data_file. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CenterImportDataFile_UploadFileInfo {
  headers: Record<string, string>;
  signedUri: string;
  uriExpirationTime: string;
}

export interface CenterImportDataFile_Timeouts {
  create: string;
  delete: string;
}

const CenterImportDataFile_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
};

export interface CenterImportDataFileConfig {
  deletionPolicy?: string | Computed<string>;
  displayName?: string | Computed<string>;
  format: string | Computed<string>;
  id?: string | Computed<string>;
  importDataFileId: string | Computed<string>;
  importJob: string | Computed<string>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  timeouts?: CenterImportDataFile_Timeouts | Computed<CenterImportDataFile_Timeouts>;
}

export interface CenterImportDataFileAttrs {
  createTime: string;
  deletionPolicy: string;
  displayName: string;
  format: string;
  id: string;
  importDataFileId: string;
  importJob: string;
  location: string;
  name: string;
  project: string;
  state: string;
  uploadFileInfo: CenterImportDataFile_UploadFileInfo[];
  timeouts: CenterImportDataFile_Timeouts;
}

export const CenterImportDataFile: ResourceBinding<CenterImportDataFileConfig, CenterImportDataFileAttrs> = {
  wireType: "google_migration_center_import_data_file",
  fields: {
    deletionPolicy: "deletion_policy",
    displayName: "display_name",
    format: "format",
    id: "id",
    importDataFileId: "import_data_file_id",
    importJob: "import_job",
    location: "location",
    project: "project",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CenterImportDataFile_TimeoutsFields,
    },
  },
};
