// Code generated by `ubx sdk gen` from google_agent_registry_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RegistryBinding_AuthProviderBinding {
  authProvider: string;
  continueUri: string;
  scopes: string[];
}

export interface RegistryBinding_Source {
  identifier: string;
}

export interface RegistryBinding_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const RegistryBinding_AuthProviderBindingFields: FieldMap = {
  authProvider: "auth_provider",
  continueUri: "continue_uri",
  scopes: "scopes",
};

const RegistryBinding_SourceFields: FieldMap = {
  identifier: "identifier",
};

const RegistryBinding_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface RegistryBindingConfig {
  bindingId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  authProviderBinding?: RegistryBinding_AuthProviderBinding[] | Computed<RegistryBinding_AuthProviderBinding[]>;
  source?: RegistryBinding_Source[] | Computed<RegistryBinding_Source[]>;
  target?: RegistryBinding_Source[] | Computed<RegistryBinding_Source[]>;
  timeouts?: RegistryBinding_Timeouts | Computed<RegistryBinding_Timeouts>;
}

export interface RegistryBindingAttrs {
  bindingId: string;
  createTime: string;
  deletionPolicy: string;
  description: string;
  displayName: string;
  id: string;
  location: string;
  name: string;
  project: string;
  updateTime: string;
  authProviderBinding: RegistryBinding_AuthProviderBinding[];
  source: RegistryBinding_Source[];
  target: RegistryBinding_Source[];
  timeouts: RegistryBinding_Timeouts;
}

export const RegistryBinding: ResourceBinding<RegistryBindingConfig, RegistryBindingAttrs> = {
  wireType: "google_agent_registry_binding",
  fields: {
    bindingId: "binding_id",
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    id: "id",
    location: "location",
    project: "project",
    authProviderBinding: {
      wireName: "auth_provider_binding",
      kind: "list",
      fields: RegistryBinding_AuthProviderBindingFields,
    },
    source: {
      wireName: "source",
      kind: "list",
      fields: RegistryBinding_SourceFields,
    },
    target: {
      wireName: "target",
      kind: "list",
      fields: RegistryBinding_SourceFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: RegistryBinding_TimeoutsFields,
    },
  },
};
