// Code generated by `ubx sdk gen` from google_workstations_workstation_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface WorkstationIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const WorkstationIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface WorkstationIamBindingConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  workstationClusterId: string | Computed<string>;
  workstationConfigId: string | Computed<string>;
  workstationId: string | Computed<string>;
  condition?: WorkstationIamBinding_Condition[] | Computed<WorkstationIamBinding_Condition[]>;
}

export interface WorkstationIamBindingAttrs {
  etag: string;
  id: string;
  location: string;
  members: string[];
  project: string;
  role: string;
  workstationClusterId: string;
  workstationConfigId: string;
  workstationId: string;
  condition: WorkstationIamBinding_Condition[];
}

export const WorkstationIamBinding: ResourceBinding<WorkstationIamBindingConfig, WorkstationIamBindingAttrs> = {
  wireType: "google_workstations_workstation_iam_binding",
  fields: {
    id: "id",
    location: "location",
    members: "members",
    project: "project",
    role: "role",
    workstationClusterId: "workstation_cluster_id",
    workstationConfigId: "workstation_config_id",
    workstationId: "workstation_id",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: WorkstationIamBinding_ConditionFields,
    },
  },
};
