// Code generated by `ubx sdk gen` from google_notebooks_instance_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface InstanceIamPolicyConfig {
  id?: string | Computed<string>;
  instanceName: string | Computed<string>;
  location?: string | Computed<string>;
  policyData: string | Computed<string>;
  project?: string | Computed<string>;
}

export interface InstanceIamPolicyAttrs {
  etag: string;
  id: string;
  instanceName: string;
  location: string;
  policyData: string;
  project: string;
}

export const InstanceIamPolicy: ResourceBinding<InstanceIamPolicyConfig, InstanceIamPolicyAttrs> = {
  wireType: "google_notebooks_instance_iam_policy",
  fields: {
    id: "id",
    instanceName: "instance_name",
    location: "location",
    policyData: "policy_data",
    project: "project",
  },
};
