// Code generated by `ubx sdk gen` from google_notebooks_instance. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Instance_AcceleratorConfig {
  coreCount: number;
  type: string;
}

export interface Instance_ContainerImage {
  repository: string;
  tag: string;
}

export interface Instance_ReservationAffinity {
  consumeReservationType: string;
  key: string;
  values: string[];
}

export interface Instance_ShieldedInstanceConfig {
  enableIntegrityMonitoring: boolean;
  enableSecureBoot: boolean;
  enableVtpm: boolean;
}

export interface Instance_Timeouts {
  create: string;
  delete: string;
  update: string;
}

export interface Instance_VmImage {
  imageFamily: string;
  imageName: string;
  project: string;
}

const Instance_AcceleratorConfigFields: FieldMap = {
  coreCount: "core_count",
  type: "type",
};

const Instance_ContainerImageFields: FieldMap = {
  repository: "repository",
  tag: "tag",
};

const Instance_ReservationAffinityFields: FieldMap = {
  consumeReservationType: "consume_reservation_type",
  key: "key",
  values: "values",
};

const Instance_ShieldedInstanceConfigFields: FieldMap = {
  enableIntegrityMonitoring: "enable_integrity_monitoring",
  enableSecureBoot: "enable_secure_boot",
  enableVtpm: "enable_vtpm",
};

const Instance_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

const Instance_VmImageFields: FieldMap = {
  imageFamily: "image_family",
  imageName: "image_name",
  project: "project",
};

export interface InstanceConfig {
  bootDiskSizeGb?: number | Computed<number>;
  bootDiskType?: string | Computed<string>;
  createTime?: string | Computed<string>;
  customGpuDriverPath?: string | Computed<string>;
  dataDiskSizeGb?: number | Computed<number>;
  dataDiskType?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  desiredState?: string | Computed<string>;
  diskEncryption?: string | Computed<string>;
  id?: string | Computed<string>;
  installGpuDriver?: boolean | Computed<boolean>;
  instanceOwners?: string[] | Computed<string[]>;
  kmsKey?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  machineType: string | Computed<string>;
  metadata?: Record<string, string> | Computed<Record<string, string>>;
  name: string | Computed<string>;
  network?: string | Computed<string>;
  nicType?: string | Computed<string>;
  noProxyAccess?: boolean | Computed<boolean>;
  noPublicIp?: boolean | Computed<boolean>;
  noRemoveDataDisk?: boolean | Computed<boolean>;
  postStartupScript?: string | Computed<string>;
  project?: string | Computed<string>;
  serviceAccount?: string | Computed<string>;
  serviceAccountScopes?: string[] | Computed<string[]>;
  subnet?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  updateTime?: string | Computed<string>;
  acceleratorConfig?: Instance_AcceleratorConfig[] | Computed<Instance_AcceleratorConfig[]>;
  containerImage?: Instance_ContainerImage[] | Computed<Instance_ContainerImage[]>;
  reservationAffinity?: Instance_ReservationAffinity[] | Computed<Instance_ReservationAffinity[]>;
  shieldedInstanceConfig?: Instance_ShieldedInstanceConfig[] | Computed<Instance_ShieldedInstanceConfig[]>;
  timeouts?: Instance_Timeouts | Computed<Instance_Timeouts>;
  vmImage?: Instance_VmImage[] | Computed<Instance_VmImage[]>;
}

export interface InstanceAttrs {
  bootDiskSizeGb: number;
  bootDiskType: string;
  createTime: string;
  customGpuDriverPath: string;
  dataDiskSizeGb: number;
  dataDiskType: string;
  deletionPolicy: string;
  desiredState: string;
  diskEncryption: string;
  effectiveLabels: Record<string, string>;
  id: string;
  installGpuDriver: boolean;
  instanceOwners: string[];
  kmsKey: string;
  labels: Record<string, string>;
  location: string;
  machineType: string;
  metadata: Record<string, string>;
  name: string;
  network: string;
  nicType: string;
  noProxyAccess: boolean;
  noPublicIp: boolean;
  noRemoveDataDisk: boolean;
  postStartupScript: string;
  project: string;
  proxyUri: string;
  serviceAccount: string;
  serviceAccountScopes: string[];
  state: string;
  subnet: string;
  tags: string[];
  terraformLabels: Record<string, string>;
  updateTime: string;
  acceleratorConfig: Instance_AcceleratorConfig[];
  containerImage: Instance_ContainerImage[];
  reservationAffinity: Instance_ReservationAffinity[];
  shieldedInstanceConfig: Instance_ShieldedInstanceConfig[];
  timeouts: Instance_Timeouts;
  vmImage: Instance_VmImage[];
}

export const Instance: ResourceBinding<InstanceConfig, InstanceAttrs> = {
  wireType: "google_notebooks_instance",
  fields: {
    bootDiskSizeGb: "boot_disk_size_gb",
    bootDiskType: "boot_disk_type",
    createTime: "create_time",
    customGpuDriverPath: "custom_gpu_driver_path",
    dataDiskSizeGb: "data_disk_size_gb",
    dataDiskType: "data_disk_type",
    deletionPolicy: "deletion_policy",
    desiredState: "desired_state",
    diskEncryption: "disk_encryption",
    id: "id",
    installGpuDriver: "install_gpu_driver",
    instanceOwners: "instance_owners",
    kmsKey: "kms_key",
    labels: "labels",
    location: "location",
    machineType: "machine_type",
    metadata: "metadata",
    name: "name",
    network: "network",
    nicType: "nic_type",
    noProxyAccess: "no_proxy_access",
    noPublicIp: "no_public_ip",
    noRemoveDataDisk: "no_remove_data_disk",
    postStartupScript: "post_startup_script",
    project: "project",
    serviceAccount: "service_account",
    serviceAccountScopes: "service_account_scopes",
    subnet: "subnet",
    tags: "tags",
    updateTime: "update_time",
    acceleratorConfig: {
      wireName: "accelerator_config",
      kind: "list",
      fields: Instance_AcceleratorConfigFields,
    },
    containerImage: {
      wireName: "container_image",
      kind: "list",
      fields: Instance_ContainerImageFields,
    },
    reservationAffinity: {
      wireName: "reservation_affinity",
      kind: "list",
      fields: Instance_ReservationAffinityFields,
    },
    shieldedInstanceConfig: {
      wireName: "shielded_instance_config",
      kind: "list",
      fields: Instance_ShieldedInstanceConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Instance_TimeoutsFields,
    },
    vmImage: {
      wireName: "vm_image",
      kind: "list",
      fields: Instance_VmImageFields,
    },
  },
};
