// Code generated by `ubx sdk gen` from google_privateca_certificate_template_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CertificateTemplateIamPolicyConfig {
  certificateTemplate: string | Computed<string>;
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  policyData: string | Computed<string>;
  project?: string | Computed<string>;
}

export interface CertificateTemplateIamPolicyAttrs {
  certificateTemplate: string;
  etag: string;
  id: string;
  location: string;
  policyData: string;
  project: string;
}

export const CertificateTemplateIamPolicy: ResourceBinding<CertificateTemplateIamPolicyConfig, CertificateTemplateIamPolicyAttrs> = {
  wireType: "google_privateca_certificate_template_iam_policy",
  fields: {
    certificateTemplate: "certificate_template",
    id: "id",
    location: "location",
    policyData: "policy_data",
    project: "project",
  },
};
