// Code generated by `ubx sdk gen` from google_pubsub_lite_reservation. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LiteReservation_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const LiteReservation_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface LiteReservationConfig {
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  region?: string | Computed<string>;
  throughputCapacity: number | Computed<number>;
  timeouts?: LiteReservation_Timeouts | Computed<LiteReservation_Timeouts>;
}

export interface LiteReservationAttrs {
  deletionPolicy: string;
  id: string;
  name: string;
  project: string;
  region: string;
  throughputCapacity: number;
  timeouts: LiteReservation_Timeouts;
}

export const LiteReservation: ResourceBinding<LiteReservationConfig, LiteReservationAttrs> = {
  wireType: "google_pubsub_lite_reservation",
  fields: {
    deletionPolicy: "deletion_policy",
    id: "id",
    name: "name",
    project: "project",
    region: "region",
    throughputCapacity: "throughput_capacity",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: LiteReservation_TimeoutsFields,
    },
  },
};
