// Code generated by `ubx sdk gen` from google_pubsub_subscription. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Subscription_BigqueryConfig {
  dropUnknownFields: boolean;
  serviceAccountEmail: string;
  table: string;
  useTableSchema: boolean;
  useTopicSchema: boolean;
  writeMetadata: boolean;
}

export interface Subscription_CloudStorageConfig_AvroConfig {
  useTopicSchema: boolean;
  writeMetadata: boolean;
}

export interface Subscription_CloudStorageConfig_TextConfig {
  state: string;
}

export interface Subscription_CloudStorageConfig {
  bucket: string;
  filenameDatetimeFormat: string;
  filenamePrefix: string;
  filenameSuffix: string;
  maxBytes: number;
  maxDuration: string;
  maxMessages: number;
  serviceAccountEmail: string;
  state: string;
  avroConfig: Subscription_CloudStorageConfig_AvroConfig[];
  textConfig: Subscription_CloudStorageConfig_TextConfig[];
}

export interface Subscription_DeadLetterPolicy {
  deadLetterTopic: string;
  maxDeliveryAttempts: number;
}

export interface Subscription_ExpirationPolicy {
  ttl: string;
}

export interface Subscription_MessageTransforms_AiInference_UnstructuredInference {
  parameters: Record<string, string>;
}

export interface Subscription_MessageTransforms_AiInference {
  endpoint: string;
  serviceAccountEmail: string;
  unstructuredInference: Subscription_MessageTransforms_AiInference_UnstructuredInference[];
}

export interface Subscription_MessageTransforms_JavascriptUdf {
  code: string;
  functionName: string;
}

export interface Subscription_MessageTransforms {
  disabled: boolean;
  aiInference: Subscription_MessageTransforms_AiInference[];
  javascriptUdf: Subscription_MessageTransforms_JavascriptUdf[];
}

export interface Subscription_PushConfig_NoWrapper {
  writeMetadata: boolean;
}

export interface Subscription_PushConfig_OidcToken {
  audience: string;
  serviceAccountEmail: string;
}

export interface Subscription_PushConfig {
  attributes: Record<string, string>;
  pushEndpoint: string;
  noWrapper: Subscription_PushConfig_NoWrapper[];
  oidcToken: Subscription_PushConfig_OidcToken[];
}

export interface Subscription_RetryPolicy {
  maximumBackoff: string;
  minimumBackoff: string;
}

export interface Subscription_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const Subscription_BigqueryConfigFields: FieldMap = {
  dropUnknownFields: "drop_unknown_fields",
  serviceAccountEmail: "service_account_email",
  table: "table",
  useTableSchema: "use_table_schema",
  useTopicSchema: "use_topic_schema",
  writeMetadata: "write_metadata",
};

const Subscription_CloudStorageConfig_AvroConfigFields: FieldMap = {
  useTopicSchema: "use_topic_schema",
  writeMetadata: "write_metadata",
};

const Subscription_CloudStorageConfig_TextConfigFields: FieldMap = {
  state: "state",
};

const Subscription_CloudStorageConfigFields: FieldMap = {
  bucket: "bucket",
  filenameDatetimeFormat: "filename_datetime_format",
  filenamePrefix: "filename_prefix",
  filenameSuffix: "filename_suffix",
  maxBytes: "max_bytes",
  maxDuration: "max_duration",
  maxMessages: "max_messages",
  serviceAccountEmail: "service_account_email",
  state: "state",
  avroConfig: {
    wireName: "avro_config",
    kind: "list",
    fields: Subscription_CloudStorageConfig_AvroConfigFields,
  },
  textConfig: {
    wireName: "text_config",
    kind: "list",
    fields: Subscription_CloudStorageConfig_TextConfigFields,
  },
};

const Subscription_DeadLetterPolicyFields: FieldMap = {
  deadLetterTopic: "dead_letter_topic",
  maxDeliveryAttempts: "max_delivery_attempts",
};

const Subscription_ExpirationPolicyFields: FieldMap = {
  ttl: "ttl",
};

const Subscription_MessageTransforms_AiInference_UnstructuredInferenceFields: FieldMap = {
  parameters: "parameters",
};

const Subscription_MessageTransforms_AiInferenceFields: FieldMap = {
  endpoint: "endpoint",
  serviceAccountEmail: "service_account_email",
  unstructuredInference: {
    wireName: "unstructured_inference",
    kind: "list",
    fields: Subscription_MessageTransforms_AiInference_UnstructuredInferenceFields,
  },
};

const Subscription_MessageTransforms_JavascriptUdfFields: FieldMap = {
  code: "code",
  functionName: "function_name",
};

const Subscription_MessageTransformsFields: FieldMap = {
  disabled: "disabled",
  aiInference: {
    wireName: "ai_inference",
    kind: "list",
    fields: Subscription_MessageTransforms_AiInferenceFields,
  },
  javascriptUdf: {
    wireName: "javascript_udf",
    kind: "list",
    fields: Subscription_MessageTransforms_JavascriptUdfFields,
  },
};

const Subscription_PushConfig_NoWrapperFields: FieldMap = {
  writeMetadata: "write_metadata",
};

const Subscription_PushConfig_OidcTokenFields: FieldMap = {
  audience: "audience",
  serviceAccountEmail: "service_account_email",
};

const Subscription_PushConfigFields: FieldMap = {
  attributes: "attributes",
  pushEndpoint: "push_endpoint",
  noWrapper: {
    wireName: "no_wrapper",
    kind: "list",
    fields: Subscription_PushConfig_NoWrapperFields,
  },
  oidcToken: {
    wireName: "oidc_token",
    kind: "list",
    fields: Subscription_PushConfig_OidcTokenFields,
  },
};

const Subscription_RetryPolicyFields: FieldMap = {
  maximumBackoff: "maximum_backoff",
  minimumBackoff: "minimum_backoff",
};

const Subscription_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SubscriptionConfig {
  ackDeadlineSeconds?: number | Computed<number>;
  deletionPolicy?: string | Computed<string>;
  enableExactlyOnceDelivery?: boolean | Computed<boolean>;
  enableMessageOrdering?: boolean | Computed<boolean>;
  filter?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  messageRetentionDuration?: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  retainAckedMessages?: boolean | Computed<boolean>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  topic: string | Computed<string>;
  bigqueryConfig?: Subscription_BigqueryConfig[] | Computed<Subscription_BigqueryConfig[]>;
  cloudStorageConfig?: Subscription_CloudStorageConfig[] | Computed<Subscription_CloudStorageConfig[]>;
  deadLetterPolicy?: Subscription_DeadLetterPolicy[] | Computed<Subscription_DeadLetterPolicy[]>;
  expirationPolicy?: Subscription_ExpirationPolicy[] | Computed<Subscription_ExpirationPolicy[]>;
  messageTransforms?: Subscription_MessageTransforms[] | Computed<Subscription_MessageTransforms[]>;
  pushConfig?: Subscription_PushConfig[] | Computed<Subscription_PushConfig[]>;
  retryPolicy?: Subscription_RetryPolicy[] | Computed<Subscription_RetryPolicy[]>;
  timeouts?: Subscription_Timeouts | Computed<Subscription_Timeouts>;
}

export interface SubscriptionAttrs {
  ackDeadlineSeconds: number;
  deletionPolicy: string;
  effectiveLabels: Record<string, string>;
  enableExactlyOnceDelivery: boolean;
  enableMessageOrdering: boolean;
  filter: string;
  id: string;
  labels: Record<string, string>;
  messageRetentionDuration: string;
  name: string;
  project: string;
  retainAckedMessages: boolean;
  tags: Record<string, string>;
  terraformLabels: Record<string, string>;
  topic: string;
  bigqueryConfig: Subscription_BigqueryConfig[];
  cloudStorageConfig: Subscription_CloudStorageConfig[];
  deadLetterPolicy: Subscription_DeadLetterPolicy[];
  expirationPolicy: Subscription_ExpirationPolicy[];
  messageTransforms: Subscription_MessageTransforms[];
  pushConfig: Subscription_PushConfig[];
  retryPolicy: Subscription_RetryPolicy[];
  timeouts: Subscription_Timeouts;
}

export const Subscription: ResourceBinding<SubscriptionConfig, SubscriptionAttrs> = {
  wireType: "google_pubsub_subscription",
  fields: {
    ackDeadlineSeconds: "ack_deadline_seconds",
    deletionPolicy: "deletion_policy",
    enableExactlyOnceDelivery: "enable_exactly_once_delivery",
    enableMessageOrdering: "enable_message_ordering",
    filter: "filter",
    id: "id",
    labels: "labels",
    messageRetentionDuration: "message_retention_duration",
    name: "name",
    project: "project",
    retainAckedMessages: "retain_acked_messages",
    tags: "tags",
    topic: "topic",
    bigqueryConfig: {
      wireName: "bigquery_config",
      kind: "list",
      fields: Subscription_BigqueryConfigFields,
    },
    cloudStorageConfig: {
      wireName: "cloud_storage_config",
      kind: "list",
      fields: Subscription_CloudStorageConfigFields,
    },
    deadLetterPolicy: {
      wireName: "dead_letter_policy",
      kind: "list",
      fields: Subscription_DeadLetterPolicyFields,
    },
    expirationPolicy: {
      wireName: "expiration_policy",
      kind: "list",
      fields: Subscription_ExpirationPolicyFields,
    },
    messageTransforms: {
      wireName: "message_transforms",
      kind: "list",
      fields: Subscription_MessageTransformsFields,
    },
    pushConfig: {
      wireName: "push_config",
      kind: "list",
      fields: Subscription_PushConfigFields,
    },
    retryPolicy: {
      wireName: "retry_policy",
      kind: "list",
      fields: Subscription_RetryPolicyFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Subscription_TimeoutsFields,
    },
  },
};
