// Code generated by `ubx sdk gen` from google_network_connectivity_destination. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConnectivityDestination_StateTimeline_States {
  effectiveTime: string;
  state: string;
}

export interface ConnectivityDestination_StateTimeline {
  states: ConnectivityDestination_StateTimeline_States[];
}

export interface ConnectivityDestination_Endpoints {
  asn: string;
  csp: string;
  state: string;
  updateTime: string;
}

export interface ConnectivityDestination_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ConnectivityDestination_EndpointsFields: FieldMap = {
  asn: "asn",
  csp: "csp",
  state: "state",
  updateTime: "update_time",
};

const ConnectivityDestination_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ConnectivityDestinationConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  ipPrefix: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  multicloudDataTransferConfig: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  endpoints?: ConnectivityDestination_Endpoints[] | Computed<ConnectivityDestination_Endpoints[]>;
  timeouts?: ConnectivityDestination_Timeouts | Computed<ConnectivityDestination_Timeouts>;
}

export interface ConnectivityDestinationAttrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  etag: string;
  id: string;
  ipPrefix: string;
  labels: Record<string, string>;
  location: string;
  multicloudDataTransferConfig: string;
  name: string;
  project: string;
  stateTimeline: ConnectivityDestination_StateTimeline[];
  terraformLabels: Record<string, string>;
  uid: string;
  updateTime: string;
  endpoints: ConnectivityDestination_Endpoints[];
  timeouts: ConnectivityDestination_Timeouts;
}

export const ConnectivityDestination: ResourceBinding<ConnectivityDestinationConfig, ConnectivityDestinationAttrs> = {
  wireType: "google_network_connectivity_destination",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    ipPrefix: "ip_prefix",
    labels: "labels",
    location: "location",
    multicloudDataTransferConfig: "multicloud_data_transfer_config",
    name: "name",
    project: "project",
    endpoints: {
      wireName: "endpoints",
      kind: "set",
      fields: ConnectivityDestination_EndpointsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ConnectivityDestination_TimeoutsFields,
    },
  },
};
