// Code generated by `ubx sdk gen` from google_network_management_vpc_flow_logs_config. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagementVpcFlowLogsConfig_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ManagementVpcFlowLogsConfig_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ManagementVpcFlowLogsConfigConfig {
  aggregationInterval?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  filterExpr?: string | Computed<string>;
  flowSampling?: number | Computed<number>;
  id?: string | Computed<string>;
  interconnectAttachment?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  metadata?: string | Computed<string>;
  metadataFields?: string[] | Computed<string[]>;
  network?: string | Computed<string>;
  project?: string | Computed<string>;
  state?: string | Computed<string>;
  subnet?: string | Computed<string>;
  vpcFlowLogsConfigId: string | Computed<string>;
  vpnTunnel?: string | Computed<string>;
  timeouts?: ManagementVpcFlowLogsConfig_Timeouts | Computed<ManagementVpcFlowLogsConfig_Timeouts>;
}

export interface ManagementVpcFlowLogsConfigAttrs {
  aggregationInterval: string;
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  filterExpr: string;
  flowSampling: number;
  id: string;
  interconnectAttachment: string;
  labels: Record<string, string>;
  location: string;
  metadata: string;
  metadataFields: string[];
  name: string;
  network: string;
  project: string;
  state: string;
  subnet: string;
  targetResourceState: string;
  terraformLabels: Record<string, string>;
  updateTime: string;
  vpcFlowLogsConfigId: string;
  vpnTunnel: string;
  timeouts: ManagementVpcFlowLogsConfig_Timeouts;
}

export const ManagementVpcFlowLogsConfig: ResourceBinding<ManagementVpcFlowLogsConfigConfig, ManagementVpcFlowLogsConfigAttrs> = {
  wireType: "google_network_management_vpc_flow_logs_config",
  fields: {
    aggregationInterval: "aggregation_interval",
    deletionPolicy: "deletion_policy",
    description: "description",
    filterExpr: "filter_expr",
    flowSampling: "flow_sampling",
    id: "id",
    interconnectAttachment: "interconnect_attachment",
    labels: "labels",
    location: "location",
    metadata: "metadata",
    metadataFields: "metadata_fields",
    network: "network",
    project: "project",
    state: "state",
    subnet: "subnet",
    vpcFlowLogsConfigId: "vpc_flow_logs_config_id",
    vpnTunnel: "vpn_tunnel",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagementVpcFlowLogsConfig_TimeoutsFields,
    },
  },
};
