// Code generated by `ubx sdk gen` from google_network_security_client_tls_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SecurityClientTlsPolicy_ClientCertificate_CertificateProviderInstance {
  pluginInstance: string;
}

export interface SecurityClientTlsPolicy_ClientCertificate_GrpcEndpoint {
  targetUri: string;
}

export interface SecurityClientTlsPolicy_ClientCertificate {
  certificateProviderInstance: SecurityClientTlsPolicy_ClientCertificate_CertificateProviderInstance[];
  grpcEndpoint: SecurityClientTlsPolicy_ClientCertificate_GrpcEndpoint[];
}

export interface SecurityClientTlsPolicy_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const SecurityClientTlsPolicy_ClientCertificate_CertificateProviderInstanceFields: FieldMap = {
  pluginInstance: "plugin_instance",
};

const SecurityClientTlsPolicy_ClientCertificate_GrpcEndpointFields: FieldMap = {
  targetUri: "target_uri",
};

const SecurityClientTlsPolicy_ClientCertificateFields: FieldMap = {
  certificateProviderInstance: {
    wireName: "certificate_provider_instance",
    kind: "list",
    fields: SecurityClientTlsPolicy_ClientCertificate_CertificateProviderInstanceFields,
  },
  grpcEndpoint: {
    wireName: "grpc_endpoint",
    kind: "list",
    fields: SecurityClientTlsPolicy_ClientCertificate_GrpcEndpointFields,
  },
};

const SecurityClientTlsPolicy_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SecurityClientTlsPolicyConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location?: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  sni?: string | Computed<string>;
  clientCertificate?: SecurityClientTlsPolicy_ClientCertificate[] | Computed<SecurityClientTlsPolicy_ClientCertificate[]>;
  serverValidationCa?: SecurityClientTlsPolicy_ClientCertificate[] | Computed<SecurityClientTlsPolicy_ClientCertificate[]>;
  timeouts?: SecurityClientTlsPolicy_Timeouts | Computed<SecurityClientTlsPolicy_Timeouts>;
}

export interface SecurityClientTlsPolicyAttrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  id: string;
  labels: Record<string, string>;
  location: string;
  name: string;
  project: string;
  sni: string;
  terraformLabels: Record<string, string>;
  updateTime: string;
  clientCertificate: SecurityClientTlsPolicy_ClientCertificate[];
  serverValidationCa: SecurityClientTlsPolicy_ClientCertificate[];
  timeouts: SecurityClientTlsPolicy_Timeouts;
}

export const SecurityClientTlsPolicy: ResourceBinding<SecurityClientTlsPolicyConfig, SecurityClientTlsPolicyAttrs> = {
  wireType: "google_network_security_client_tls_policy",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    labels: "labels",
    location: "location",
    name: "name",
    project: "project",
    sni: "sni",
    clientCertificate: {
      wireName: "client_certificate",
      kind: "list",
      fields: SecurityClientTlsPolicy_ClientCertificateFields,
    },
    serverValidationCa: {
      wireName: "server_validation_ca",
      kind: "list",
      fields: SecurityClientTlsPolicy_ClientCertificateFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SecurityClientTlsPolicy_TimeoutsFields,
    },
  },
};
