// Code generated by `ubx sdk gen` from google_network_security_server_tls_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa_CertificateProviderInstance {
  pluginInstance: string;
}

export interface SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa_GrpcEndpoint {
  targetUri: string;
}

export interface SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa {
  certificateProviderInstance: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa_CertificateProviderInstance[];
  grpcEndpoint: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa_GrpcEndpoint[];
}

export interface SecurityServerTlsPolicy_MtlsPolicy {
  clientValidationMode: string;
  clientValidationTrustConfig: string;
  clientValidationCa: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa[];
}

export interface SecurityServerTlsPolicy_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa_CertificateProviderInstanceFields: FieldMap = {
  pluginInstance: "plugin_instance",
};

const SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa_GrpcEndpointFields: FieldMap = {
  targetUri: "target_uri",
};

const SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCaFields: FieldMap = {
  certificateProviderInstance: {
    wireName: "certificate_provider_instance",
    kind: "list",
    fields: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa_CertificateProviderInstanceFields,
  },
  grpcEndpoint: {
    wireName: "grpc_endpoint",
    kind: "list",
    fields: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa_GrpcEndpointFields,
  },
};

const SecurityServerTlsPolicy_MtlsPolicyFields: FieldMap = {
  clientValidationMode: "client_validation_mode",
  clientValidationTrustConfig: "client_validation_trust_config",
  clientValidationCa: {
    wireName: "client_validation_ca",
    kind: "list",
    fields: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCaFields,
  },
};

const SecurityServerTlsPolicy_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SecurityServerTlsPolicyConfig {
  allowOpen?: boolean | Computed<boolean>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location?: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  mtlsPolicy?: SecurityServerTlsPolicy_MtlsPolicy[] | Computed<SecurityServerTlsPolicy_MtlsPolicy[]>;
  serverCertificate?: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa[] | Computed<SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa[]>;
  timeouts?: SecurityServerTlsPolicy_Timeouts | Computed<SecurityServerTlsPolicy_Timeouts>;
}

export interface SecurityServerTlsPolicyAttrs {
  allowOpen: boolean;
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  id: string;
  labels: Record<string, string>;
  location: string;
  name: string;
  project: string;
  terraformLabels: Record<string, string>;
  updateTime: string;
  mtlsPolicy: SecurityServerTlsPolicy_MtlsPolicy[];
  serverCertificate: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCa[];
  timeouts: SecurityServerTlsPolicy_Timeouts;
}

export const SecurityServerTlsPolicy: ResourceBinding<SecurityServerTlsPolicyConfig, SecurityServerTlsPolicyAttrs> = {
  wireType: "google_network_security_server_tls_policy",
  fields: {
    allowOpen: "allow_open",
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    labels: "labels",
    location: "location",
    name: "name",
    project: "project",
    mtlsPolicy: {
      wireName: "mtls_policy",
      kind: "list",
      fields: SecurityServerTlsPolicy_MtlsPolicyFields,
    },
    serverCertificate: {
      wireName: "server_certificate",
      kind: "list",
      fields: SecurityServerTlsPolicy_MtlsPolicy_ClientValidationCaFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SecurityServerTlsPolicy_TimeoutsFields,
    },
  },
};
