// Code generated by `ubx sdk gen` from google_network_security_intercept_deployment_group. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SecurityInterceptDeploymentGroup_ConnectedEndpointGroups {
  name: string;
}

export interface SecurityInterceptDeploymentGroup_Locations {
  location: string;
  state: string;
}

export interface SecurityInterceptDeploymentGroup_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const SecurityInterceptDeploymentGroup_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SecurityInterceptDeploymentGroupConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  interceptDeploymentGroupId: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  network: string | Computed<string>;
  project?: string | Computed<string>;
  timeouts?: SecurityInterceptDeploymentGroup_Timeouts | Computed<SecurityInterceptDeploymentGroup_Timeouts>;
}

export interface SecurityInterceptDeploymentGroupAttrs {
  connectedEndpointGroups: SecurityInterceptDeploymentGroup_ConnectedEndpointGroups[];
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  id: string;
  interceptDeploymentGroupId: string;
  labels: Record<string, string>;
  location: string;
  locations: SecurityInterceptDeploymentGroup_Locations[];
  name: string;
  network: string;
  project: string;
  reconciling: boolean;
  state: string;
  terraformLabels: Record<string, string>;
  updateTime: string;
  timeouts: SecurityInterceptDeploymentGroup_Timeouts;
}

export const SecurityInterceptDeploymentGroup: ResourceBinding<SecurityInterceptDeploymentGroupConfig, SecurityInterceptDeploymentGroupAttrs> = {
  wireType: "google_network_security_intercept_deployment_group",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    interceptDeploymentGroupId: "intercept_deployment_group_id",
    labels: "labels",
    location: "location",
    network: "network",
    project: "project",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SecurityInterceptDeploymentGroup_TimeoutsFields,
    },
  },
};
