// Code generated by `ubx sdk gen` from google_network_security_mirroring_endpoint_group. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SecurityMirroringEndpointGroup_Associations {
  name: string;
  network: string;
  state: string;
}

export interface SecurityMirroringEndpointGroup_ConnectedDeploymentGroups_Locations {
  location: string;
  state: string;
}

export interface SecurityMirroringEndpointGroup_ConnectedDeploymentGroups {
  locations: SecurityMirroringEndpointGroup_ConnectedDeploymentGroups_Locations[];
  name: string;
}

export interface SecurityMirroringEndpointGroup_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const SecurityMirroringEndpointGroup_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SecurityMirroringEndpointGroupConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  mirroringDeploymentGroup?: string | Computed<string>;
  mirroringDeploymentGroups?: string[] | Computed<string[]>;
  mirroringEndpointGroupId: string | Computed<string>;
  project?: string | Computed<string>;
  type?: string | Computed<string>;
  timeouts?: SecurityMirroringEndpointGroup_Timeouts | Computed<SecurityMirroringEndpointGroup_Timeouts>;
}

export interface SecurityMirroringEndpointGroupAttrs {
  associations: SecurityMirroringEndpointGroup_Associations[];
  connectedDeploymentGroups: SecurityMirroringEndpointGroup_ConnectedDeploymentGroups[];
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  id: string;
  labels: Record<string, string>;
  location: string;
  mirroringDeploymentGroup: string;
  mirroringDeploymentGroups: string[];
  mirroringEndpointGroupId: string;
  name: string;
  project: string;
  reconciling: boolean;
  state: string;
  terraformLabels: Record<string, string>;
  type: string;
  updateTime: string;
  timeouts: SecurityMirroringEndpointGroup_Timeouts;
}

export const SecurityMirroringEndpointGroup: ResourceBinding<SecurityMirroringEndpointGroupConfig, SecurityMirroringEndpointGroupAttrs> = {
  wireType: "google_network_security_mirroring_endpoint_group",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    labels: "labels",
    location: "location",
    mirroringDeploymentGroup: "mirroring_deployment_group",
    mirroringDeploymentGroups: "mirroring_deployment_groups",
    mirroringEndpointGroupId: "mirroring_endpoint_group_id",
    project: "project",
    type: "type",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SecurityMirroringEndpointGroup_TimeoutsFields,
    },
  },
};
