// Code generated by `ubx sdk gen` from google_network_services_grpc_route. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ServicesGrpcRoute_Rules_Action_Destinations {
  serviceName: string;
  weight: number;
}

export interface ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy_Abort {
  httpStatus: number;
  percentage: number;
}

export interface ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy_Delay {
  fixedDelay: string;
  percentage: number;
}

export interface ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy {
  abort: ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy_Abort[];
  delay: ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy_Delay[];
}

export interface ServicesGrpcRoute_Rules_Action_RetryPolicy {
  numRetries: number;
  retryConditions: string[];
}

export interface ServicesGrpcRoute_Rules_Action {
  timeout: string;
  destinations: ServicesGrpcRoute_Rules_Action_Destinations[];
  faultInjectionPolicy: ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy[];
  retryPolicy: ServicesGrpcRoute_Rules_Action_RetryPolicy[];
}

export interface ServicesGrpcRoute_Rules_Matches_Headers {
  key: string;
  type: string;
  value: string;
}

export interface ServicesGrpcRoute_Rules_Matches_Method {
  caseSensitive: boolean;
  grpcMethod: string;
  grpcService: string;
}

export interface ServicesGrpcRoute_Rules_Matches {
  headers: ServicesGrpcRoute_Rules_Matches_Headers[];
  method: ServicesGrpcRoute_Rules_Matches_Method[];
}

export interface ServicesGrpcRoute_Rules {
  action: ServicesGrpcRoute_Rules_Action[];
  matches: ServicesGrpcRoute_Rules_Matches[];
}

export interface ServicesGrpcRoute_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ServicesGrpcRoute_Rules_Action_DestinationsFields: FieldMap = {
  serviceName: "service_name",
  weight: "weight",
};

const ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy_AbortFields: FieldMap = {
  httpStatus: "http_status",
  percentage: "percentage",
};

const ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy_DelayFields: FieldMap = {
  fixedDelay: "fixed_delay",
  percentage: "percentage",
};

const ServicesGrpcRoute_Rules_Action_FaultInjectionPolicyFields: FieldMap = {
  abort: {
    wireName: "abort",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy_AbortFields,
  },
  delay: {
    wireName: "delay",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_Action_FaultInjectionPolicy_DelayFields,
  },
};

const ServicesGrpcRoute_Rules_Action_RetryPolicyFields: FieldMap = {
  numRetries: "num_retries",
  retryConditions: "retry_conditions",
};

const ServicesGrpcRoute_Rules_ActionFields: FieldMap = {
  timeout: "timeout",
  destinations: {
    wireName: "destinations",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_Action_DestinationsFields,
  },
  faultInjectionPolicy: {
    wireName: "fault_injection_policy",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_Action_FaultInjectionPolicyFields,
  },
  retryPolicy: {
    wireName: "retry_policy",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_Action_RetryPolicyFields,
  },
};

const ServicesGrpcRoute_Rules_Matches_HeadersFields: FieldMap = {
  key: "key",
  type: "type",
  value: "value",
};

const ServicesGrpcRoute_Rules_Matches_MethodFields: FieldMap = {
  caseSensitive: "case_sensitive",
  grpcMethod: "grpc_method",
  grpcService: "grpc_service",
};

const ServicesGrpcRoute_Rules_MatchesFields: FieldMap = {
  headers: {
    wireName: "headers",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_Matches_HeadersFields,
  },
  method: {
    wireName: "method",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_Matches_MethodFields,
  },
};

const ServicesGrpcRoute_RulesFields: FieldMap = {
  action: {
    wireName: "action",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_ActionFields,
  },
  matches: {
    wireName: "matches",
    kind: "list",
    fields: ServicesGrpcRoute_Rules_MatchesFields,
  },
};

const ServicesGrpcRoute_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ServicesGrpcRouteConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  gateways?: string[] | Computed<string[]>;
  hostnames: string[] | Computed<string[]>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location?: string | Computed<string>;
  meshes?: string[] | Computed<string[]>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  rules?: ServicesGrpcRoute_Rules[] | Computed<ServicesGrpcRoute_Rules[]>;
  timeouts?: ServicesGrpcRoute_Timeouts | Computed<ServicesGrpcRoute_Timeouts>;
}

export interface ServicesGrpcRouteAttrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  gateways: string[];
  hostnames: string[];
  id: string;
  labels: Record<string, string>;
  location: string;
  meshes: string[];
  name: string;
  project: string;
  selfLink: string;
  terraformLabels: Record<string, string>;
  updateTime: string;
  rules: ServicesGrpcRoute_Rules[];
  timeouts: ServicesGrpcRoute_Timeouts;
}

export const ServicesGrpcRoute: ResourceBinding<ServicesGrpcRouteConfig, ServicesGrpcRouteAttrs> = {
  wireType: "google_network_services_grpc_route",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    gateways: "gateways",
    hostnames: "hostnames",
    id: "id",
    labels: "labels",
    location: "location",
    meshes: "meshes",
    name: "name",
    project: "project",
    rules: {
      wireName: "rules",
      kind: "list",
      fields: ServicesGrpcRoute_RulesFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ServicesGrpcRoute_TimeoutsFields,
    },
  },
};
