// Code generated by `ubx sdk gen` from google_network_services_multicast_domain_group. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ServicesMulticastDomainGroup_State {
  state: string;
}

export interface ServicesMulticastDomainGroup_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ServicesMulticastDomainGroup_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ServicesMulticastDomainGroupConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  multicastDomainGroupId: string | Computed<string>;
  project?: string | Computed<string>;
  timeouts?: ServicesMulticastDomainGroup_Timeouts | Computed<ServicesMulticastDomainGroup_Timeouts>;
}

export interface ServicesMulticastDomainGroupAttrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  id: string;
  labels: Record<string, string>;
  location: string;
  multicastDomainGroupId: string;
  multicastDomains: string[];
  name: string;
  project: string;
  state: ServicesMulticastDomainGroup_State[];
  terraformLabels: Record<string, string>;
  uniqueId: string;
  updateTime: string;
  timeouts: ServicesMulticastDomainGroup_Timeouts;
}

export const ServicesMulticastDomainGroup: ResourceBinding<ServicesMulticastDomainGroupConfig, ServicesMulticastDomainGroupAttrs> = {
  wireType: "google_network_services_multicast_domain_group",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    labels: "labels",
    location: "location",
    multicastDomainGroupId: "multicast_domain_group_id",
    project: "project",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ServicesMulticastDomainGroup_TimeoutsFields,
    },
  },
};
