// Code generated by `ubx sdk gen` from google_project_access_approval_settings. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AccessApprovalSettings_EnrolledServices {
  cloudProduct: string;
  enrollmentLevel: string;
}

export interface AccessApprovalSettings_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const AccessApprovalSettings_EnrolledServicesFields: FieldMap = {
  cloudProduct: "cloud_product",
  enrollmentLevel: "enrollment_level",
};

const AccessApprovalSettings_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface AccessApprovalSettingsConfig {
  activeKeyVersion?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  notificationEmails?: string[] | Computed<string[]>;
  project?: string | Computed<string>;
  projectId: string | Computed<string>;
  enrolledServices?: AccessApprovalSettings_EnrolledServices[] | Computed<AccessApprovalSettings_EnrolledServices[]>;
  timeouts?: AccessApprovalSettings_Timeouts | Computed<AccessApprovalSettings_Timeouts>;
}

export interface AccessApprovalSettingsAttrs {
  activeKeyVersion: string;
  ancestorHasActiveKeyVersion: boolean;
  deletionPolicy: string;
  enrolledAncestor: boolean;
  id: string;
  invalidKeyVersion: boolean;
  name: string;
  notificationEmails: string[];
  project: string;
  projectId: string;
  enrolledServices: AccessApprovalSettings_EnrolledServices[];
  timeouts: AccessApprovalSettings_Timeouts;
}

export const AccessApprovalSettings: ResourceBinding<AccessApprovalSettingsConfig, AccessApprovalSettingsAttrs> = {
  wireType: "google_project_access_approval_settings",
  fields: {
    activeKeyVersion: "active_key_version",
    deletionPolicy: "deletion_policy",
    id: "id",
    notificationEmails: "notification_emails",
    project: "project",
    projectId: "project_id",
    enrolledServices: {
      wireName: "enrolled_services",
      kind: "set",
      fields: AccessApprovalSettings_EnrolledServicesFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AccessApprovalSettings_TimeoutsFields,
    },
  },
};
