// Code generated by `ubx sdk gen` from google_firebase_app_check_app_attest_config. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AppCheckAppAttestConfig_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const AppCheckAppAttestConfig_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface AppCheckAppAttestConfigConfig {
  appId: string | Computed<string>;
  id?: string | Computed<string>;
  project?: string | Computed<string>;
  tokenTtl?: string | Computed<string>;
  timeouts?: AppCheckAppAttestConfig_Timeouts | Computed<AppCheckAppAttestConfig_Timeouts>;
}

export interface AppCheckAppAttestConfigAttrs {
  appId: string;
  id: string;
  name: string;
  project: string;
  tokenTtl: string;
  timeouts: AppCheckAppAttestConfig_Timeouts;
}

export const AppCheckAppAttestConfig: ResourceBinding<AppCheckAppAttestConfigConfig, AppCheckAppAttestConfigAttrs> = {
  wireType: "google_firebase_app_check_app_attest_config",
  fields: {
    appId: "app_id",
    id: "id",
    project: "project",
    tokenTtl: "token_ttl",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AppCheckAppAttestConfig_TimeoutsFields,
    },
  },
};
