// Code generated by `ubx sdk gen` from google_iam_workforce_pool_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface WorkforcePoolIamPolicyConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  policyData: string | Computed<string>;
  workforcePoolId: string | Computed<string>;
}

export interface WorkforcePoolIamPolicyAttrs {
  etag: string;
  id: string;
  location: string;
  policyData: string;
  workforcePoolId: string;
}

export const WorkforcePoolIamPolicy: ResourceBinding<WorkforcePoolIamPolicyConfig, WorkforcePoolIamPolicyAttrs> = {
  wireType: "google_iam_workforce_pool_iam_policy",
  fields: {
    id: "id",
    location: "location",
    policyData: "policy_data",
    workforcePoolId: "workforce_pool_id",
  },
};
