// Code generated by `ubx sdk gen` from google_iam_workload_identity_pool. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface WorkloadIdentityPool_AttestationRules {
  googleCloudResource: string;
}

export interface WorkloadIdentityPool_InlineCertificateIssuanceConfig {
  caPools: Record<string, string>;
  keyAlgorithm: string;
  lifetime: string;
  rotationWindowPercentage: number;
  useDefaultSharedCa: boolean;
}

export interface WorkloadIdentityPool_InlineTrustConfig_AdditionalTrustBundles_TrustAnchors {
  pemCertificate: string;
}

export interface WorkloadIdentityPool_InlineTrustConfig_AdditionalTrustBundles {
  trustDefaultSharedCa: boolean;
  trustDomain: string;
  trustAnchors: WorkloadIdentityPool_InlineTrustConfig_AdditionalTrustBundles_TrustAnchors[];
}

export interface WorkloadIdentityPool_InlineTrustConfig {
  additionalTrustBundles: WorkloadIdentityPool_InlineTrustConfig_AdditionalTrustBundles[];
}

export interface WorkloadIdentityPool_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const WorkloadIdentityPool_AttestationRulesFields: FieldMap = {
  googleCloudResource: "google_cloud_resource",
};

const WorkloadIdentityPool_InlineCertificateIssuanceConfigFields: FieldMap = {
  caPools: "ca_pools",
  keyAlgorithm: "key_algorithm",
  lifetime: "lifetime",
  rotationWindowPercentage: "rotation_window_percentage",
  useDefaultSharedCa: "use_default_shared_ca",
};

const WorkloadIdentityPool_InlineTrustConfig_AdditionalTrustBundles_TrustAnchorsFields: FieldMap = {
  pemCertificate: "pem_certificate",
};

const WorkloadIdentityPool_InlineTrustConfig_AdditionalTrustBundlesFields: FieldMap = {
  trustDefaultSharedCa: "trust_default_shared_ca",
  trustDomain: "trust_domain",
  trustAnchors: {
    wireName: "trust_anchors",
    kind: "list",
    fields: WorkloadIdentityPool_InlineTrustConfig_AdditionalTrustBundles_TrustAnchorsFields,
  },
};

const WorkloadIdentityPool_InlineTrustConfigFields: FieldMap = {
  additionalTrustBundles: {
    wireName: "additional_trust_bundles",
    kind: "set",
    fields: WorkloadIdentityPool_InlineTrustConfig_AdditionalTrustBundlesFields,
  },
};

const WorkloadIdentityPool_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface WorkloadIdentityPoolConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  mode?: string | Computed<string>;
  project?: string | Computed<string>;
  workloadIdentityPoolId: string | Computed<string>;
  attestationRules?: WorkloadIdentityPool_AttestationRules[] | Computed<WorkloadIdentityPool_AttestationRules[]>;
  inlineCertificateIssuanceConfig?: WorkloadIdentityPool_InlineCertificateIssuanceConfig[] | Computed<WorkloadIdentityPool_InlineCertificateIssuanceConfig[]>;
  inlineTrustConfig?: WorkloadIdentityPool_InlineTrustConfig[] | Computed<WorkloadIdentityPool_InlineTrustConfig[]>;
  timeouts?: WorkloadIdentityPool_Timeouts | Computed<WorkloadIdentityPool_Timeouts>;
}

export interface WorkloadIdentityPoolAttrs {
  deletionPolicy: string;
  description: string;
  disabled: boolean;
  displayName: string;
  id: string;
  mode: string;
  name: string;
  project: string;
  state: string;
  workloadIdentityPoolId: string;
  attestationRules: WorkloadIdentityPool_AttestationRules[];
  inlineCertificateIssuanceConfig: WorkloadIdentityPool_InlineCertificateIssuanceConfig[];
  inlineTrustConfig: WorkloadIdentityPool_InlineTrustConfig[];
  timeouts: WorkloadIdentityPool_Timeouts;
}

export const WorkloadIdentityPool: ResourceBinding<WorkloadIdentityPoolConfig, WorkloadIdentityPoolAttrs> = {
  wireType: "google_iam_workload_identity_pool",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    disabled: "disabled",
    displayName: "display_name",
    id: "id",
    mode: "mode",
    project: "project",
    workloadIdentityPoolId: "workload_identity_pool_id",
    attestationRules: {
      wireName: "attestation_rules",
      kind: "set",
      fields: WorkloadIdentityPool_AttestationRulesFields,
    },
    inlineCertificateIssuanceConfig: {
      wireName: "inline_certificate_issuance_config",
      kind: "list",
      fields: WorkloadIdentityPool_InlineCertificateIssuanceConfigFields,
    },
    inlineTrustConfig: {
      wireName: "inline_trust_config",
      kind: "list",
      fields: WorkloadIdentityPool_InlineTrustConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: WorkloadIdentityPool_TimeoutsFields,
    },
  },
};
