// Code generated by `ubx sdk gen` from google_iam_workload_identity_pool_managed_identity. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface WorkloadIdentityPoolManagedIdentity_AttestationRules {
  googleCloudResource: string;
}

export interface WorkloadIdentityPoolManagedIdentity_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const WorkloadIdentityPoolManagedIdentity_AttestationRulesFields: FieldMap = {
  googleCloudResource: "google_cloud_resource",
};

const WorkloadIdentityPoolManagedIdentity_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface WorkloadIdentityPoolManagedIdentityConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  project?: string | Computed<string>;
  workloadIdentityPoolId: string | Computed<string>;
  workloadIdentityPoolManagedIdentityId: string | Computed<string>;
  workloadIdentityPoolNamespaceId: string | Computed<string>;
  attestationRules?: WorkloadIdentityPoolManagedIdentity_AttestationRules[] | Computed<WorkloadIdentityPoolManagedIdentity_AttestationRules[]>;
  timeouts?: WorkloadIdentityPoolManagedIdentity_Timeouts | Computed<WorkloadIdentityPoolManagedIdentity_Timeouts>;
}

export interface WorkloadIdentityPoolManagedIdentityAttrs {
  deletionPolicy: string;
  description: string;
  disabled: boolean;
  id: string;
  name: string;
  project: string;
  state: string;
  workloadIdentityPoolId: string;
  workloadIdentityPoolManagedIdentityId: string;
  workloadIdentityPoolNamespaceId: string;
  attestationRules: WorkloadIdentityPoolManagedIdentity_AttestationRules[];
  timeouts: WorkloadIdentityPoolManagedIdentity_Timeouts;
}

export const WorkloadIdentityPoolManagedIdentity: ResourceBinding<WorkloadIdentityPoolManagedIdentityConfig, WorkloadIdentityPoolManagedIdentityAttrs> = {
  wireType: "google_iam_workload_identity_pool_managed_identity",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    disabled: "disabled",
    id: "id",
    project: "project",
    workloadIdentityPoolId: "workload_identity_pool_id",
    workloadIdentityPoolManagedIdentityId: "workload_identity_pool_managed_identity_id",
    workloadIdentityPoolNamespaceId: "workload_identity_pool_namespace_id",
    attestationRules: {
      wireName: "attestation_rules",
      kind: "set",
      fields: WorkloadIdentityPoolManagedIdentity_AttestationRulesFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: WorkloadIdentityPoolManagedIdentity_TimeoutsFields,
    },
  },
};
