// Code generated by `ubx sdk gen` from google_dataproc_autoscaling_policy_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AutoscalingPolicyIamPolicyConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  policyData: string | Computed<string>;
  policyId: string | Computed<string>;
  project?: string | Computed<string>;
}

export interface AutoscalingPolicyIamPolicyAttrs {
  etag: string;
  id: string;
  location: string;
  policyData: string;
  policyId: string;
  project: string;
}

export const AutoscalingPolicyIamPolicy: ResourceBinding<AutoscalingPolicyIamPolicyConfig, AutoscalingPolicyIamPolicyAttrs> = {
  wireType: "google_dataproc_autoscaling_policy_iam_policy",
  fields: {
    id: "id",
    location: "location",
    policyData: "policy_data",
    policyId: "policy_id",
    project: "project",
  },
};
