// Code generated by `ubx sdk gen` from google_dataproc_job_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface JobIamPolicyConfig {
  id?: string | Computed<string>;
  jobId: string | Computed<string>;
  policyData: string | Computed<string>;
  project?: string | Computed<string>;
  region?: string | Computed<string>;
}

export interface JobIamPolicyAttrs {
  etag: string;
  id: string;
  jobId: string;
  policyData: string;
  project: string;
  region: string;
}

export const JobIamPolicy: ResourceBinding<JobIamPolicyConfig, JobIamPolicyAttrs> = {
  wireType: "google_dataproc_job_iam_policy",
  fields: {
    id: "id",
    jobId: "job_id",
    policyData: "policy_data",
    project: "project",
    region: "region",
  },
};
