// Code generated by `ubx sdk gen` from google_dataproc_metastore_service_iam_member. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MetastoreServiceIamMember_Condition {
  description: string;
  expression: string;
  title: string;
}

const MetastoreServiceIamMember_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface MetastoreServiceIamMemberConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  member: string | Computed<string>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  serviceId: string | Computed<string>;
  condition?: MetastoreServiceIamMember_Condition[] | Computed<MetastoreServiceIamMember_Condition[]>;
}

export interface MetastoreServiceIamMemberAttrs {
  etag: string;
  id: string;
  location: string;
  member: string;
  project: string;
  role: string;
  serviceId: string;
  condition: MetastoreServiceIamMember_Condition[];
}

export const MetastoreServiceIamMember: ResourceBinding<MetastoreServiceIamMemberConfig, MetastoreServiceIamMemberAttrs> = {
  wireType: "google_dataproc_metastore_service_iam_member",
  fields: {
    id: "id",
    location: "location",
    member: "member",
    project: "project",
    role: "role",
    serviceId: "service_id",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: MetastoreServiceIamMember_ConditionFields,
    },
  },
};
