// Code generated by `ubx sdk gen` from google_os_config_os_policy_assignment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConfigOsPolicyAssignment_InstanceFilter_ExclusionLabels {
  labels: Record<string, string>;
}

export interface ConfigOsPolicyAssignment_InstanceFilter_Inventories {
  osShortName: string;
  osVersion: string;
}

export interface ConfigOsPolicyAssignment_InstanceFilter {
  all: boolean;
  exclusionLabels: ConfigOsPolicyAssignment_InstanceFilter_ExclusionLabels[];
  inclusionLabels: ConfigOsPolicyAssignment_InstanceFilter_ExclusionLabels[];
  inventories: ConfigOsPolicyAssignment_InstanceFilter_Inventories[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File_Gcs {
  bucket: string;
  generation: number;
  object: string;
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File_Remote {
  sha256Checksum: string;
  uri: string;
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File {
  allowInsecure: boolean;
  localPath: string;
  gcs: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File_Gcs[];
  remote: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File_Remote[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce {
  args: string[];
  interpreter: string;
  outputFilePath: string;
  script: string;
  file: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec {
  enforce: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce[];
  validate: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_File {
  content: string;
  path: string;
  permissions: string;
  state: string;
  file: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Apt {
  name: string;
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Deb {
  pullDeps: boolean;
  source: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Msi {
  properties: string[];
  source: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg {
  desiredState: string;
  apt: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Apt[];
  deb: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Deb[];
  googet: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Apt[];
  msi: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Msi[];
  rpm: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Deb[];
  yum: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Apt[];
  zypper: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_Apt[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_Apt {
  archiveType: string;
  components: string[];
  distribution: string;
  gpgKey: string;
  uri: string;
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_Goo {
  name: string;
  url: string;
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_Yum {
  baseUrl: string;
  displayName: string;
  gpgKeys: string[];
  id: string;
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository {
  apt: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_Apt[];
  goo: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_Goo[];
  yum: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_Yum[];
  zypper: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_Yum[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources {
  id: string;
  exec: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec[];
  file: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_File[];
  pkg: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg[];
  repository: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository[];
}

export interface ConfigOsPolicyAssignment_OsPolicies_ResourceGroups {
  inventoryFilters: ConfigOsPolicyAssignment_InstanceFilter_Inventories[];
  resources: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources[];
}

export interface ConfigOsPolicyAssignment_OsPolicies {
  allowNoResourceGroupMatch: boolean;
  description: string;
  id: string;
  mode: string;
  resourceGroups: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups[];
}

export interface ConfigOsPolicyAssignment_Rollout_DisruptionBudget {
  fixed: number;
  percent: number;
}

export interface ConfigOsPolicyAssignment_Rollout {
  minWaitDuration: string;
  disruptionBudget: ConfigOsPolicyAssignment_Rollout_DisruptionBudget[];
}

export interface ConfigOsPolicyAssignment_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ConfigOsPolicyAssignment_InstanceFilter_ExclusionLabelsFields: FieldMap = {
  labels: "labels",
};

const ConfigOsPolicyAssignment_InstanceFilter_InventoriesFields: FieldMap = {
  osShortName: "os_short_name",
  osVersion: "os_version",
};

const ConfigOsPolicyAssignment_InstanceFilterFields: FieldMap = {
  all: "all",
  exclusionLabels: {
    wireName: "exclusion_labels",
    kind: "list",
    fields: ConfigOsPolicyAssignment_InstanceFilter_ExclusionLabelsFields,
  },
  inclusionLabels: {
    wireName: "inclusion_labels",
    kind: "list",
    fields: ConfigOsPolicyAssignment_InstanceFilter_ExclusionLabelsFields,
  },
  inventories: {
    wireName: "inventories",
    kind: "list",
    fields: ConfigOsPolicyAssignment_InstanceFilter_InventoriesFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File_GcsFields: FieldMap = {
  bucket: "bucket",
  generation: "generation",
  object: "object",
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File_RemoteFields: FieldMap = {
  sha256Checksum: "sha256_checksum",
  uri: "uri",
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_FileFields: FieldMap = {
  allowInsecure: "allow_insecure",
  localPath: "local_path",
  gcs: {
    wireName: "gcs",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File_GcsFields,
  },
  remote: {
    wireName: "remote",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_File_RemoteFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_EnforceFields: FieldMap = {
  args: "args",
  interpreter: "interpreter",
  outputFilePath: "output_file_path",
  script: "script",
  file: {
    wireName: "file",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_FileFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_ExecFields: FieldMap = {
  enforce: {
    wireName: "enforce",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_EnforceFields,
  },
  validate: {
    wireName: "validate",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_EnforceFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_FileFields: FieldMap = {
  content: "content",
  path: "path",
  permissions: "permissions",
  state: "state",
  file: {
    wireName: "file",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_FileFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_AptFields: FieldMap = {
  name: "name",
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_DebFields: FieldMap = {
  pullDeps: "pull_deps",
  source: {
    wireName: "source",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_FileFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_MsiFields: FieldMap = {
  properties: "properties",
  source: {
    wireName: "source",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Exec_Enforce_FileFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_PkgFields: FieldMap = {
  desiredState: "desired_state",
  apt: {
    wireName: "apt",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_AptFields,
  },
  deb: {
    wireName: "deb",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_DebFields,
  },
  googet: {
    wireName: "googet",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_AptFields,
  },
  msi: {
    wireName: "msi",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_MsiFields,
  },
  rpm: {
    wireName: "rpm",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_DebFields,
  },
  yum: {
    wireName: "yum",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_AptFields,
  },
  zypper: {
    wireName: "zypper",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Pkg_AptFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_AptFields: FieldMap = {
  archiveType: "archive_type",
  components: "components",
  distribution: "distribution",
  gpgKey: "gpg_key",
  uri: "uri",
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_GooFields: FieldMap = {
  name: "name",
  url: "url",
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_YumFields: FieldMap = {
  baseUrl: "base_url",
  displayName: "display_name",
  gpgKeys: "gpg_keys",
  id: "id",
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_RepositoryFields: FieldMap = {
  apt: {
    wireName: "apt",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_AptFields,
  },
  goo: {
    wireName: "goo",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_GooFields,
  },
  yum: {
    wireName: "yum",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_YumFields,
  },
  zypper: {
    wireName: "zypper",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_Repository_YumFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_ResourcesFields: FieldMap = {
  id: "id",
  exec: {
    wireName: "exec",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_ExecFields,
  },
  file: {
    wireName: "file",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_FileFields,
  },
  pkg: {
    wireName: "pkg",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_PkgFields,
  },
  repository: {
    wireName: "repository",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_Resources_RepositoryFields,
  },
};

const ConfigOsPolicyAssignment_OsPolicies_ResourceGroupsFields: FieldMap = {
  inventoryFilters: {
    wireName: "inventory_filters",
    kind: "list",
    fields: ConfigOsPolicyAssignment_InstanceFilter_InventoriesFields,
  },
  resources: {
    wireName: "resources",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroups_ResourcesFields,
  },
};

const ConfigOsPolicyAssignment_OsPoliciesFields: FieldMap = {
  allowNoResourceGroupMatch: "allow_no_resource_group_match",
  description: "description",
  id: "id",
  mode: "mode",
  resourceGroups: {
    wireName: "resource_groups",
    kind: "list",
    fields: ConfigOsPolicyAssignment_OsPolicies_ResourceGroupsFields,
  },
};

const ConfigOsPolicyAssignment_Rollout_DisruptionBudgetFields: FieldMap = {
  fixed: "fixed",
  percent: "percent",
};

const ConfigOsPolicyAssignment_RolloutFields: FieldMap = {
  minWaitDuration: "min_wait_duration",
  disruptionBudget: {
    wireName: "disruption_budget",
    kind: "list",
    fields: ConfigOsPolicyAssignment_Rollout_DisruptionBudgetFields,
  },
};

const ConfigOsPolicyAssignment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ConfigOsPolicyAssignmentConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  skipAwaitRollout?: boolean | Computed<boolean>;
  instanceFilter?: ConfigOsPolicyAssignment_InstanceFilter[] | Computed<ConfigOsPolicyAssignment_InstanceFilter[]>;
  osPolicies?: ConfigOsPolicyAssignment_OsPolicies[] | Computed<ConfigOsPolicyAssignment_OsPolicies[]>;
  rollout?: ConfigOsPolicyAssignment_Rollout[] | Computed<ConfigOsPolicyAssignment_Rollout[]>;
  timeouts?: ConfigOsPolicyAssignment_Timeouts | Computed<ConfigOsPolicyAssignment_Timeouts>;
}

export interface ConfigOsPolicyAssignmentAttrs {
  baseline: boolean;
  deleted: boolean;
  deletionPolicy: string;
  description: string;
  etag: string;
  id: string;
  location: string;
  name: string;
  project: string;
  reconciling: boolean;
  revisionCreateTime: string;
  revisionId: string;
  rolloutState: string;
  skipAwaitRollout: boolean;
  uid: string;
  instanceFilter: ConfigOsPolicyAssignment_InstanceFilter[];
  osPolicies: ConfigOsPolicyAssignment_OsPolicies[];
  rollout: ConfigOsPolicyAssignment_Rollout[];
  timeouts: ConfigOsPolicyAssignment_Timeouts;
}

export const ConfigOsPolicyAssignment: ResourceBinding<ConfigOsPolicyAssignmentConfig, ConfigOsPolicyAssignmentAttrs> = {
  wireType: "google_os_config_os_policy_assignment",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    location: "location",
    name: "name",
    project: "project",
    skipAwaitRollout: "skip_await_rollout",
    instanceFilter: {
      wireName: "instance_filter",
      kind: "list",
      fields: ConfigOsPolicyAssignment_InstanceFilterFields,
    },
    osPolicies: {
      wireName: "os_policies",
      kind: "list",
      fields: ConfigOsPolicyAssignment_OsPoliciesFields,
    },
    rollout: {
      wireName: "rollout",
      kind: "list",
      fields: ConfigOsPolicyAssignment_RolloutFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ConfigOsPolicyAssignment_TimeoutsFields,
    },
  },
};
