// Code generated by `ubx sdk gen` from google_dialogflow_fulfillment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Fulfillment_Features {
  type: string;
}

export interface Fulfillment_GenericWebService {
  password: string;
  requestHeaders: Record<string, string>;
  uri: string;
  username: string;
}

export interface Fulfillment_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const Fulfillment_FeaturesFields: FieldMap = {
  type: "type",
};

const Fulfillment_GenericWebServiceFields: FieldMap = {
  password: "password",
  requestHeaders: "request_headers",
  uri: "uri",
  username: "username",
};

const Fulfillment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface FulfillmentConfig {
  deletionPolicy?: string | Computed<string>;
  displayName: string | Computed<string>;
  enabled?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  project?: string | Computed<string>;
  features?: Fulfillment_Features[] | Computed<Fulfillment_Features[]>;
  genericWebService?: Fulfillment_GenericWebService[] | Computed<Fulfillment_GenericWebService[]>;
  timeouts?: Fulfillment_Timeouts | Computed<Fulfillment_Timeouts>;
}

export interface FulfillmentAttrs {
  deletionPolicy: string;
  displayName: string;
  enabled: boolean;
  id: string;
  name: string;
  project: string;
  features: Fulfillment_Features[];
  genericWebService: Fulfillment_GenericWebService[];
  timeouts: Fulfillment_Timeouts;
}

export const Fulfillment: ResourceBinding<FulfillmentConfig, FulfillmentAttrs> = {
  wireType: "google_dialogflow_fulfillment",
  fields: {
    deletionPolicy: "deletion_policy",
    displayName: "display_name",
    enabled: "enabled",
    id: "id",
    project: "project",
    features: {
      wireName: "features",
      kind: "list",
      fields: Fulfillment_FeaturesFields,
    },
    genericWebService: {
      wireName: "generic_web_service",
      kind: "list",
      fields: Fulfillment_GenericWebServiceFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Fulfillment_TimeoutsFields,
    },
  },
};
