// Code generated by `ubx sdk gen` from google_dialogflow_generator. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Generator_InferenceParameter {
  maxOutputTokens: number;
  temperature: number;
  topK: number;
  topP: number;
}

export interface Generator_SummarizationContext_FewShotExamples_ConversationContext_MessageEntries {
  createTime: string;
  languageCode: string;
  role: string;
  text: string;
}

export interface Generator_SummarizationContext_FewShotExamples_ConversationContext {
  messageEntries: Generator_SummarizationContext_FewShotExamples_ConversationContext_MessageEntries[];
}

export interface Generator_SummarizationContext_FewShotExamples_Output_SummarySuggestion_SummarySections {
  section: string;
  summary: string;
}

export interface Generator_SummarizationContext_FewShotExamples_Output_SummarySuggestion {
  summarySections: Generator_SummarizationContext_FewShotExamples_Output_SummarySuggestion_SummarySections[];
}

export interface Generator_SummarizationContext_FewShotExamples_Output {
  summarySuggestion: Generator_SummarizationContext_FewShotExamples_Output_SummarySuggestion[];
}

export interface Generator_SummarizationContext_FewShotExamples_SummarizationSectionList_SummarizationSections {
  definition: string;
  key: string;
  type: string;
}

export interface Generator_SummarizationContext_FewShotExamples_SummarizationSectionList {
  summarizationSections: Generator_SummarizationContext_FewShotExamples_SummarizationSectionList_SummarizationSections[];
}

export interface Generator_SummarizationContext_FewShotExamples {
  extraInfo: Record<string, string>;
  conversationContext: Generator_SummarizationContext_FewShotExamples_ConversationContext[];
  output: Generator_SummarizationContext_FewShotExamples_Output[];
  summarizationSectionList: Generator_SummarizationContext_FewShotExamples_SummarizationSectionList[];
}

export interface Generator_SummarizationContext {
  outputLanguageCode: string;
  version: string;
  fewShotExamples: Generator_SummarizationContext_FewShotExamples[];
  summarizationSections: Generator_SummarizationContext_FewShotExamples_SummarizationSectionList_SummarizationSections[];
}

export interface Generator_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const Generator_InferenceParameterFields: FieldMap = {
  maxOutputTokens: "max_output_tokens",
  temperature: "temperature",
  topK: "top_k",
  topP: "top_p",
};

const Generator_SummarizationContext_FewShotExamples_ConversationContext_MessageEntriesFields: FieldMap = {
  createTime: "create_time",
  languageCode: "language_code",
  role: "role",
  text: "text",
};

const Generator_SummarizationContext_FewShotExamples_ConversationContextFields: FieldMap = {
  messageEntries: {
    wireName: "message_entries",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamples_ConversationContext_MessageEntriesFields,
  },
};

const Generator_SummarizationContext_FewShotExamples_Output_SummarySuggestion_SummarySectionsFields: FieldMap = {
  section: "section",
  summary: "summary",
};

const Generator_SummarizationContext_FewShotExamples_Output_SummarySuggestionFields: FieldMap = {
  summarySections: {
    wireName: "summary_sections",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamples_Output_SummarySuggestion_SummarySectionsFields,
  },
};

const Generator_SummarizationContext_FewShotExamples_OutputFields: FieldMap = {
  summarySuggestion: {
    wireName: "summary_suggestion",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamples_Output_SummarySuggestionFields,
  },
};

const Generator_SummarizationContext_FewShotExamples_SummarizationSectionList_SummarizationSectionsFields: FieldMap = {
  definition: "definition",
  key: "key",
  type: "type",
};

const Generator_SummarizationContext_FewShotExamples_SummarizationSectionListFields: FieldMap = {
  summarizationSections: {
    wireName: "summarization_sections",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamples_SummarizationSectionList_SummarizationSectionsFields,
  },
};

const Generator_SummarizationContext_FewShotExamplesFields: FieldMap = {
  extraInfo: "extra_info",
  conversationContext: {
    wireName: "conversation_context",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamples_ConversationContextFields,
  },
  output: {
    wireName: "output",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamples_OutputFields,
  },
  summarizationSectionList: {
    wireName: "summarization_section_list",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamples_SummarizationSectionListFields,
  },
};

const Generator_SummarizationContextFields: FieldMap = {
  outputLanguageCode: "output_language_code",
  version: "version",
  fewShotExamples: {
    wireName: "few_shot_examples",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamplesFields,
  },
  summarizationSections: {
    wireName: "summarization_sections",
    kind: "list",
    fields: Generator_SummarizationContext_FewShotExamples_SummarizationSectionList_SummarizationSectionsFields,
  },
};

const Generator_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface GeneratorConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  generatorId?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  publishedModel?: string | Computed<string>;
  triggerEvent?: string | Computed<string>;
  inferenceParameter?: Generator_InferenceParameter[] | Computed<Generator_InferenceParameter[]>;
  summarizationContext?: Generator_SummarizationContext[] | Computed<Generator_SummarizationContext[]>;
  timeouts?: Generator_Timeouts | Computed<Generator_Timeouts>;
}

export interface GeneratorAttrs {
  deletionPolicy: string;
  description: string;
  generatorId: string;
  id: string;
  location: string;
  name: string;
  project: string;
  publishedModel: string;
  triggerEvent: string;
  inferenceParameter: Generator_InferenceParameter[];
  summarizationContext: Generator_SummarizationContext[];
  timeouts: Generator_Timeouts;
}

export const Generator: ResourceBinding<GeneratorConfig, GeneratorAttrs> = {
  wireType: "google_dialogflow_generator",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    generatorId: "generator_id",
    id: "id",
    location: "location",
    project: "project",
    publishedModel: "published_model",
    triggerEvent: "trigger_event",
    inferenceParameter: {
      wireName: "inference_parameter",
      kind: "list",
      fields: Generator_InferenceParameterFields,
    },
    summarizationContext: {
      wireName: "summarization_context",
      kind: "list",
      fields: Generator_SummarizationContextFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Generator_TimeoutsFields,
    },
  },
};
