// Code generated by `ubx sdk gen` from google_access_context_manager_access_levels. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ContextManagerAccessLevels_AccessLevels_Basic_Conditions_DevicePolicy_OsConstraints {
  minimumVersion: string;
  osType: string;
}

export interface ContextManagerAccessLevels_AccessLevels_Basic_Conditions_DevicePolicy {
  allowedDeviceManagementLevels: string[];
  allowedEncryptionStatuses: string[];
  requireAdminApproval: boolean;
  requireCorpOwned: boolean;
  requireScreenLock: boolean;
  osConstraints: ContextManagerAccessLevels_AccessLevels_Basic_Conditions_DevicePolicy_OsConstraints[];
}

export interface ContextManagerAccessLevels_AccessLevels_Basic_Conditions_VpcNetworkSources_VpcSubnetwork {
  network: string;
  vpcIpSubnetworks: string[];
}

export interface ContextManagerAccessLevels_AccessLevels_Basic_Conditions_VpcNetworkSources {
  vpcSubnetwork: ContextManagerAccessLevels_AccessLevels_Basic_Conditions_VpcNetworkSources_VpcSubnetwork[];
}

export interface ContextManagerAccessLevels_AccessLevels_Basic_Conditions {
  ipSubnetworks: string[];
  members: string[];
  negate: boolean;
  regions: string[];
  requiredAccessLevels: string[];
  devicePolicy: ContextManagerAccessLevels_AccessLevels_Basic_Conditions_DevicePolicy[];
  vpcNetworkSources: ContextManagerAccessLevels_AccessLevels_Basic_Conditions_VpcNetworkSources[];
}

export interface ContextManagerAccessLevels_AccessLevels_Basic {
  combiningFunction: string;
  conditions: ContextManagerAccessLevels_AccessLevels_Basic_Conditions[];
}

export interface ContextManagerAccessLevels_AccessLevels_Custom_Expr {
  description: string;
  expression: string;
  location: string;
  title: string;
}

export interface ContextManagerAccessLevels_AccessLevels_Custom {
  expr: ContextManagerAccessLevels_AccessLevels_Custom_Expr[];
}

export interface ContextManagerAccessLevels_AccessLevels {
  description: string;
  name: string;
  title: string;
  basic: ContextManagerAccessLevels_AccessLevels_Basic[];
  custom: ContextManagerAccessLevels_AccessLevels_Custom[];
}

export interface ContextManagerAccessLevels_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ContextManagerAccessLevels_AccessLevels_Basic_Conditions_DevicePolicy_OsConstraintsFields: FieldMap = {
  minimumVersion: "minimum_version",
  osType: "os_type",
};

const ContextManagerAccessLevels_AccessLevels_Basic_Conditions_DevicePolicyFields: FieldMap = {
  allowedDeviceManagementLevels: "allowed_device_management_levels",
  allowedEncryptionStatuses: "allowed_encryption_statuses",
  requireAdminApproval: "require_admin_approval",
  requireCorpOwned: "require_corp_owned",
  requireScreenLock: "require_screen_lock",
  osConstraints: {
    wireName: "os_constraints",
    kind: "list",
    fields: ContextManagerAccessLevels_AccessLevels_Basic_Conditions_DevicePolicy_OsConstraintsFields,
  },
};

const ContextManagerAccessLevels_AccessLevels_Basic_Conditions_VpcNetworkSources_VpcSubnetworkFields: FieldMap = {
  network: "network",
  vpcIpSubnetworks: "vpc_ip_subnetworks",
};

const ContextManagerAccessLevels_AccessLevels_Basic_Conditions_VpcNetworkSourcesFields: FieldMap = {
  vpcSubnetwork: {
    wireName: "vpc_subnetwork",
    kind: "list",
    fields: ContextManagerAccessLevels_AccessLevels_Basic_Conditions_VpcNetworkSources_VpcSubnetworkFields,
  },
};

const ContextManagerAccessLevels_AccessLevels_Basic_ConditionsFields: FieldMap = {
  ipSubnetworks: "ip_subnetworks",
  members: "members",
  negate: "negate",
  regions: "regions",
  requiredAccessLevels: "required_access_levels",
  devicePolicy: {
    wireName: "device_policy",
    kind: "list",
    fields: ContextManagerAccessLevels_AccessLevels_Basic_Conditions_DevicePolicyFields,
  },
  vpcNetworkSources: {
    wireName: "vpc_network_sources",
    kind: "list",
    fields: ContextManagerAccessLevels_AccessLevels_Basic_Conditions_VpcNetworkSourcesFields,
  },
};

const ContextManagerAccessLevels_AccessLevels_BasicFields: FieldMap = {
  combiningFunction: "combining_function",
  conditions: {
    wireName: "conditions",
    kind: "list",
    fields: ContextManagerAccessLevels_AccessLevels_Basic_ConditionsFields,
  },
};

const ContextManagerAccessLevels_AccessLevels_Custom_ExprFields: FieldMap = {
  description: "description",
  expression: "expression",
  location: "location",
  title: "title",
};

const ContextManagerAccessLevels_AccessLevels_CustomFields: FieldMap = {
  expr: {
    wireName: "expr",
    kind: "list",
    fields: ContextManagerAccessLevels_AccessLevels_Custom_ExprFields,
  },
};

const ContextManagerAccessLevels_AccessLevelsFields: FieldMap = {
  description: "description",
  name: "name",
  title: "title",
  basic: {
    wireName: "basic",
    kind: "list",
    fields: ContextManagerAccessLevels_AccessLevels_BasicFields,
  },
  custom: {
    wireName: "custom",
    kind: "list",
    fields: ContextManagerAccessLevels_AccessLevels_CustomFields,
  },
};

const ContextManagerAccessLevels_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ContextManagerAccessLevelsConfig {
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  parent: string | Computed<string>;
  accessLevels?: ContextManagerAccessLevels_AccessLevels[] | Computed<ContextManagerAccessLevels_AccessLevels[]>;
  timeouts?: ContextManagerAccessLevels_Timeouts | Computed<ContextManagerAccessLevels_Timeouts>;
}

export interface ContextManagerAccessLevelsAttrs {
  deletionPolicy: string;
  id: string;
  parent: string;
  accessLevels: ContextManagerAccessLevels_AccessLevels[];
  timeouts: ContextManagerAccessLevels_Timeouts;
}

export const ContextManagerAccessLevels: ResourceBinding<ContextManagerAccessLevelsConfig, ContextManagerAccessLevelsAttrs> = {
  wireType: "google_access_context_manager_access_levels",
  fields: {
    deletionPolicy: "deletion_policy",
    id: "id",
    parent: "parent",
    accessLevels: {
      wireName: "access_levels",
      kind: "set",
      fields: ContextManagerAccessLevels_AccessLevelsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ContextManagerAccessLevels_TimeoutsFields,
    },
  },
};
