// Code generated by `ubx sdk gen` from google_access_context_manager_authorized_orgs_desc. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ContextManagerAuthorizedOrgsDesc_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ContextManagerAuthorizedOrgsDesc_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ContextManagerAuthorizedOrgsDescConfig {
  assetType?: string | Computed<string>;
  authorizationDirection?: string | Computed<string>;
  authorizationType?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  orgs?: string[] | Computed<string[]>;
  parent: string | Computed<string>;
  timeouts?: ContextManagerAuthorizedOrgsDesc_Timeouts | Computed<ContextManagerAuthorizedOrgsDesc_Timeouts>;
}

export interface ContextManagerAuthorizedOrgsDescAttrs {
  assetType: string;
  authorizationDirection: string;
  authorizationType: string;
  createTime: string;
  deletionPolicy: string;
  id: string;
  name: string;
  orgs: string[];
  parent: string;
  updateTime: string;
  timeouts: ContextManagerAuthorizedOrgsDesc_Timeouts;
}

export const ContextManagerAuthorizedOrgsDesc: ResourceBinding<ContextManagerAuthorizedOrgsDescConfig, ContextManagerAuthorizedOrgsDescAttrs> = {
  wireType: "google_access_context_manager_authorized_orgs_desc",
  fields: {
    assetType: "asset_type",
    authorizationDirection: "authorization_direction",
    authorizationType: "authorization_type",
    deletionPolicy: "deletion_policy",
    id: "id",
    name: "name",
    orgs: "orgs",
    parent: "parent",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ContextManagerAuthorizedOrgsDesc_TimeoutsFields,
    },
  },
};
