// Code generated by `ubx sdk gen` from google_access_context_manager_access_level. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ContextManagerAccessLevel_Basic_Conditions_DevicePolicy_OsConstraints {
  minimumVersion: string;
  osType: string;
  requireVerifiedChromeOs: boolean;
}

export interface ContextManagerAccessLevel_Basic_Conditions_DevicePolicy {
  allowedDeviceManagementLevels: string[];
  allowedEncryptionStatuses: string[];
  requireAdminApproval: boolean;
  requireCorpOwned: boolean;
  requireScreenLock: boolean;
  osConstraints: ContextManagerAccessLevel_Basic_Conditions_DevicePolicy_OsConstraints[];
}

export interface ContextManagerAccessLevel_Basic_Conditions_VpcNetworkSources_VpcSubnetwork {
  network: string;
  vpcIpSubnetworks: string[];
}

export interface ContextManagerAccessLevel_Basic_Conditions_VpcNetworkSources {
  vpcSubnetwork: ContextManagerAccessLevel_Basic_Conditions_VpcNetworkSources_VpcSubnetwork[];
}

export interface ContextManagerAccessLevel_Basic_Conditions {
  ipSubnetworks: string[];
  members: string[];
  negate: boolean;
  regions: string[];
  requiredAccessLevels: string[];
  devicePolicy: ContextManagerAccessLevel_Basic_Conditions_DevicePolicy[];
  vpcNetworkSources: ContextManagerAccessLevel_Basic_Conditions_VpcNetworkSources[];
}

export interface ContextManagerAccessLevel_Basic {
  combiningFunction: string;
  conditions: ContextManagerAccessLevel_Basic_Conditions[];
}

export interface ContextManagerAccessLevel_Custom_Expr {
  description: string;
  expression: string;
  location: string;
  title: string;
}

export interface ContextManagerAccessLevel_Custom {
  expr: ContextManagerAccessLevel_Custom_Expr[];
}

export interface ContextManagerAccessLevel_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ContextManagerAccessLevel_Basic_Conditions_DevicePolicy_OsConstraintsFields: FieldMap = {
  minimumVersion: "minimum_version",
  osType: "os_type",
  requireVerifiedChromeOs: "require_verified_chrome_os",
};

const ContextManagerAccessLevel_Basic_Conditions_DevicePolicyFields: FieldMap = {
  allowedDeviceManagementLevels: "allowed_device_management_levels",
  allowedEncryptionStatuses: "allowed_encryption_statuses",
  requireAdminApproval: "require_admin_approval",
  requireCorpOwned: "require_corp_owned",
  requireScreenLock: "require_screen_lock",
  osConstraints: {
    wireName: "os_constraints",
    kind: "list",
    fields: ContextManagerAccessLevel_Basic_Conditions_DevicePolicy_OsConstraintsFields,
  },
};

const ContextManagerAccessLevel_Basic_Conditions_VpcNetworkSources_VpcSubnetworkFields: FieldMap = {
  network: "network",
  vpcIpSubnetworks: "vpc_ip_subnetworks",
};

const ContextManagerAccessLevel_Basic_Conditions_VpcNetworkSourcesFields: FieldMap = {
  vpcSubnetwork: {
    wireName: "vpc_subnetwork",
    kind: "list",
    fields: ContextManagerAccessLevel_Basic_Conditions_VpcNetworkSources_VpcSubnetworkFields,
  },
};

const ContextManagerAccessLevel_Basic_ConditionsFields: FieldMap = {
  ipSubnetworks: "ip_subnetworks",
  members: "members",
  negate: "negate",
  regions: "regions",
  requiredAccessLevels: "required_access_levels",
  devicePolicy: {
    wireName: "device_policy",
    kind: "list",
    fields: ContextManagerAccessLevel_Basic_Conditions_DevicePolicyFields,
  },
  vpcNetworkSources: {
    wireName: "vpc_network_sources",
    kind: "list",
    fields: ContextManagerAccessLevel_Basic_Conditions_VpcNetworkSourcesFields,
  },
};

const ContextManagerAccessLevel_BasicFields: FieldMap = {
  combiningFunction: "combining_function",
  conditions: {
    wireName: "conditions",
    kind: "list",
    fields: ContextManagerAccessLevel_Basic_ConditionsFields,
  },
};

const ContextManagerAccessLevel_Custom_ExprFields: FieldMap = {
  description: "description",
  expression: "expression",
  location: "location",
  title: "title",
};

const ContextManagerAccessLevel_CustomFields: FieldMap = {
  expr: {
    wireName: "expr",
    kind: "list",
    fields: ContextManagerAccessLevel_Custom_ExprFields,
  },
};

const ContextManagerAccessLevel_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ContextManagerAccessLevelConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  parent: string | Computed<string>;
  title: string | Computed<string>;
  basic?: ContextManagerAccessLevel_Basic[] | Computed<ContextManagerAccessLevel_Basic[]>;
  custom?: ContextManagerAccessLevel_Custom[] | Computed<ContextManagerAccessLevel_Custom[]>;
  timeouts?: ContextManagerAccessLevel_Timeouts | Computed<ContextManagerAccessLevel_Timeouts>;
}

export interface ContextManagerAccessLevelAttrs {
  deletionPolicy: string;
  description: string;
  id: string;
  name: string;
  parent: string;
  title: string;
  basic: ContextManagerAccessLevel_Basic[];
  custom: ContextManagerAccessLevel_Custom[];
  timeouts: ContextManagerAccessLevel_Timeouts;
}

export const ContextManagerAccessLevel: ResourceBinding<ContextManagerAccessLevelConfig, ContextManagerAccessLevelAttrs> = {
  wireType: "google_access_context_manager_access_level",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    name: "name",
    parent: "parent",
    title: "title",
    basic: {
      wireName: "basic",
      kind: "list",
      fields: ContextManagerAccessLevel_BasicFields,
    },
    custom: {
      wireName: "custom",
      kind: "list",
      fields: ContextManagerAccessLevel_CustomFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ContextManagerAccessLevel_TimeoutsFields,
    },
  },
};
