// Code generated by `ubx sdk gen` from google_gke_backup_backup_plan. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface BackupBackupPlan_BackupConfig_EncryptionKey {
  gcpKmsEncryptionKey: string;
}

export interface BackupBackupPlan_BackupConfig_SelectedApplications_NamespacedNames {
  name: string;
  namespace: string;
}

export interface BackupBackupPlan_BackupConfig_SelectedApplications {
  namespacedNames: BackupBackupPlan_BackupConfig_SelectedApplications_NamespacedNames[];
}

export interface BackupBackupPlan_BackupConfig_SelectedNamespaceLabels_ResourceLabels {
  key: string;
  value: string;
}

export interface BackupBackupPlan_BackupConfig_SelectedNamespaceLabels {
  resourceLabels: BackupBackupPlan_BackupConfig_SelectedNamespaceLabels_ResourceLabels[];
}

export interface BackupBackupPlan_BackupConfig_SelectedNamespaces {
  namespaces: string[];
}

export interface BackupBackupPlan_BackupConfig {
  allNamespaces: boolean;
  includeSecrets: boolean;
  includeVolumeData: boolean;
  permissiveMode: boolean;
  encryptionKey: BackupBackupPlan_BackupConfig_EncryptionKey[];
  selectedApplications: BackupBackupPlan_BackupConfig_SelectedApplications[];
  selectedNamespaceLabels: BackupBackupPlan_BackupConfig_SelectedNamespaceLabels[];
  selectedNamespaces: BackupBackupPlan_BackupConfig_SelectedNamespaces[];
}

export interface BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_DaysOfWeek {
  daysOfWeek: string[];
}

export interface BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_SingleOccurrenceDate {
  day: number;
  month: number;
  year: number;
}

export interface BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_StartTime {
  hours: number;
  minutes: number;
  nanos: number;
  seconds: number;
}

export interface BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows {
  daily: boolean;
  duration: string;
  daysOfWeek: BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_DaysOfWeek[];
  singleOccurrenceDate: BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_SingleOccurrenceDate[];
  startTime: BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_StartTime[];
}

export interface BackupBackupPlan_BackupSchedule_RpoConfig {
  targetRpoMinutes: number;
  exclusionWindows: BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows[];
}

export interface BackupBackupPlan_BackupSchedule {
  cronSchedule: string;
  paused: boolean;
  rpoConfig: BackupBackupPlan_BackupSchedule_RpoConfig[];
}

export interface BackupBackupPlan_RetentionPolicy {
  backupDeleteLockDays: number;
  backupRetainDays: number;
  locked: boolean;
}

export interface BackupBackupPlan_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const BackupBackupPlan_BackupConfig_EncryptionKeyFields: FieldMap = {
  gcpKmsEncryptionKey: "gcp_kms_encryption_key",
};

const BackupBackupPlan_BackupConfig_SelectedApplications_NamespacedNamesFields: FieldMap = {
  name: "name",
  namespace: "namespace",
};

const BackupBackupPlan_BackupConfig_SelectedApplicationsFields: FieldMap = {
  namespacedNames: {
    wireName: "namespaced_names",
    kind: "list",
    fields: BackupBackupPlan_BackupConfig_SelectedApplications_NamespacedNamesFields,
  },
};

const BackupBackupPlan_BackupConfig_SelectedNamespaceLabels_ResourceLabelsFields: FieldMap = {
  key: "key",
  value: "value",
};

const BackupBackupPlan_BackupConfig_SelectedNamespaceLabelsFields: FieldMap = {
  resourceLabels: {
    wireName: "resource_labels",
    kind: "list",
    fields: BackupBackupPlan_BackupConfig_SelectedNamespaceLabels_ResourceLabelsFields,
  },
};

const BackupBackupPlan_BackupConfig_SelectedNamespacesFields: FieldMap = {
  namespaces: "namespaces",
};

const BackupBackupPlan_BackupConfigFields: FieldMap = {
  allNamespaces: "all_namespaces",
  includeSecrets: "include_secrets",
  includeVolumeData: "include_volume_data",
  permissiveMode: "permissive_mode",
  encryptionKey: {
    wireName: "encryption_key",
    kind: "list",
    fields: BackupBackupPlan_BackupConfig_EncryptionKeyFields,
  },
  selectedApplications: {
    wireName: "selected_applications",
    kind: "list",
    fields: BackupBackupPlan_BackupConfig_SelectedApplicationsFields,
  },
  selectedNamespaceLabels: {
    wireName: "selected_namespace_labels",
    kind: "list",
    fields: BackupBackupPlan_BackupConfig_SelectedNamespaceLabelsFields,
  },
  selectedNamespaces: {
    wireName: "selected_namespaces",
    kind: "list",
    fields: BackupBackupPlan_BackupConfig_SelectedNamespacesFields,
  },
};

const BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_DaysOfWeekFields: FieldMap = {
  daysOfWeek: "days_of_week",
};

const BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_SingleOccurrenceDateFields: FieldMap = {
  day: "day",
  month: "month",
  year: "year",
};

const BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_StartTimeFields: FieldMap = {
  hours: "hours",
  minutes: "minutes",
  nanos: "nanos",
  seconds: "seconds",
};

const BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindowsFields: FieldMap = {
  daily: "daily",
  duration: "duration",
  daysOfWeek: {
    wireName: "days_of_week",
    kind: "list",
    fields: BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_DaysOfWeekFields,
  },
  singleOccurrenceDate: {
    wireName: "single_occurrence_date",
    kind: "list",
    fields: BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_SingleOccurrenceDateFields,
  },
  startTime: {
    wireName: "start_time",
    kind: "list",
    fields: BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindows_StartTimeFields,
  },
};

const BackupBackupPlan_BackupSchedule_RpoConfigFields: FieldMap = {
  targetRpoMinutes: "target_rpo_minutes",
  exclusionWindows: {
    wireName: "exclusion_windows",
    kind: "list",
    fields: BackupBackupPlan_BackupSchedule_RpoConfig_ExclusionWindowsFields,
  },
};

const BackupBackupPlan_BackupScheduleFields: FieldMap = {
  cronSchedule: "cron_schedule",
  paused: "paused",
  rpoConfig: {
    wireName: "rpo_config",
    kind: "list",
    fields: BackupBackupPlan_BackupSchedule_RpoConfigFields,
  },
};

const BackupBackupPlan_RetentionPolicyFields: FieldMap = {
  backupDeleteLockDays: "backup_delete_lock_days",
  backupRetainDays: "backup_retain_days",
  locked: "locked",
};

const BackupBackupPlan_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface BackupBackupPlanConfig {
  cluster: string | Computed<string>;
  deactivated?: boolean | Computed<boolean>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  backupConfig?: BackupBackupPlan_BackupConfig[] | Computed<BackupBackupPlan_BackupConfig[]>;
  backupSchedule?: BackupBackupPlan_BackupSchedule[] | Computed<BackupBackupPlan_BackupSchedule[]>;
  retentionPolicy?: BackupBackupPlan_RetentionPolicy[] | Computed<BackupBackupPlan_RetentionPolicy[]>;
  timeouts?: BackupBackupPlan_Timeouts | Computed<BackupBackupPlan_Timeouts>;
}

export interface BackupBackupPlanAttrs {
  cluster: string;
  deactivated: boolean;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  etag: string;
  id: string;
  labels: Record<string, string>;
  location: string;
  name: string;
  project: string;
  protectedNamespaceCount: number;
  protectedPodCount: number;
  state: string;
  stateReason: string;
  terraformLabels: Record<string, string>;
  uid: string;
  backupConfig: BackupBackupPlan_BackupConfig[];
  backupSchedule: BackupBackupPlan_BackupSchedule[];
  retentionPolicy: BackupBackupPlan_RetentionPolicy[];
  timeouts: BackupBackupPlan_Timeouts;
}

export const BackupBackupPlan: ResourceBinding<BackupBackupPlanConfig, BackupBackupPlanAttrs> = {
  wireType: "google_gke_backup_backup_plan",
  fields: {
    cluster: "cluster",
    deactivated: "deactivated",
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    labels: "labels",
    location: "location",
    name: "name",
    project: "project",
    backupConfig: {
      wireName: "backup_config",
      kind: "list",
      fields: BackupBackupPlan_BackupConfigFields,
    },
    backupSchedule: {
      wireName: "backup_schedule",
      kind: "list",
      fields: BackupBackupPlan_BackupScheduleFields,
    },
    retentionPolicy: {
      wireName: "retention_policy",
      kind: "list",
      fields: BackupBackupPlan_RetentionPolicyFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: BackupBackupPlan_TimeoutsFields,
    },
  },
};
