// Code generated by `ubx sdk gen` from google_gke_hub_membership. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HubMembership_Authority {
  issuer: string;
}

export interface HubMembership_Endpoint_GkeCluster {
  resourceLink: string;
}

export interface HubMembership_Endpoint {
  gkeCluster: HubMembership_Endpoint_GkeCluster[];
}

export interface HubMembership_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const HubMembership_AuthorityFields: FieldMap = {
  issuer: "issuer",
};

const HubMembership_Endpoint_GkeClusterFields: FieldMap = {
  resourceLink: "resource_link",
};

const HubMembership_EndpointFields: FieldMap = {
  gkeCluster: {
    wireName: "gke_cluster",
    kind: "list",
    fields: HubMembership_Endpoint_GkeClusterFields,
  },
};

const HubMembership_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface HubMembershipConfig {
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location?: string | Computed<string>;
  membershipId: string | Computed<string>;
  project?: string | Computed<string>;
  authority?: HubMembership_Authority[] | Computed<HubMembership_Authority[]>;
  endpoint?: HubMembership_Endpoint[] | Computed<HubMembership_Endpoint[]>;
  timeouts?: HubMembership_Timeouts | Computed<HubMembership_Timeouts>;
}

export interface HubMembershipAttrs {
  deletionPolicy: string;
  effectiveLabels: Record<string, string>;
  id: string;
  labels: Record<string, string>;
  location: string;
  membershipId: string;
  name: string;
  project: string;
  terraformLabels: Record<string, string>;
  authority: HubMembership_Authority[];
  endpoint: HubMembership_Endpoint[];
  timeouts: HubMembership_Timeouts;
}

export const HubMembership: ResourceBinding<HubMembershipConfig, HubMembershipAttrs> = {
  wireType: "google_gke_hub_membership",
  fields: {
    deletionPolicy: "deletion_policy",
    id: "id",
    labels: "labels",
    location: "location",
    membershipId: "membership_id",
    project: "project",
    authority: {
      wireName: "authority",
      kind: "list",
      fields: HubMembership_AuthorityFields,
    },
    endpoint: {
      wireName: "endpoint",
      kind: "list",
      fields: HubMembership_EndpointFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: HubMembership_TimeoutsFields,
    },
  },
};
