// Code generated by `ubx sdk gen` from google_gke_hub_feature_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface HubFeatureIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const HubFeatureIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface HubFeatureIamBindingConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  condition?: HubFeatureIamBinding_Condition[] | Computed<HubFeatureIamBinding_Condition[]>;
}

export interface HubFeatureIamBindingAttrs {
  etag: string;
  id: string;
  location: string;
  members: string[];
  name: string;
  project: string;
  role: string;
  condition: HubFeatureIamBinding_Condition[];
}

export const HubFeatureIamBinding: ResourceBinding<HubFeatureIamBindingConfig, HubFeatureIamBindingAttrs> = {
  wireType: "google_gke_hub_feature_iam_binding",
  fields: {
    id: "id",
    location: "location",
    members: "members",
    name: "name",
    project: "project",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: HubFeatureIamBinding_ConditionFields,
    },
  },
};
