// Code generated by `ubx sdk gen` from google_storage_control_folder_intelligence_config. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ControlFolderIntelligenceConfig_EffectiveIntelligenceConfig {
  effectiveEdition: string;
  intelligenceConfig: string;
}

export interface ControlFolderIntelligenceConfig_TrialConfig {
  expireTime: string;
}

export interface ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageBuckets {
  bucketIdRegexes: string[];
}

export interface ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageLocations {
  locations: string[];
}

export interface ControlFolderIntelligenceConfig_Filter {
  excludedCloudStorageBuckets: ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageBuckets[];
  excludedCloudStorageLocations: ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageLocations[];
  includedCloudStorageBuckets: ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageBuckets[];
  includedCloudStorageLocations: ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageLocations[];
}

export interface ControlFolderIntelligenceConfig_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageBucketsFields: FieldMap = {
  bucketIdRegexes: "bucket_id_regexes",
};

const ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageLocationsFields: FieldMap = {
  locations: "locations",
};

const ControlFolderIntelligenceConfig_FilterFields: FieldMap = {
  excludedCloudStorageBuckets: {
    wireName: "excluded_cloud_storage_buckets",
    kind: "list",
    fields: ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageBucketsFields,
  },
  excludedCloudStorageLocations: {
    wireName: "excluded_cloud_storage_locations",
    kind: "list",
    fields: ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageLocationsFields,
  },
  includedCloudStorageBuckets: {
    wireName: "included_cloud_storage_buckets",
    kind: "list",
    fields: ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageBucketsFields,
  },
  includedCloudStorageLocations: {
    wireName: "included_cloud_storage_locations",
    kind: "list",
    fields: ControlFolderIntelligenceConfig_Filter_ExcludedCloudStorageLocationsFields,
  },
};

const ControlFolderIntelligenceConfig_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ControlFolderIntelligenceConfigConfig {
  editionConfig?: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  filter?: ControlFolderIntelligenceConfig_Filter[] | Computed<ControlFolderIntelligenceConfig_Filter[]>;
  timeouts?: ControlFolderIntelligenceConfig_Timeouts | Computed<ControlFolderIntelligenceConfig_Timeouts>;
}

export interface ControlFolderIntelligenceConfigAttrs {
  editionConfig: string;
  effectiveIntelligenceConfig: ControlFolderIntelligenceConfig_EffectiveIntelligenceConfig[];
  id: string;
  name: string;
  trialConfig: ControlFolderIntelligenceConfig_TrialConfig[];
  updateTime: string;
  filter: ControlFolderIntelligenceConfig_Filter[];
  timeouts: ControlFolderIntelligenceConfig_Timeouts;
}

export const ControlFolderIntelligenceConfig: ResourceBinding<ControlFolderIntelligenceConfigConfig, ControlFolderIntelligenceConfigAttrs> = {
  wireType: "google_storage_control_folder_intelligence_config",
  fields: {
    editionConfig: "edition_config",
    id: "id",
    name: "name",
    filter: {
      wireName: "filter",
      kind: "list",
      fields: ControlFolderIntelligenceConfig_FilterFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ControlFolderIntelligenceConfig_TimeoutsFields,
    },
  },
};
