// Code generated by `ubx sdk gen` from google_storage_object_access_control. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ObjectAccessControl_ProjectTeam {
  projectNumber: string;
  team: string;
}

export interface ObjectAccessControl_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ObjectAccessControl_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ObjectAccessControlConfig {
  bucket: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  entity: string | Computed<string>;
  id?: string | Computed<string>;
  object: string | Computed<string>;
  role: string | Computed<string>;
  timeouts?: ObjectAccessControl_Timeouts | Computed<ObjectAccessControl_Timeouts>;
}

export interface ObjectAccessControlAttrs {
  bucket: string;
  deletionPolicy: string;
  domain: string;
  email: string;
  entity: string;
  entityId: string;
  generation: number;
  id: string;
  object: string;
  projectTeam: ObjectAccessControl_ProjectTeam[];
  role: string;
  timeouts: ObjectAccessControl_Timeouts;
}

export const ObjectAccessControl: ResourceBinding<ObjectAccessControlConfig, ObjectAccessControlAttrs> = {
  wireType: "google_storage_object_access_control",
  fields: {
    bucket: "bucket",
    deletionPolicy: "deletion_policy",
    entity: "entity",
    id: "id",
    object: "object",
    role: "role",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ObjectAccessControl_TimeoutsFields,
    },
  },
};
