// Code generated by `ubx sdk gen` from google_iap_app_engine_service_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AppEngineServiceIamPolicyConfig {
  appId: string | Computed<string>;
  id?: string | Computed<string>;
  policyData: string | Computed<string>;
  project?: string | Computed<string>;
  service: string | Computed<string>;
}

export interface AppEngineServiceIamPolicyAttrs {
  appId: string;
  etag: string;
  id: string;
  policyData: string;
  project: string;
  service: string;
}

export const AppEngineServiceIamPolicy: ResourceBinding<AppEngineServiceIamPolicyConfig, AppEngineServiceIamPolicyAttrs> = {
  wireType: "google_iap_app_engine_service_iam_policy",
  fields: {
    appId: "app_id",
    id: "id",
    policyData: "policy_data",
    project: "project",
    service: "service",
  },
};
