// Code generated by `ubx sdk gen` from google_iap_app_engine_version_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AppEngineVersionIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const AppEngineVersionIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface AppEngineVersionIamBindingConfig {
  appId: string | Computed<string>;
  id?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  service: string | Computed<string>;
  versionId: string | Computed<string>;
  condition?: AppEngineVersionIamBinding_Condition[] | Computed<AppEngineVersionIamBinding_Condition[]>;
}

export interface AppEngineVersionIamBindingAttrs {
  appId: string;
  etag: string;
  id: string;
  members: string[];
  project: string;
  role: string;
  service: string;
  versionId: string;
  condition: AppEngineVersionIamBinding_Condition[];
}

export const AppEngineVersionIamBinding: ResourceBinding<AppEngineVersionIamBindingConfig, AppEngineVersionIamBindingAttrs> = {
  wireType: "google_iap_app_engine_version_iam_binding",
  fields: {
    appId: "app_id",
    id: "id",
    members: "members",
    project: "project",
    role: "role",
    service: "service",
    versionId: "version_id",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: AppEngineVersionIamBinding_ConditionFields,
    },
  },
};
