// Code generated by `ubx sdk gen` from google_iap_brand. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Brand_Timeouts {
  create: string;
  delete: string;
}

const Brand_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
};

export interface BrandConfig {
  applicationTitle: string | Computed<string>;
  id?: string | Computed<string>;
  project?: string | Computed<string>;
  supportEmail: string | Computed<string>;
  timeouts?: Brand_Timeouts | Computed<Brand_Timeouts>;
}

export interface BrandAttrs {
  applicationTitle: string;
  id: string;
  name: string;
  orgInternalOnly: boolean;
  project: string;
  supportEmail: string;
  timeouts: Brand_Timeouts;
}

export const Brand: ResourceBinding<BrandConfig, BrandAttrs> = {
  wireType: "google_iap_brand",
  fields: {
    applicationTitle: "application_title",
    id: "id",
    project: "project",
    supportEmail: "support_email",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Brand_TimeoutsFields,
    },
  },
};
