// Code generated by `ubx sdk gen` from google_iap_location_web_iam_member. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LocationWebIamMember_Condition {
  description: string;
  expression: string;
  title: string;
}

const LocationWebIamMember_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface LocationWebIamMemberConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  member: string | Computed<string>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  condition?: LocationWebIamMember_Condition[] | Computed<LocationWebIamMember_Condition[]>;
}

export interface LocationWebIamMemberAttrs {
  etag: string;
  id: string;
  location: string;
  member: string;
  project: string;
  role: string;
  condition: LocationWebIamMember_Condition[];
}

export const LocationWebIamMember: ResourceBinding<LocationWebIamMemberConfig, LocationWebIamMemberAttrs> = {
  wireType: "google_iap_location_web_iam_member",
  fields: {
    id: "id",
    location: "location",
    member: "member",
    project: "project",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: LocationWebIamMember_ConditionFields,
    },
  },
};
