// Code generated by `ubx sdk gen` from google_folder. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Folder_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

const Folder_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

export interface FolderConfig {
  deletionPolicy?: string | Computed<string>;
  deletionProtection?: boolean | Computed<boolean>;
  displayName: string | Computed<string>;
  id?: string | Computed<string>;
  parent: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  timeouts?: Folder_Timeouts | Computed<Folder_Timeouts>;
}

export interface FolderAttrs {
  configuredCapabilities: string[];
  createTime: string;
  deletionPolicy: string;
  deletionProtection: boolean;
  displayName: string;
  folderId: string;
  id: string;
  lifecycleState: string;
  managementProject: string;
  name: string;
  parent: string;
  tags: Record<string, string>;
  timeouts: Folder_Timeouts;
}

export const Folder: ResourceBinding<FolderConfig, FolderAttrs> = {
  wireType: "google_folder",
  fields: {
    deletionPolicy: "deletion_policy",
    deletionProtection: "deletion_protection",
    displayName: "display_name",
    id: "id",
    parent: "parent",
    tags: "tags",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Folder_TimeoutsFields,
    },
  },
};
