// Code generated by `ubx sdk gen` from google_folder_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface IamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const IamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface IamBindingConfig {
  folder: string | Computed<string>;
  id?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  role: string | Computed<string>;
  condition?: IamBinding_Condition[] | Computed<IamBinding_Condition[]>;
}

export interface IamBindingAttrs {
  etag: string;
  folder: string;
  id: string;
  members: string[];
  role: string;
  condition: IamBinding_Condition[];
}

export const IamBinding: ResourceBinding<IamBindingConfig, IamBindingAttrs> = {
  wireType: "google_folder_iam_binding",
  fields: {
    folder: "folder",
    id: "id",
    members: "members",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: IamBinding_ConditionFields,
    },
  },
};
