// Code generated by `ubx sdk gen` from google_bigquery_data_transfer_config. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataTransferConfig_EmailPreferences {
  enableFailureEmail: boolean;
}

export interface DataTransferConfig_EncryptionConfiguration {
  kmsKeyName: string;
}

export interface DataTransferConfig_ScheduleOptions {
  disableAutoScheduling: boolean;
  endTime: string;
  startTime: string;
}

export interface DataTransferConfig_SensitiveParams {
  secretAccessKey: string;
  secretAccessKeyWo: string;
  secretAccessKeyWoVersion: number;
}

export interface DataTransferConfig_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const DataTransferConfig_EmailPreferencesFields: FieldMap = {
  enableFailureEmail: "enable_failure_email",
};

const DataTransferConfig_EncryptionConfigurationFields: FieldMap = {
  kmsKeyName: "kms_key_name",
};

const DataTransferConfig_ScheduleOptionsFields: FieldMap = {
  disableAutoScheduling: "disable_auto_scheduling",
  endTime: "end_time",
  startTime: "start_time",
};

const DataTransferConfig_SensitiveParamsFields: FieldMap = {
  secretAccessKey: "secret_access_key",
  secretAccessKeyWo: "secret_access_key_wo",
  secretAccessKeyWoVersion: "secret_access_key_wo_version",
};

const DataTransferConfig_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface DataTransferConfigConfig {
  dataRefreshWindowDays?: number | Computed<number>;
  dataSourceId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  destinationDatasetId?: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  displayName: string | Computed<string>;
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  notificationPubsubTopic?: string | Computed<string>;
  params: Record<string, string> | Computed<Record<string, string>>;
  project?: string | Computed<string>;
  schedule?: string | Computed<string>;
  serviceAccountName?: string | Computed<string>;
  emailPreferences?: DataTransferConfig_EmailPreferences[] | Computed<DataTransferConfig_EmailPreferences[]>;
  encryptionConfiguration?: DataTransferConfig_EncryptionConfiguration[] | Computed<DataTransferConfig_EncryptionConfiguration[]>;
  scheduleOptions?: DataTransferConfig_ScheduleOptions[] | Computed<DataTransferConfig_ScheduleOptions[]>;
  sensitiveParams?: DataTransferConfig_SensitiveParams[] | Computed<DataTransferConfig_SensitiveParams[]>;
  timeouts?: DataTransferConfig_Timeouts | Computed<DataTransferConfig_Timeouts>;
}

export interface DataTransferConfigAttrs {
  dataRefreshWindowDays: number;
  dataSourceId: string;
  deletionPolicy: string;
  destinationDatasetId: string;
  disabled: boolean;
  displayName: string;
  id: string;
  location: string;
  name: string;
  notificationPubsubTopic: string;
  params: Record<string, string>;
  project: string;
  schedule: string;
  serviceAccountName: string;
  emailPreferences: DataTransferConfig_EmailPreferences[];
  encryptionConfiguration: DataTransferConfig_EncryptionConfiguration[];
  scheduleOptions: DataTransferConfig_ScheduleOptions[];
  sensitiveParams: DataTransferConfig_SensitiveParams[];
  timeouts: DataTransferConfig_Timeouts;
}

export const DataTransferConfig: ResourceBinding<DataTransferConfigConfig, DataTransferConfigAttrs> = {
  wireType: "google_bigquery_data_transfer_config",
  fields: {
    dataRefreshWindowDays: "data_refresh_window_days",
    dataSourceId: "data_source_id",
    deletionPolicy: "deletion_policy",
    destinationDatasetId: "destination_dataset_id",
    disabled: "disabled",
    displayName: "display_name",
    id: "id",
    location: "location",
    notificationPubsubTopic: "notification_pubsub_topic",
    params: "params",
    project: "project",
    schedule: "schedule",
    serviceAccountName: "service_account_name",
    emailPreferences: {
      wireName: "email_preferences",
      kind: "list",
      fields: DataTransferConfig_EmailPreferencesFields,
    },
    encryptionConfiguration: {
      wireName: "encryption_configuration",
      kind: "list",
      fields: DataTransferConfig_EncryptionConfigurationFields,
    },
    scheduleOptions: {
      wireName: "schedule_options",
      kind: "list",
      fields: DataTransferConfig_ScheduleOptionsFields,
    },
    sensitiveParams: {
      wireName: "sensitive_params",
      kind: "list",
      fields: DataTransferConfig_SensitiveParamsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DataTransferConfig_TimeoutsFields,
    },
  },
};
