// Code generated by `ubx sdk gen` from google_bigquery_datapolicy_data_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DatapolicyDataPolicy_DataMaskingPolicy {
  predefinedExpression: string;
  routine: string;
}

export interface DatapolicyDataPolicy_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const DatapolicyDataPolicy_DataMaskingPolicyFields: FieldMap = {
  predefinedExpression: "predefined_expression",
  routine: "routine",
};

const DatapolicyDataPolicy_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface DatapolicyDataPolicyConfig {
  dataPolicyId: string | Computed<string>;
  dataPolicyType: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  policyTag: string | Computed<string>;
  project?: string | Computed<string>;
  dataMaskingPolicy?: DatapolicyDataPolicy_DataMaskingPolicy[] | Computed<DatapolicyDataPolicy_DataMaskingPolicy[]>;
  timeouts?: DatapolicyDataPolicy_Timeouts | Computed<DatapolicyDataPolicy_Timeouts>;
}

export interface DatapolicyDataPolicyAttrs {
  dataPolicyId: string;
  dataPolicyType: string;
  deletionPolicy: string;
  id: string;
  location: string;
  name: string;
  policyTag: string;
  project: string;
  dataMaskingPolicy: DatapolicyDataPolicy_DataMaskingPolicy[];
  timeouts: DatapolicyDataPolicy_Timeouts;
}

export const DatapolicyDataPolicy: ResourceBinding<DatapolicyDataPolicyConfig, DatapolicyDataPolicyAttrs> = {
  wireType: "google_bigquery_datapolicy_data_policy",
  fields: {
    dataPolicyId: "data_policy_id",
    dataPolicyType: "data_policy_type",
    deletionPolicy: "deletion_policy",
    id: "id",
    location: "location",
    policyTag: "policy_tag",
    project: "project",
    dataMaskingPolicy: {
      wireName: "data_masking_policy",
      kind: "list",
      fields: DatapolicyDataPolicy_DataMaskingPolicyFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DatapolicyDataPolicy_TimeoutsFields,
    },
  },
};
