// Code generated by `ubx sdk gen` from google_compute_firewall_policy_with_rules. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FirewallPolicyWithRules_PredefinedRules_Match_Layer4Config {
  ipProtocol: string;
  ports: string[];
}

export interface FirewallPolicyWithRules_PredefinedRules_Match_SrcSecureTag {
  name: string;
  state: string;
}

export interface FirewallPolicyWithRules_PredefinedRules_Match {
  destAddressGroups: string[];
  destFqdns: string[];
  destIpRanges: string[];
  destRegionCodes: string[];
  destThreatIntelligences: string[];
  layer4Config: FirewallPolicyWithRules_PredefinedRules_Match_Layer4Config[];
  srcAddressGroups: string[];
  srcFqdns: string[];
  srcIpRanges: string[];
  srcRegionCodes: string[];
  srcSecureTag: FirewallPolicyWithRules_PredefinedRules_Match_SrcSecureTag[];
  srcThreatIntelligences: string[];
}

export interface FirewallPolicyWithRules_PredefinedRules {
  action: string;
  description: string;
  direction: string;
  disabled: boolean;
  enableLogging: boolean;
  match: FirewallPolicyWithRules_PredefinedRules_Match[];
  priority: number;
  ruleName: string;
  securityProfileGroup: string;
  targetResources: string[];
  targetSecureTag: FirewallPolicyWithRules_PredefinedRules_Match_SrcSecureTag[];
  targetServiceAccounts: string[];
  tlsInspect: boolean;
}

export interface FirewallPolicyWithRules_Rule_Match {
  destAddressGroups: string[];
  destFqdns: string[];
  destIpRanges: string[];
  destRegionCodes: string[];
  destThreatIntelligences: string[];
  srcAddressGroups: string[];
  srcFqdns: string[];
  srcIpRanges: string[];
  srcRegionCodes: string[];
  srcThreatIntelligences: string[];
  layer4Config: FirewallPolicyWithRules_PredefinedRules_Match_Layer4Config[];
  srcSecureTag: FirewallPolicyWithRules_PredefinedRules_Match_SrcSecureTag[];
}

export interface FirewallPolicyWithRules_Rule {
  action: string;
  description: string;
  direction: string;
  disabled: boolean;
  enableLogging: boolean;
  priority: number;
  ruleName: string;
  securityProfileGroup: string;
  targetResources: string[];
  targetServiceAccounts: string[];
  tlsInspect: boolean;
  match: FirewallPolicyWithRules_Rule_Match[];
  targetSecureTag: FirewallPolicyWithRules_PredefinedRules_Match_SrcSecureTag[];
}

export interface FirewallPolicyWithRules_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const FirewallPolicyWithRules_PredefinedRules_Match_Layer4ConfigFields: FieldMap = {
  ipProtocol: "ip_protocol",
  ports: "ports",
};

const FirewallPolicyWithRules_PredefinedRules_Match_SrcSecureTagFields: FieldMap = {
  name: "name",
  state: "state",
};

const FirewallPolicyWithRules_Rule_MatchFields: FieldMap = {
  destAddressGroups: "dest_address_groups",
  destFqdns: "dest_fqdns",
  destIpRanges: "dest_ip_ranges",
  destRegionCodes: "dest_region_codes",
  destThreatIntelligences: "dest_threat_intelligences",
  srcAddressGroups: "src_address_groups",
  srcFqdns: "src_fqdns",
  srcIpRanges: "src_ip_ranges",
  srcRegionCodes: "src_region_codes",
  srcThreatIntelligences: "src_threat_intelligences",
  layer4Config: {
    wireName: "layer4_config",
    kind: "list",
    fields: FirewallPolicyWithRules_PredefinedRules_Match_Layer4ConfigFields,
  },
  srcSecureTag: {
    wireName: "src_secure_tag",
    kind: "list",
    fields: FirewallPolicyWithRules_PredefinedRules_Match_SrcSecureTagFields,
  },
};

const FirewallPolicyWithRules_RuleFields: FieldMap = {
  action: "action",
  description: "description",
  direction: "direction",
  disabled: "disabled",
  enableLogging: "enable_logging",
  priority: "priority",
  ruleName: "rule_name",
  securityProfileGroup: "security_profile_group",
  targetResources: "target_resources",
  targetServiceAccounts: "target_service_accounts",
  tlsInspect: "tls_inspect",
  match: {
    wireName: "match",
    kind: "list",
    fields: FirewallPolicyWithRules_Rule_MatchFields,
  },
  targetSecureTag: {
    wireName: "target_secure_tag",
    kind: "list",
    fields: FirewallPolicyWithRules_PredefinedRules_Match_SrcSecureTagFields,
  },
};

const FirewallPolicyWithRules_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface FirewallPolicyWithRulesConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  parent: string | Computed<string>;
  shortName: string | Computed<string>;
  rule?: FirewallPolicyWithRules_Rule[] | Computed<FirewallPolicyWithRules_Rule[]>;
  timeouts?: FirewallPolicyWithRules_Timeouts | Computed<FirewallPolicyWithRules_Timeouts>;
}

export interface FirewallPolicyWithRulesAttrs {
  creationTimestamp: string;
  deletionPolicy: string;
  description: string;
  fingerprint: string;
  id: string;
  parent: string;
  policyId: string;
  predefinedRules: FirewallPolicyWithRules_PredefinedRules[];
  ruleTupleCount: number;
  selfLink: string;
  selfLinkWithId: string;
  shortName: string;
  rule: FirewallPolicyWithRules_Rule[];
  timeouts: FirewallPolicyWithRules_Timeouts;
}

export const FirewallPolicyWithRules: ResourceBinding<FirewallPolicyWithRulesConfig, FirewallPolicyWithRulesAttrs> = {
  wireType: "google_compute_firewall_policy_with_rules",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    parent: "parent",
    shortName: "short_name",
    rule: {
      wireName: "rule",
      kind: "list",
      fields: FirewallPolicyWithRules_RuleFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FirewallPolicyWithRules_TimeoutsFields,
    },
  },
};
