// Code generated by `ubx sdk gen` from google_compute_firewall_policy_rule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FirewallPolicyRule_Match_Layer4Configs {
  ipProtocol: string;
  ports: string[];
}

export interface FirewallPolicyRule_Match_SrcSecureTags {
  name: string;
  state: string;
}

export interface FirewallPolicyRule_Match {
  destAddressGroups: string[];
  destFqdns: string[];
  destIpRanges: string[];
  destNetworkContext: string;
  destRegionCodes: string[];
  destThreatIntelligences: string[];
  srcAddressGroups: string[];
  srcFqdns: string[];
  srcIpRanges: string[];
  srcNetworkContext: string;
  srcNetworks: string[];
  srcRegionCodes: string[];
  srcThreatIntelligences: string[];
  layer4Configs: FirewallPolicyRule_Match_Layer4Configs[];
  srcSecureTags: FirewallPolicyRule_Match_SrcSecureTags[];
}

export interface FirewallPolicyRule_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const FirewallPolicyRule_Match_Layer4ConfigsFields: FieldMap = {
  ipProtocol: "ip_protocol",
  ports: "ports",
};

const FirewallPolicyRule_Match_SrcSecureTagsFields: FieldMap = {
  name: "name",
  state: "state",
};

const FirewallPolicyRule_MatchFields: FieldMap = {
  destAddressGroups: "dest_address_groups",
  destFqdns: "dest_fqdns",
  destIpRanges: "dest_ip_ranges",
  destNetworkContext: "dest_network_context",
  destRegionCodes: "dest_region_codes",
  destThreatIntelligences: "dest_threat_intelligences",
  srcAddressGroups: "src_address_groups",
  srcFqdns: "src_fqdns",
  srcIpRanges: "src_ip_ranges",
  srcNetworkContext: "src_network_context",
  srcNetworks: "src_networks",
  srcRegionCodes: "src_region_codes",
  srcThreatIntelligences: "src_threat_intelligences",
  layer4Configs: {
    wireName: "layer4_configs",
    kind: "list",
    fields: FirewallPolicyRule_Match_Layer4ConfigsFields,
  },
  srcSecureTags: {
    wireName: "src_secure_tags",
    kind: "list",
    fields: FirewallPolicyRule_Match_SrcSecureTagsFields,
  },
};

const FirewallPolicyRule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface FirewallPolicyRuleConfig {
  action: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  direction: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  enableLogging?: boolean | Computed<boolean>;
  firewallPolicy: string | Computed<string>;
  id?: string | Computed<string>;
  priority: number | Computed<number>;
  securityProfileGroup?: string | Computed<string>;
  targetResources?: string[] | Computed<string[]>;
  targetServiceAccounts?: string[] | Computed<string[]>;
  tlsInspect?: boolean | Computed<boolean>;
  match?: FirewallPolicyRule_Match[] | Computed<FirewallPolicyRule_Match[]>;
  targetSecureTags?: FirewallPolicyRule_Match_SrcSecureTags[] | Computed<FirewallPolicyRule_Match_SrcSecureTags[]>;
  timeouts?: FirewallPolicyRule_Timeouts | Computed<FirewallPolicyRule_Timeouts>;
}

export interface FirewallPolicyRuleAttrs {
  action: string;
  creationTimestamp: string;
  deletionPolicy: string;
  description: string;
  direction: string;
  disabled: boolean;
  enableLogging: boolean;
  firewallPolicy: string;
  id: string;
  kind: string;
  priority: number;
  ruleTupleCount: number;
  securityProfileGroup: string;
  targetResources: string[];
  targetServiceAccounts: string[];
  tlsInspect: boolean;
  match: FirewallPolicyRule_Match[];
  targetSecureTags: FirewallPolicyRule_Match_SrcSecureTags[];
  timeouts: FirewallPolicyRule_Timeouts;
}

export const FirewallPolicyRule: ResourceBinding<FirewallPolicyRuleConfig, FirewallPolicyRuleAttrs> = {
  wireType: "google_compute_firewall_policy_rule",
  fields: {
    action: "action",
    deletionPolicy: "deletion_policy",
    description: "description",
    direction: "direction",
    disabled: "disabled",
    enableLogging: "enable_logging",
    firewallPolicy: "firewall_policy",
    id: "id",
    priority: "priority",
    securityProfileGroup: "security_profile_group",
    targetResources: "target_resources",
    targetServiceAccounts: "target_service_accounts",
    tlsInspect: "tls_inspect",
    match: {
      wireName: "match",
      kind: "list",
      fields: FirewallPolicyRule_MatchFields,
    },
    targetSecureTags: {
      wireName: "target_secure_tags",
      kind: "list",
      fields: FirewallPolicyRule_Match_SrcSecureTagsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FirewallPolicyRule_TimeoutsFields,
    },
  },
};
