// Code generated by `ubx sdk gen` from google_compute_global_address. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface GlobalAddress_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const GlobalAddress_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface GlobalAddressConfig {
  address?: string | Computed<string>;
  addressType?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  ipVersion?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  name: string | Computed<string>;
  network?: string | Computed<string>;
  prefixLength?: number | Computed<number>;
  project?: string | Computed<string>;
  purpose?: string | Computed<string>;
  timeouts?: GlobalAddress_Timeouts | Computed<GlobalAddress_Timeouts>;
}

export interface GlobalAddressAttrs {
  address: string;
  addressType: string;
  creationTimestamp: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  id: string;
  ipVersion: string;
  labelFingerprint: string;
  labels: Record<string, string>;
  name: string;
  network: string;
  prefixLength: number;
  project: string;
  purpose: string;
  selfLink: string;
  terraformLabels: Record<string, string>;
  timeouts: GlobalAddress_Timeouts;
}

export const GlobalAddress: ResourceBinding<GlobalAddressConfig, GlobalAddressAttrs> = {
  wireType: "google_compute_global_address",
  fields: {
    address: "address",
    addressType: "address_type",
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    ipVersion: "ip_version",
    labels: "labels",
    name: "name",
    network: "network",
    prefixLength: "prefix_length",
    project: "project",
    purpose: "purpose",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: GlobalAddress_TimeoutsFields,
    },
  },
};
