// Code generated by `ubx sdk gen` from google_compute_instance_template_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface InstanceTemplateIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const InstanceTemplateIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface InstanceTemplateIamBindingConfig {
  id?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  condition?: InstanceTemplateIamBinding_Condition[] | Computed<InstanceTemplateIamBinding_Condition[]>;
}

export interface InstanceTemplateIamBindingAttrs {
  etag: string;
  id: string;
  members: string[];
  name: string;
  project: string;
  role: string;
  condition: InstanceTemplateIamBinding_Condition[];
}

export const InstanceTemplateIamBinding: ResourceBinding<InstanceTemplateIamBindingConfig, InstanceTemplateIamBindingAttrs> = {
  wireType: "google_compute_instance_template_iam_binding",
  fields: {
    id: "id",
    members: "members",
    name: "name",
    project: "project",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: InstanceTemplateIamBinding_ConditionFields,
    },
  },
};
