// Code generated by `ubx sdk gen` from google_compute_managed_ssl_certificate. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagedSslCertificate_Managed {
  domains: string[];
}

export interface ManagedSslCertificate_Timeouts {
  create: string;
  delete: string;
}

const ManagedSslCertificate_ManagedFields: FieldMap = {
  domains: "domains",
};

const ManagedSslCertificate_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
};

export interface ManagedSslCertificateConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  project?: string | Computed<string>;
  type?: string | Computed<string>;
  managed?: ManagedSslCertificate_Managed[] | Computed<ManagedSslCertificate_Managed[]>;
  timeouts?: ManagedSslCertificate_Timeouts | Computed<ManagedSslCertificate_Timeouts>;
}

export interface ManagedSslCertificateAttrs {
  certificateId: number;
  creationTimestamp: string;
  deletionPolicy: string;
  description: string;
  expireTime: string;
  id: string;
  name: string;
  project: string;
  selfLink: string;
  subjectAlternativeNames: string[];
  type: string;
  managed: ManagedSslCertificate_Managed[];
  timeouts: ManagedSslCertificate_Timeouts;
}

export const ManagedSslCertificate: ResourceBinding<ManagedSslCertificateConfig, ManagedSslCertificateAttrs> = {
  wireType: "google_compute_managed_ssl_certificate",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    name: "name",
    project: "project",
    type: "type",
    managed: {
      wireName: "managed",
      kind: "list",
      fields: ManagedSslCertificate_ManagedFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagedSslCertificate_TimeoutsFields,
    },
  },
};
