// Code generated by `ubx sdk gen` from google_compute_network. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Network_Params {
  resourceManagerTags: Record<string, string>;
}

export interface Network_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const Network_ParamsFields: FieldMap = {
  resourceManagerTags: "resource_manager_tags",
};

const Network_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface NetworkConfig {
  autoCreateSubnetworks?: boolean | Computed<boolean>;
  bgpAlwaysCompareMed?: boolean | Computed<boolean>;
  bgpBestPathSelectionMode?: string | Computed<string>;
  bgpInterRegionCost?: string | Computed<string>;
  deleteBgpAlwaysCompareMed?: boolean | Computed<boolean>;
  deleteDefaultRoutesOnCreate?: boolean | Computed<boolean>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  enableUlaInternalIpv6?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  internalIpv6Range?: string | Computed<string>;
  mtu?: number | Computed<number>;
  name: string | Computed<string>;
  networkFirewallPolicyEnforcementOrder?: string | Computed<string>;
  networkProfile?: string | Computed<string>;
  project?: string | Computed<string>;
  routingMode?: string | Computed<string>;
  params?: Network_Params[] | Computed<Network_Params[]>;
  timeouts?: Network_Timeouts | Computed<Network_Timeouts>;
}

export interface NetworkAttrs {
  autoCreateSubnetworks: boolean;
  bgpAlwaysCompareMed: boolean;
  bgpBestPathSelectionMode: string;
  bgpInterRegionCost: string;
  deleteBgpAlwaysCompareMed: boolean;
  deleteDefaultRoutesOnCreate: boolean;
  deletionPolicy: string;
  description: string;
  enableUlaInternalIpv6: boolean;
  gatewayIpv4: string;
  id: string;
  internalIpv6Range: string;
  mtu: number;
  name: string;
  networkFirewallPolicyEnforcementOrder: string;
  networkId: string;
  networkProfile: string;
  numericId: string;
  project: string;
  routingMode: string;
  selfLink: string;
  params: Network_Params[];
  timeouts: Network_Timeouts;
}

export const Network: ResourceBinding<NetworkConfig, NetworkAttrs> = {
  wireType: "google_compute_network",
  fields: {
    autoCreateSubnetworks: "auto_create_subnetworks",
    bgpAlwaysCompareMed: "bgp_always_compare_med",
    bgpBestPathSelectionMode: "bgp_best_path_selection_mode",
    bgpInterRegionCost: "bgp_inter_region_cost",
    deleteBgpAlwaysCompareMed: "delete_bgp_always_compare_med",
    deleteDefaultRoutesOnCreate: "delete_default_routes_on_create",
    deletionPolicy: "deletion_policy",
    description: "description",
    enableUlaInternalIpv6: "enable_ula_internal_ipv6",
    id: "id",
    internalIpv6Range: "internal_ipv6_range",
    mtu: "mtu",
    name: "name",
    networkFirewallPolicyEnforcementOrder: "network_firewall_policy_enforcement_order",
    networkProfile: "network_profile",
    project: "project",
    routingMode: "routing_mode",
    params: {
      wireName: "params",
      kind: "list",
      fields: Network_ParamsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Network_TimeoutsFields,
    },
  },
};
