// Code generated by `ubx sdk gen` from google_compute_region_disk. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RegionDisk_AsyncPrimaryDisk {
  disk: string;
}

export interface RegionDisk_DiskEncryptionKey {
  kmsKeyName: string;
  rawKey: string;
  rsaEncryptedKey: string;
  sha256: string;
}

export interface RegionDisk_GuestOsFeatures {
  type: string;
}

export interface RegionDisk_SourceImageEncryptionKey {
  kmsKeyName: string;
  kmsKeyServiceAccount: string;
  rawKey: string;
  rsaEncryptedKey: string;
  sha256: string;
}

export interface RegionDisk_SourceSnapshotEncryptionKey {
  rawKey: string;
  sha256: string;
}

export interface RegionDisk_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const RegionDisk_AsyncPrimaryDiskFields: FieldMap = {
  disk: "disk",
};

const RegionDisk_DiskEncryptionKeyFields: FieldMap = {
  kmsKeyName: "kms_key_name",
  rawKey: "raw_key",
  rsaEncryptedKey: "rsa_encrypted_key",
  sha256: "sha256",
};

const RegionDisk_GuestOsFeaturesFields: FieldMap = {
  type: "type",
};

const RegionDisk_SourceImageEncryptionKeyFields: FieldMap = {
  kmsKeyName: "kms_key_name",
  kmsKeyServiceAccount: "kms_key_service_account",
  rawKey: "raw_key",
  rsaEncryptedKey: "rsa_encrypted_key",
  sha256: "sha256",
};

const RegionDisk_SourceSnapshotEncryptionKeyFields: FieldMap = {
  rawKey: "raw_key",
  sha256: "sha256",
};

const RegionDisk_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface RegionDiskConfig {
  accessMode?: string | Computed<string>;
  createSnapshotBeforeDestroy?: boolean | Computed<boolean>;
  createSnapshotBeforeDestroyPrefix?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  image?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  licenses?: string[] | Computed<string[]>;
  name: string | Computed<string>;
  physicalBlockSizeBytes?: number | Computed<number>;
  project?: string | Computed<string>;
  provisionedIops?: number | Computed<number>;
  provisionedThroughput?: number | Computed<number>;
  region?: string | Computed<string>;
  replicaZones: string[] | Computed<string[]>;
  size?: number | Computed<number>;
  snapshot?: string | Computed<string>;
  sourceDisk?: string | Computed<string>;
  type?: string | Computed<string>;
  asyncPrimaryDisk?: RegionDisk_AsyncPrimaryDisk[] | Computed<RegionDisk_AsyncPrimaryDisk[]>;
  diskEncryptionKey?: RegionDisk_DiskEncryptionKey[] | Computed<RegionDisk_DiskEncryptionKey[]>;
  guestOsFeatures?: RegionDisk_GuestOsFeatures[] | Computed<RegionDisk_GuestOsFeatures[]>;
  sourceImageEncryptionKey?: RegionDisk_SourceImageEncryptionKey[] | Computed<RegionDisk_SourceImageEncryptionKey[]>;
  sourceSnapshotEncryptionKey?: RegionDisk_SourceSnapshotEncryptionKey[] | Computed<RegionDisk_SourceSnapshotEncryptionKey[]>;
  timeouts?: RegionDisk_Timeouts | Computed<RegionDisk_Timeouts>;
}

export interface RegionDiskAttrs {
  accessMode: string;
  createSnapshotBeforeDestroy: boolean;
  createSnapshotBeforeDestroyPrefix: string;
  creationTimestamp: string;
  deletionPolicy: string;
  description: string;
  diskId: string;
  effectiveLabels: Record<string, string>;
  id: string;
  image: string;
  labelFingerprint: string;
  labels: Record<string, string>;
  lastAttachTimestamp: string;
  lastDetachTimestamp: string;
  licenses: string[];
  name: string;
  physicalBlockSizeBytes: number;
  project: string;
  provisionedIops: number;
  provisionedThroughput: number;
  region: string;
  replicaZones: string[];
  selfLink: string;
  size: number;
  snapshot: string;
  sourceDisk: string;
  sourceDiskId: string;
  sourceImageId: string;
  sourceSnapshotId: string;
  terraformLabels: Record<string, string>;
  type: string;
  users: string[];
  asyncPrimaryDisk: RegionDisk_AsyncPrimaryDisk[];
  diskEncryptionKey: RegionDisk_DiskEncryptionKey[];
  guestOsFeatures: RegionDisk_GuestOsFeatures[];
  sourceImageEncryptionKey: RegionDisk_SourceImageEncryptionKey[];
  sourceSnapshotEncryptionKey: RegionDisk_SourceSnapshotEncryptionKey[];
  timeouts: RegionDisk_Timeouts;
}

export const RegionDisk: ResourceBinding<RegionDiskConfig, RegionDiskAttrs> = {
  wireType: "google_compute_region_disk",
  fields: {
    accessMode: "access_mode",
    createSnapshotBeforeDestroy: "create_snapshot_before_destroy",
    createSnapshotBeforeDestroyPrefix: "create_snapshot_before_destroy_prefix",
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    image: "image",
    labels: "labels",
    licenses: "licenses",
    name: "name",
    physicalBlockSizeBytes: "physical_block_size_bytes",
    project: "project",
    provisionedIops: "provisioned_iops",
    provisionedThroughput: "provisioned_throughput",
    region: "region",
    replicaZones: "replica_zones",
    size: "size",
    snapshot: "snapshot",
    sourceDisk: "source_disk",
    type: "type",
    asyncPrimaryDisk: {
      wireName: "async_primary_disk",
      kind: "list",
      fields: RegionDisk_AsyncPrimaryDiskFields,
    },
    diskEncryptionKey: {
      wireName: "disk_encryption_key",
      kind: "list",
      fields: RegionDisk_DiskEncryptionKeyFields,
    },
    guestOsFeatures: {
      wireName: "guest_os_features",
      kind: "set",
      fields: RegionDisk_GuestOsFeaturesFields,
    },
    sourceImageEncryptionKey: {
      wireName: "source_image_encryption_key",
      kind: "list",
      fields: RegionDisk_SourceImageEncryptionKeyFields,
    },
    sourceSnapshotEncryptionKey: {
      wireName: "source_snapshot_encryption_key",
      kind: "list",
      fields: RegionDisk_SourceSnapshotEncryptionKeyFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: RegionDisk_TimeoutsFields,
    },
  },
};
