// Code generated by `ubx sdk gen` from google_compute_region_network_firewall_policy_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RegionNetworkFirewallPolicyIamPolicyConfig {
  id?: string | Computed<string>;
  name: string | Computed<string>;
  policyData: string | Computed<string>;
  project?: string | Computed<string>;
  region?: string | Computed<string>;
}

export interface RegionNetworkFirewallPolicyIamPolicyAttrs {
  etag: string;
  id: string;
  name: string;
  policyData: string;
  project: string;
  region: string;
}

export const RegionNetworkFirewallPolicyIamPolicy: ResourceBinding<RegionNetworkFirewallPolicyIamPolicyConfig, RegionNetworkFirewallPolicyIamPolicyAttrs> = {
  wireType: "google_compute_region_network_firewall_policy_iam_policy",
  fields: {
    id: "id",
    name: "name",
    policyData: "policy_data",
    project: "project",
    region: "region",
  },
};
