// Code generated by `ubx sdk gen` from google_compute_region_security_policy_rule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RegionSecurityPolicyRule_Match_Config {
  srcIpRanges: string[];
}

export interface RegionSecurityPolicyRule_Match_Expr {
  expression: string;
}

export interface RegionSecurityPolicyRule_Match {
  versionedExpr: string;
  config: RegionSecurityPolicyRule_Match_Config[];
  expr: RegionSecurityPolicyRule_Match_Expr[];
}

export interface RegionSecurityPolicyRule_NetworkMatch_UserDefinedFields {
  name: string;
  values: string[];
}

export interface RegionSecurityPolicyRule_NetworkMatch {
  destIpRanges: string[];
  destPorts: string[];
  ipProtocols: string[];
  srcAsns: number[];
  srcIpRanges: string[];
  srcPorts: string[];
  srcRegionCodes: string[];
  userDefinedFields: RegionSecurityPolicyRule_NetworkMatch_UserDefinedFields[];
}

export interface RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookie {
  operator: string;
  value: string;
}

export interface RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion {
  targetRuleIds: string[];
  targetRuleSet: string;
  requestCookie: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookie[];
  requestHeader: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookie[];
  requestQueryParam: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookie[];
  requestUri: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookie[];
}

export interface RegionSecurityPolicyRule_PreconfiguredWafConfig {
  exclusion: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion[];
}

export interface RegionSecurityPolicyRule_RateLimitOptions_BanThreshold {
  count: number;
  intervalSec: number;
}

export interface RegionSecurityPolicyRule_RateLimitOptions_EnforceOnKeyConfigs {
  enforceOnKeyName: string;
  enforceOnKeyType: string;
}

export interface RegionSecurityPolicyRule_RateLimitOptions {
  banDurationSec: number;
  conformAction: string;
  enforceOnKey: string;
  enforceOnKeyName: string;
  exceedAction: string;
  banThreshold: RegionSecurityPolicyRule_RateLimitOptions_BanThreshold[];
  enforceOnKeyConfigs: RegionSecurityPolicyRule_RateLimitOptions_EnforceOnKeyConfigs[];
  rateLimitThreshold: RegionSecurityPolicyRule_RateLimitOptions_BanThreshold[];
}

export interface RegionSecurityPolicyRule_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const RegionSecurityPolicyRule_Match_ConfigFields: FieldMap = {
  srcIpRanges: "src_ip_ranges",
};

const RegionSecurityPolicyRule_Match_ExprFields: FieldMap = {
  expression: "expression",
};

const RegionSecurityPolicyRule_MatchFields: FieldMap = {
  versionedExpr: "versioned_expr",
  config: {
    wireName: "config",
    kind: "list",
    fields: RegionSecurityPolicyRule_Match_ConfigFields,
  },
  expr: {
    wireName: "expr",
    kind: "list",
    fields: RegionSecurityPolicyRule_Match_ExprFields,
  },
};

const RegionSecurityPolicyRule_NetworkMatch_UserDefinedFieldsFields: FieldMap = {
  name: "name",
  values: "values",
};

const RegionSecurityPolicyRule_NetworkMatchFields: FieldMap = {
  destIpRanges: "dest_ip_ranges",
  destPorts: "dest_ports",
  ipProtocols: "ip_protocols",
  srcAsns: "src_asns",
  srcIpRanges: "src_ip_ranges",
  srcPorts: "src_ports",
  srcRegionCodes: "src_region_codes",
  userDefinedFields: {
    wireName: "user_defined_fields",
    kind: "list",
    fields: RegionSecurityPolicyRule_NetworkMatch_UserDefinedFieldsFields,
  },
};

const RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookieFields: FieldMap = {
  operator: "operator",
  value: "value",
};

const RegionSecurityPolicyRule_PreconfiguredWafConfig_ExclusionFields: FieldMap = {
  targetRuleIds: "target_rule_ids",
  targetRuleSet: "target_rule_set",
  requestCookie: {
    wireName: "request_cookie",
    kind: "list",
    fields: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookieFields,
  },
  requestHeader: {
    wireName: "request_header",
    kind: "list",
    fields: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookieFields,
  },
  requestQueryParam: {
    wireName: "request_query_param",
    kind: "list",
    fields: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookieFields,
  },
  requestUri: {
    wireName: "request_uri",
    kind: "list",
    fields: RegionSecurityPolicyRule_PreconfiguredWafConfig_Exclusion_RequestCookieFields,
  },
};

const RegionSecurityPolicyRule_PreconfiguredWafConfigFields: FieldMap = {
  exclusion: {
    wireName: "exclusion",
    kind: "list",
    fields: RegionSecurityPolicyRule_PreconfiguredWafConfig_ExclusionFields,
  },
};

const RegionSecurityPolicyRule_RateLimitOptions_BanThresholdFields: FieldMap = {
  count: "count",
  intervalSec: "interval_sec",
};

const RegionSecurityPolicyRule_RateLimitOptions_EnforceOnKeyConfigsFields: FieldMap = {
  enforceOnKeyName: "enforce_on_key_name",
  enforceOnKeyType: "enforce_on_key_type",
};

const RegionSecurityPolicyRule_RateLimitOptionsFields: FieldMap = {
  banDurationSec: "ban_duration_sec",
  conformAction: "conform_action",
  enforceOnKey: "enforce_on_key",
  enforceOnKeyName: "enforce_on_key_name",
  exceedAction: "exceed_action",
  banThreshold: {
    wireName: "ban_threshold",
    kind: "list",
    fields: RegionSecurityPolicyRule_RateLimitOptions_BanThresholdFields,
  },
  enforceOnKeyConfigs: {
    wireName: "enforce_on_key_configs",
    kind: "list",
    fields: RegionSecurityPolicyRule_RateLimitOptions_EnforceOnKeyConfigsFields,
  },
  rateLimitThreshold: {
    wireName: "rate_limit_threshold",
    kind: "list",
    fields: RegionSecurityPolicyRule_RateLimitOptions_BanThresholdFields,
  },
};

const RegionSecurityPolicyRule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface RegionSecurityPolicyRuleConfig {
  action: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  preview?: boolean | Computed<boolean>;
  priority: number | Computed<number>;
  project?: string | Computed<string>;
  region: string | Computed<string>;
  securityPolicy: string | Computed<string>;
  match?: RegionSecurityPolicyRule_Match[] | Computed<RegionSecurityPolicyRule_Match[]>;
  networkMatch?: RegionSecurityPolicyRule_NetworkMatch[] | Computed<RegionSecurityPolicyRule_NetworkMatch[]>;
  preconfiguredWafConfig?: RegionSecurityPolicyRule_PreconfiguredWafConfig[] | Computed<RegionSecurityPolicyRule_PreconfiguredWafConfig[]>;
  rateLimitOptions?: RegionSecurityPolicyRule_RateLimitOptions[] | Computed<RegionSecurityPolicyRule_RateLimitOptions[]>;
  timeouts?: RegionSecurityPolicyRule_Timeouts | Computed<RegionSecurityPolicyRule_Timeouts>;
}

export interface RegionSecurityPolicyRuleAttrs {
  action: string;
  deletionPolicy: string;
  description: string;
  id: string;
  preview: boolean;
  priority: number;
  project: string;
  region: string;
  securityPolicy: string;
  match: RegionSecurityPolicyRule_Match[];
  networkMatch: RegionSecurityPolicyRule_NetworkMatch[];
  preconfiguredWafConfig: RegionSecurityPolicyRule_PreconfiguredWafConfig[];
  rateLimitOptions: RegionSecurityPolicyRule_RateLimitOptions[];
  timeouts: RegionSecurityPolicyRule_Timeouts;
}

export const RegionSecurityPolicyRule: ResourceBinding<RegionSecurityPolicyRuleConfig, RegionSecurityPolicyRuleAttrs> = {
  wireType: "google_compute_region_security_policy_rule",
  fields: {
    action: "action",
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    preview: "preview",
    priority: "priority",
    project: "project",
    region: "region",
    securityPolicy: "security_policy",
    match: {
      wireName: "match",
      kind: "list",
      fields: RegionSecurityPolicyRule_MatchFields,
    },
    networkMatch: {
      wireName: "network_match",
      kind: "list",
      fields: RegionSecurityPolicyRule_NetworkMatchFields,
    },
    preconfiguredWafConfig: {
      wireName: "preconfigured_waf_config",
      kind: "list",
      fields: RegionSecurityPolicyRule_PreconfiguredWafConfigFields,
    },
    rateLimitOptions: {
      wireName: "rate_limit_options",
      kind: "list",
      fields: RegionSecurityPolicyRule_RateLimitOptionsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: RegionSecurityPolicyRule_TimeoutsFields,
    },
  },
};
