// Code generated by `ubx sdk gen` from google_compute_route. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Route_AsPaths {
  asLists: number[];
  pathSegmentType: string;
}

export interface Route_Warnings_Data {
  key: string;
  value: string;
}

export interface Route_Warnings {
  code: string;
  data: Route_Warnings_Data[];
  message: string;
}

export interface Route_Params {
  resourceManagerTags: Record<string, string>;
}

export interface Route_Timeouts {
  create: string;
  delete: string;
}

const Route_ParamsFields: FieldMap = {
  resourceManagerTags: "resource_manager_tags",
};

const Route_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
};

export interface RouteConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  destRange: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  network: string | Computed<string>;
  nextHopGateway?: string | Computed<string>;
  nextHopIlb?: string | Computed<string>;
  nextHopInstance?: string | Computed<string>;
  nextHopInstanceZone?: string | Computed<string>;
  nextHopIp?: string | Computed<string>;
  nextHopVpnTunnel?: string | Computed<string>;
  priority?: number | Computed<number>;
  project?: string | Computed<string>;
  tags?: string[] | Computed<string[]>;
  params?: Route_Params[] | Computed<Route_Params[]>;
  timeouts?: Route_Timeouts | Computed<Route_Timeouts>;
}

export interface RouteAttrs {
  asPaths: Route_AsPaths[];
  creationTimestamp: string;
  deletionPolicy: string;
  description: string;
  destRange: string;
  id: string;
  name: string;
  network: string;
  nextHopGateway: string;
  nextHopHub: string;
  nextHopIlb: string;
  nextHopInstance: string;
  nextHopInstanceZone: string;
  nextHopInterRegionCost: string;
  nextHopIp: string;
  nextHopMed: string;
  nextHopNetwork: string;
  nextHopOrigin: string;
  nextHopPeering: string;
  nextHopVpnTunnel: string;
  priority: number;
  project: string;
  routeStatus: string;
  routeType: string;
  selfLink: string;
  tags: string[];
  warnings: Route_Warnings[];
  params: Route_Params[];
  timeouts: Route_Timeouts;
}

export const Route: ResourceBinding<RouteConfig, RouteAttrs> = {
  wireType: "google_compute_route",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    destRange: "dest_range",
    id: "id",
    name: "name",
    network: "network",
    nextHopGateway: "next_hop_gateway",
    nextHopIlb: "next_hop_ilb",
    nextHopInstance: "next_hop_instance",
    nextHopInstanceZone: "next_hop_instance_zone",
    nextHopIp: "next_hop_ip",
    nextHopVpnTunnel: "next_hop_vpn_tunnel",
    priority: "priority",
    project: "project",
    tags: "tags",
    params: {
      wireName: "params",
      kind: "list",
      fields: Route_ParamsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Route_TimeoutsFields,
    },
  },
};
