// Code generated by `ubx sdk gen` from google_compute_shared_vpc_service_project. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SharedVpcServiceProject_Timeouts {
  create: string;
  delete: string;
}

const SharedVpcServiceProject_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
};

export interface SharedVpcServiceProjectConfig {
  deletionPolicy?: string | Computed<string>;
  hostProject: string | Computed<string>;
  id?: string | Computed<string>;
  serviceProject: string | Computed<string>;
  timeouts?: SharedVpcServiceProject_Timeouts | Computed<SharedVpcServiceProject_Timeouts>;
}

export interface SharedVpcServiceProjectAttrs {
  deletionPolicy: string;
  hostProject: string;
  id: string;
  serviceProject: string;
  timeouts: SharedVpcServiceProject_Timeouts;
}

export const SharedVpcServiceProject: ResourceBinding<SharedVpcServiceProjectConfig, SharedVpcServiceProjectAttrs> = {
  wireType: "google_compute_shared_vpc_service_project",
  fields: {
    deletionPolicy: "deletion_policy",
    hostProject: "host_project",
    id: "id",
    serviceProject: "service_project",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SharedVpcServiceProject_TimeoutsFields,
    },
  },
};
