// Code generated by `ubx sdk gen` from google_compute_snapshot_settings. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SnapshotSettings_StorageLocation_Locations {
  location: string;
  name: string;
}

export interface SnapshotSettings_StorageLocation {
  policy: string;
  locations: SnapshotSettings_StorageLocation_Locations[];
}

export interface SnapshotSettings_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const SnapshotSettings_StorageLocation_LocationsFields: FieldMap = {
  location: "location",
  name: "name",
};

const SnapshotSettings_StorageLocationFields: FieldMap = {
  policy: "policy",
  locations: {
    wireName: "locations",
    kind: "set",
    fields: SnapshotSettings_StorageLocation_LocationsFields,
  },
};

const SnapshotSettings_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SnapshotSettingsConfig {
  id?: string | Computed<string>;
  project?: string | Computed<string>;
  storageLocation?: SnapshotSettings_StorageLocation[] | Computed<SnapshotSettings_StorageLocation[]>;
  timeouts?: SnapshotSettings_Timeouts | Computed<SnapshotSettings_Timeouts>;
}

export interface SnapshotSettingsAttrs {
  id: string;
  project: string;
  storageLocation: SnapshotSettings_StorageLocation[];
  timeouts: SnapshotSettings_Timeouts;
}

export const SnapshotSettings: ResourceBinding<SnapshotSettingsConfig, SnapshotSettingsAttrs> = {
  wireType: "google_compute_snapshot_settings",
  fields: {
    id: "id",
    project: "project",
    storageLocation: {
      wireName: "storage_location",
      kind: "list",
      fields: SnapshotSettings_StorageLocationFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SnapshotSettings_TimeoutsFields,
    },
  },
};
