// Code generated by `ubx sdk gen` from google_developer_connect_connection. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ConnectConnection_InstallationState {
  actionUri: string;
  message: string;
  stage: string;
}

export interface ConnectConnection_BitbucketCloudConfig_AuthorizerCredential {
  userTokenSecretVersion: string;
  username: string;
}

export interface ConnectConnection_BitbucketCloudConfig {
  webhookSecretSecretVersion: string;
  workspace: string;
  authorizerCredential: ConnectConnection_BitbucketCloudConfig_AuthorizerCredential[];
  readAuthorizerCredential: ConnectConnection_BitbucketCloudConfig_AuthorizerCredential[];
}

export interface ConnectConnection_BitbucketDataCenterConfig_ServiceDirectoryConfig {
  service: string;
}

export interface ConnectConnection_BitbucketDataCenterConfig {
  hostUri: string;
  serverVersion: string;
  sslCaCertificate: string;
  webhookSecretSecretVersion: string;
  authorizerCredential: ConnectConnection_BitbucketCloudConfig_AuthorizerCredential[];
  readAuthorizerCredential: ConnectConnection_BitbucketCloudConfig_AuthorizerCredential[];
  serviceDirectoryConfig: ConnectConnection_BitbucketDataCenterConfig_ServiceDirectoryConfig[];
}

export interface ConnectConnection_CryptoKeyConfig {
  keyReference: string;
}

export interface ConnectConnection_GithubConfig_AuthorizerCredential {
  oauthTokenSecretVersion: string;
  username: string;
}

export interface ConnectConnection_GithubConfig {
  appInstallationId: string;
  githubApp: string;
  installationUri: string;
  authorizerCredential: ConnectConnection_GithubConfig_AuthorizerCredential[];
}

export interface ConnectConnection_GithubEnterpriseConfig {
  appId: string;
  appInstallationId: string;
  appSlug: string;
  hostUri: string;
  installationUri: string;
  privateKeySecretVersion: string;
  serverVersion: string;
  sslCaCertificate: string;
  webhookSecretSecretVersion: string;
  serviceDirectoryConfig: ConnectConnection_BitbucketDataCenterConfig_ServiceDirectoryConfig[];
}

export interface ConnectConnection_GitlabConfig {
  webhookSecretSecretVersion: string;
  authorizerCredential: ConnectConnection_BitbucketCloudConfig_AuthorizerCredential[];
  readAuthorizerCredential: ConnectConnection_BitbucketCloudConfig_AuthorizerCredential[];
}

export interface ConnectConnection_HttpConfig_BasicAuthentication {
  passwordSecretVersion: string;
  username: string;
}

export interface ConnectConnection_HttpConfig_BearerTokenAuthentication {
  tokenSecretVersion: string;
}

export interface ConnectConnection_HttpConfig {
  hostUri: string;
  sslCaCertificate: string;
  basicAuthentication: ConnectConnection_HttpConfig_BasicAuthentication[];
  bearerTokenAuthentication: ConnectConnection_HttpConfig_BearerTokenAuthentication[];
  serviceDirectoryConfig: ConnectConnection_BitbucketDataCenterConfig_ServiceDirectoryConfig[];
}

export interface ConnectConnection_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ConnectConnection_BitbucketCloudConfig_AuthorizerCredentialFields: FieldMap = {
  userTokenSecretVersion: "user_token_secret_version",
  username: "username",
};

const ConnectConnection_BitbucketCloudConfigFields: FieldMap = {
  webhookSecretSecretVersion: "webhook_secret_secret_version",
  workspace: "workspace",
  authorizerCredential: {
    wireName: "authorizer_credential",
    kind: "list",
    fields: ConnectConnection_BitbucketCloudConfig_AuthorizerCredentialFields,
  },
  readAuthorizerCredential: {
    wireName: "read_authorizer_credential",
    kind: "list",
    fields: ConnectConnection_BitbucketCloudConfig_AuthorizerCredentialFields,
  },
};

const ConnectConnection_BitbucketDataCenterConfig_ServiceDirectoryConfigFields: FieldMap = {
  service: "service",
};

const ConnectConnection_BitbucketDataCenterConfigFields: FieldMap = {
  hostUri: "host_uri",
  serverVersion: "server_version",
  sslCaCertificate: "ssl_ca_certificate",
  webhookSecretSecretVersion: "webhook_secret_secret_version",
  authorizerCredential: {
    wireName: "authorizer_credential",
    kind: "list",
    fields: ConnectConnection_BitbucketCloudConfig_AuthorizerCredentialFields,
  },
  readAuthorizerCredential: {
    wireName: "read_authorizer_credential",
    kind: "list",
    fields: ConnectConnection_BitbucketCloudConfig_AuthorizerCredentialFields,
  },
  serviceDirectoryConfig: {
    wireName: "service_directory_config",
    kind: "list",
    fields: ConnectConnection_BitbucketDataCenterConfig_ServiceDirectoryConfigFields,
  },
};

const ConnectConnection_CryptoKeyConfigFields: FieldMap = {
  keyReference: "key_reference",
};

const ConnectConnection_GithubConfig_AuthorizerCredentialFields: FieldMap = {
  oauthTokenSecretVersion: "oauth_token_secret_version",
  username: "username",
};

const ConnectConnection_GithubConfigFields: FieldMap = {
  appInstallationId: "app_installation_id",
  githubApp: "github_app",
  installationUri: "installation_uri",
  authorizerCredential: {
    wireName: "authorizer_credential",
    kind: "list",
    fields: ConnectConnection_GithubConfig_AuthorizerCredentialFields,
  },
};

const ConnectConnection_GithubEnterpriseConfigFields: FieldMap = {
  appId: "app_id",
  appInstallationId: "app_installation_id",
  appSlug: "app_slug",
  hostUri: "host_uri",
  installationUri: "installation_uri",
  privateKeySecretVersion: "private_key_secret_version",
  serverVersion: "server_version",
  sslCaCertificate: "ssl_ca_certificate",
  webhookSecretSecretVersion: "webhook_secret_secret_version",
  serviceDirectoryConfig: {
    wireName: "service_directory_config",
    kind: "list",
    fields: ConnectConnection_BitbucketDataCenterConfig_ServiceDirectoryConfigFields,
  },
};

const ConnectConnection_GitlabConfigFields: FieldMap = {
  webhookSecretSecretVersion: "webhook_secret_secret_version",
  authorizerCredential: {
    wireName: "authorizer_credential",
    kind: "list",
    fields: ConnectConnection_BitbucketCloudConfig_AuthorizerCredentialFields,
  },
  readAuthorizerCredential: {
    wireName: "read_authorizer_credential",
    kind: "list",
    fields: ConnectConnection_BitbucketCloudConfig_AuthorizerCredentialFields,
  },
};

const ConnectConnection_HttpConfig_BasicAuthenticationFields: FieldMap = {
  passwordSecretVersion: "password_secret_version",
  username: "username",
};

const ConnectConnection_HttpConfig_BearerTokenAuthenticationFields: FieldMap = {
  tokenSecretVersion: "token_secret_version",
};

const ConnectConnection_HttpConfigFields: FieldMap = {
  hostUri: "host_uri",
  sslCaCertificate: "ssl_ca_certificate",
  basicAuthentication: {
    wireName: "basic_authentication",
    kind: "list",
    fields: ConnectConnection_HttpConfig_BasicAuthenticationFields,
  },
  bearerTokenAuthentication: {
    wireName: "bearer_token_authentication",
    kind: "list",
    fields: ConnectConnection_HttpConfig_BearerTokenAuthenticationFields,
  },
  serviceDirectoryConfig: {
    wireName: "service_directory_config",
    kind: "list",
    fields: ConnectConnection_BitbucketDataCenterConfig_ServiceDirectoryConfigFields,
  },
};

const ConnectConnection_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ConnectConnectionConfig {
  annotations?: Record<string, string> | Computed<Record<string, string>>;
  connectionId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  etag?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  bitbucketCloudConfig?: ConnectConnection_BitbucketCloudConfig[] | Computed<ConnectConnection_BitbucketCloudConfig[]>;
  bitbucketDataCenterConfig?: ConnectConnection_BitbucketDataCenterConfig[] | Computed<ConnectConnection_BitbucketDataCenterConfig[]>;
  cryptoKeyConfig?: ConnectConnection_CryptoKeyConfig[] | Computed<ConnectConnection_CryptoKeyConfig[]>;
  githubConfig?: ConnectConnection_GithubConfig[] | Computed<ConnectConnection_GithubConfig[]>;
  githubEnterpriseConfig?: ConnectConnection_GithubEnterpriseConfig[] | Computed<ConnectConnection_GithubEnterpriseConfig[]>;
  gitlabConfig?: ConnectConnection_GitlabConfig[] | Computed<ConnectConnection_GitlabConfig[]>;
  gitlabEnterpriseConfig?: ConnectConnection_BitbucketDataCenterConfig[] | Computed<ConnectConnection_BitbucketDataCenterConfig[]>;
  httpConfig?: ConnectConnection_HttpConfig[] | Computed<ConnectConnection_HttpConfig[]>;
  timeouts?: ConnectConnection_Timeouts | Computed<ConnectConnection_Timeouts>;
}

export interface ConnectConnectionAttrs {
  annotations: Record<string, string>;
  connectionId: string;
  createTime: string;
  deleteTime: string;
  deletionPolicy: string;
  disabled: boolean;
  effectiveAnnotations: Record<string, string>;
  effectiveLabels: Record<string, string>;
  etag: string;
  id: string;
  installationState: ConnectConnection_InstallationState[];
  labels: Record<string, string>;
  location: string;
  name: string;
  project: string;
  reconciling: boolean;
  terraformLabels: Record<string, string>;
  uid: string;
  updateTime: string;
  bitbucketCloudConfig: ConnectConnection_BitbucketCloudConfig[];
  bitbucketDataCenterConfig: ConnectConnection_BitbucketDataCenterConfig[];
  cryptoKeyConfig: ConnectConnection_CryptoKeyConfig[];
  githubConfig: ConnectConnection_GithubConfig[];
  githubEnterpriseConfig: ConnectConnection_GithubEnterpriseConfig[];
  gitlabConfig: ConnectConnection_GitlabConfig[];
  gitlabEnterpriseConfig: ConnectConnection_BitbucketDataCenterConfig[];
  httpConfig: ConnectConnection_HttpConfig[];
  timeouts: ConnectConnection_Timeouts;
}

export const ConnectConnection: ResourceBinding<ConnectConnectionConfig, ConnectConnectionAttrs> = {
  wireType: "google_developer_connect_connection",
  fields: {
    annotations: "annotations",
    connectionId: "connection_id",
    deletionPolicy: "deletion_policy",
    disabled: "disabled",
    etag: "etag",
    id: "id",
    labels: "labels",
    location: "location",
    project: "project",
    bitbucketCloudConfig: {
      wireName: "bitbucket_cloud_config",
      kind: "list",
      fields: ConnectConnection_BitbucketCloudConfigFields,
    },
    bitbucketDataCenterConfig: {
      wireName: "bitbucket_data_center_config",
      kind: "list",
      fields: ConnectConnection_BitbucketDataCenterConfigFields,
    },
    cryptoKeyConfig: {
      wireName: "crypto_key_config",
      kind: "list",
      fields: ConnectConnection_CryptoKeyConfigFields,
    },
    githubConfig: {
      wireName: "github_config",
      kind: "list",
      fields: ConnectConnection_GithubConfigFields,
    },
    githubEnterpriseConfig: {
      wireName: "github_enterprise_config",
      kind: "list",
      fields: ConnectConnection_GithubEnterpriseConfigFields,
    },
    gitlabConfig: {
      wireName: "gitlab_config",
      kind: "list",
      fields: ConnectConnection_GitlabConfigFields,
    },
    gitlabEnterpriseConfig: {
      wireName: "gitlab_enterprise_config",
      kind: "list",
      fields: ConnectConnection_BitbucketDataCenterConfigFields,
    },
    httpConfig: {
      wireName: "http_config",
      kind: "list",
      fields: ConnectConnection_HttpConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ConnectConnection_TimeoutsFields,
    },
  },
};
