// Code generated by `ubx sdk gen` from google_container_analysis_occurrence. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AnalysisOccurrence_Attestation_Signatures {
  publicKeyId: string;
  signature: string;
}

export interface AnalysisOccurrence_Attestation {
  serializedPayload: string;
  signatures: AnalysisOccurrence_Attestation_Signatures[];
}

export interface AnalysisOccurrence_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const AnalysisOccurrence_Attestation_SignaturesFields: FieldMap = {
  publicKeyId: "public_key_id",
  signature: "signature",
};

const AnalysisOccurrence_AttestationFields: FieldMap = {
  serializedPayload: "serialized_payload",
  signatures: {
    wireName: "signatures",
    kind: "set",
    fields: AnalysisOccurrence_Attestation_SignaturesFields,
  },
};

const AnalysisOccurrence_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface AnalysisOccurrenceConfig {
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  noteName: string | Computed<string>;
  project?: string | Computed<string>;
  remediation?: string | Computed<string>;
  resourceUri: string | Computed<string>;
  attestation?: AnalysisOccurrence_Attestation[] | Computed<AnalysisOccurrence_Attestation[]>;
  timeouts?: AnalysisOccurrence_Timeouts | Computed<AnalysisOccurrence_Timeouts>;
}

export interface AnalysisOccurrenceAttrs {
  createTime: string;
  deletionPolicy: string;
  id: string;
  kind: string;
  name: string;
  noteName: string;
  project: string;
  remediation: string;
  resourceUri: string;
  updateTime: string;
  attestation: AnalysisOccurrence_Attestation[];
  timeouts: AnalysisOccurrence_Timeouts;
}

export const AnalysisOccurrence: ResourceBinding<AnalysisOccurrenceConfig, AnalysisOccurrenceAttrs> = {
  wireType: "google_container_analysis_occurrence",
  fields: {
    deletionPolicy: "deletion_policy",
    id: "id",
    noteName: "note_name",
    project: "project",
    remediation: "remediation",
    resourceUri: "resource_uri",
    attestation: {
      wireName: "attestation",
      kind: "list",
      fields: AnalysisOccurrence_AttestationFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AnalysisOccurrence_TimeoutsFields,
    },
  },
};
