// Code generated by `ubx sdk gen` from google_container_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Cluster_AddonsConfig_AgentSandboxConfig {
  enabled: boolean;
}

export interface Cluster_AddonsConfig_CloudrunConfig {
  disabled: boolean;
  loadBalancerType: string;
}

export interface Cluster_AddonsConfig_HorizontalPodAutoscaling {
  disabled: boolean;
}

export interface Cluster_AddonsConfig_LustreCsiDriverConfig {
  disableMultiNic: boolean;
  enableLegacyLustrePort: boolean;
  enabled: boolean;
}

export interface Cluster_AddonsConfig_RayOperatorConfig {
  enabled: boolean;
  rayClusterLoggingConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  rayClusterMonitoringConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
}

export interface Cluster_AddonsConfig {
  agentSandboxConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  cloudrunConfig: Cluster_AddonsConfig_CloudrunConfig[];
  configConnectorConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  dnsCacheConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  gcePersistentDiskCsiDriverConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  gcpFilestoreCsiDriverConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  gcsFuseCsiDriverConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  gkeBackupAgentConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  horizontalPodAutoscaling: Cluster_AddonsConfig_HorizontalPodAutoscaling[];
  httpLoadBalancing: Cluster_AddonsConfig_HorizontalPodAutoscaling[];
  lustreCsiDriverConfig: Cluster_AddonsConfig_LustreCsiDriverConfig[];
  networkPolicyConfig: Cluster_AddonsConfig_HorizontalPodAutoscaling[];
  nodeReadinessConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  parallelstoreCsiDriverConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  podSnapshotConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  rayOperatorConfig: Cluster_AddonsConfig_RayOperatorConfig[];
  sliceControllerConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  slurmOperatorConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  statefulHaConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
}

export interface Cluster_AnonymousAuthenticationConfig {
  mode: string;
}

export interface Cluster_AuthenticatorGroupsConfig {
  securityGroup: string;
}

export interface Cluster_AutopilotClusterPolicyConfig {
  noStandardNodePools: boolean;
  noSystemImpersonation: boolean;
  noSystemMutation: boolean;
  noUnsafeWebhooks: boolean;
}

export interface Cluster_BinaryAuthorization {
  enabled: boolean;
  evaluationMode: string;
}

export interface Cluster_ClusterAutoscaling_AutoProvisioningDefaults_Management_UpgradeOptions {
  autoUpgradeStartTime: string;
  description: string;
}

export interface Cluster_ClusterAutoscaling_AutoProvisioningDefaults_Management {
  autoRepair: boolean;
  autoUpgrade: boolean;
  upgradeOptions: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_Management_UpgradeOptions[];
}

export interface Cluster_ClusterAutoscaling_AutoProvisioningDefaults_ShieldedInstanceConfig {
  enableIntegrityMonitoring: boolean;
  enableSecureBoot: boolean;
}

export interface Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings_BlueGreenSettings_StandardRolloutPolicy {
  batchNodeCount: number;
  batchPercentage: number;
  batchSoakDuration: string;
}

export interface Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings_BlueGreenSettings {
  nodePoolSoakDuration: string;
  standardRolloutPolicy: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings_BlueGreenSettings_StandardRolloutPolicy[];
}

export interface Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings {
  maxSurge: number;
  maxUnavailable: number;
  strategy: string;
  blueGreenSettings: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings_BlueGreenSettings[];
}

export interface Cluster_ClusterAutoscaling_AutoProvisioningDefaults {
  bootDiskKmsKey: string;
  diskSize: number;
  diskType: string;
  imageType: string;
  minCpuPlatform: string;
  oauthScopes: string[];
  serviceAccount: string;
  management: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_Management[];
  shieldedInstanceConfig: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_ShieldedInstanceConfig[];
  upgradeSettings: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings[];
}

export interface Cluster_ClusterAutoscaling_ResourceLimits {
  maximum: number;
  minimum: number;
  resourceType: string;
}

export interface Cluster_ClusterAutoscaling {
  autoProvisioningLocations: string[];
  autoscalingProfile: string;
  defaultComputeClassEnabled: boolean;
  enabled: boolean;
  autoProvisioningDefaults: Cluster_ClusterAutoscaling_AutoProvisioningDefaults[];
  resourceLimits: Cluster_ClusterAutoscaling_ResourceLimits[];
}

export interface Cluster_ConfidentialNodes {
  confidentialInstanceType: string;
  enabled: boolean;
}

export interface Cluster_ControlPlaneEndpointsConfig_DnsEndpointConfig {
  allowExternalTraffic: boolean;
  enableK8sCertsViaDns: boolean;
  enableK8sTokensViaDns: boolean;
  endpoint: string;
}

export interface Cluster_ControlPlaneEndpointsConfig {
  dnsEndpointConfig: Cluster_ControlPlaneEndpointsConfig_DnsEndpointConfig[];
  ipEndpointsConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
}

export interface Cluster_DatabaseEncryption {
  keyName: string;
  state: string;
}

export interface Cluster_DnsConfig {
  additiveVpcScopeDnsDomain: string;
  clusterDns: string;
  clusterDnsDomain: string;
  clusterDnsScope: string;
}

export interface Cluster_EnableK8sBetaApis {
  enabledApis: string[];
}

export interface Cluster_EnterpriseConfig {
  clusterTier: string;
  desiredTier: string;
}

export interface Cluster_Fleet {
  membership: string;
  membershipId: string;
  membershipLocation: string;
  membershipType: string;
  preRegistered: boolean;
  project: string;
}

export interface Cluster_GatewayApiConfig {
  channel: string;
}

export interface Cluster_GkeAutoUpgradeConfig {
  patchMode: string;
}

export interface Cluster_IpAllocationPolicy_AdditionalIpRangesConfig {
  podIpv4RangeNames: string[];
  status: string;
  subnetwork: string;
}

export interface Cluster_IpAllocationPolicy_AdditionalPodRangesConfig {
  podRangeNames: string[];
}

export interface Cluster_IpAllocationPolicy_NetworkTierConfig {
  networkTier: string;
}

export interface Cluster_IpAllocationPolicy {
  clusterIpv4CidrBlock: string;
  clusterSecondaryRangeName: string;
  servicesIpv4CidrBlock: string;
  servicesSecondaryRangeName: string;
  stackType: string;
  additionalIpRangesConfig: Cluster_IpAllocationPolicy_AdditionalIpRangesConfig[];
  additionalPodRangesConfig: Cluster_IpAllocationPolicy_AdditionalPodRangesConfig[];
  autoIpamConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  networkTierConfig: Cluster_IpAllocationPolicy_NetworkTierConfig[];
  podCidrOverprovisionConfig: Cluster_AddonsConfig_HorizontalPodAutoscaling[];
}

export interface Cluster_LoggingConfig {
  enableComponents: string[];
}

export interface Cluster_MaintenancePolicy_DailyMaintenanceWindow {
  duration: string;
  startTime: string;
}

export interface Cluster_MaintenancePolicy_DisruptionBudget {
  lastDisruptionTime: string;
  lastMinorVersionDisruptionTime: string;
  minorVersionDisruptionInterval: string;
  patchVersionDisruptionInterval: string;
}

export interface Cluster_MaintenancePolicy_MaintenanceExclusion_ExclusionOptions {
  endTimeBehavior: string;
  scope: string;
}

export interface Cluster_MaintenancePolicy_MaintenanceExclusion {
  endTime: string;
  exclusionName: string;
  startTime: string;
  exclusionOptions: Cluster_MaintenancePolicy_MaintenanceExclusion_ExclusionOptions[];
}

export interface Cluster_MaintenancePolicy_RecurringMaintenanceWindow_DelayUntil {
  day: number;
  month: number;
  year: number;
}

export interface Cluster_MaintenancePolicy_RecurringMaintenanceWindow_WindowStartTime {
  hours: number;
  minutes: number;
  seconds: number;
}

export interface Cluster_MaintenancePolicy_RecurringMaintenanceWindow {
  recurrence: string;
  windowDuration: string;
  delayUntil: Cluster_MaintenancePolicy_RecurringMaintenanceWindow_DelayUntil[];
  windowStartTime: Cluster_MaintenancePolicy_RecurringMaintenanceWindow_WindowStartTime[];
}

export interface Cluster_MaintenancePolicy_RecurringWindow {
  endTime: string;
  recurrence: string;
  startTime: string;
}

export interface Cluster_MaintenancePolicy {
  dailyMaintenanceWindow: Cluster_MaintenancePolicy_DailyMaintenanceWindow[];
  disruptionBudget: Cluster_MaintenancePolicy_DisruptionBudget[];
  maintenanceExclusion: Cluster_MaintenancePolicy_MaintenanceExclusion[];
  recurringMaintenanceWindow: Cluster_MaintenancePolicy_RecurringMaintenanceWindow[];
  recurringWindow: Cluster_MaintenancePolicy_RecurringWindow[];
}

export interface Cluster_MasterAuth_ClientCertificateConfig {
  issueClientCertificate: boolean;
}

export interface Cluster_MasterAuth {
  clientCertificate: string;
  clientKey: string;
  clusterCaCertificate: string;
  clientCertificateConfig: Cluster_MasterAuth_ClientCertificateConfig[];
}

export interface Cluster_MasterAuthorizedNetworksConfig_CidrBlocks {
  cidrBlock: string;
  displayName: string;
}

export interface Cluster_MasterAuthorizedNetworksConfig {
  gcpPublicCidrsAccessEnabled: boolean;
  privateEndpointEnforcementEnabled: boolean;
  cidrBlocks: Cluster_MasterAuthorizedNetworksConfig_CidrBlocks[];
}

export interface Cluster_MeshCertificates {
  enableCertificates: boolean;
}

export interface Cluster_MonitoringConfig_AdvancedDatapathObservabilityConfig {
  enableMetrics: boolean;
  enableRelay: boolean;
}

export interface Cluster_MonitoringConfig_ManagedPrometheus_AutoMonitoringConfig {
  scope: string;
}

export interface Cluster_MonitoringConfig_ManagedPrometheus {
  enabled: boolean;
  autoMonitoringConfig: Cluster_MonitoringConfig_ManagedPrometheus_AutoMonitoringConfig[];
}

export interface Cluster_MonitoringConfig {
  enableComponents: string[];
  advancedDatapathObservabilityConfig: Cluster_MonitoringConfig_AdvancedDatapathObservabilityConfig[];
  managedPrometheus: Cluster_MonitoringConfig_ManagedPrometheus[];
}

export interface Cluster_NetworkPerformanceConfig {
  totalEgressBandwidthTier: string;
}

export interface Cluster_NetworkPolicy {
  enabled: boolean;
  provider: string;
}

export interface Cluster_NodeConfig_EffectiveTaints {
  effect: string;
  key: string;
  value: string;
}

export interface Cluster_NodeConfig_AdvancedMachineFeatures {
  enableNestedVirtualization: boolean;
  performanceMonitoringUnit: string;
  threadsPerCore: number;
}

export interface Cluster_NodeConfig_BootDisk {
  diskType: string;
  provisionedIops: number;
  provisionedThroughput: number;
  sizeGb: number;
}

export interface Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GcpSecretManagerCertificateConfig {
  secretUri: string;
}

export interface Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig {
  fqdns: string[];
  gcpSecretManagerCertificateConfig: Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GcpSecretManagerCertificateConfig[];
}

export interface Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig {
  enabled: boolean;
  certificateAuthorityDomainConfig: Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig[];
}

export interface Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_Ca {
  gcpSecretManagerSecretUri: string;
}

export interface Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_Client {
  cert: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_Ca[];
  key: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_Ca[];
}

export interface Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_Header {
  key: string;
  value: string[];
}

export interface Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts {
  capabilities: string[];
  dialTimeout: string;
  host: string;
  overridePath: boolean;
  ca: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_Ca[];
  client: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_Client[];
  header: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_Header[];
}

export interface Cluster_NodeConfig_ContainerdConfig_RegistryHosts {
  server: string;
  hosts: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts[];
}

export interface Cluster_NodeConfig_ContainerdConfig {
  privateRegistryAccessConfig: Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig[];
  registryHosts: Cluster_NodeConfig_ContainerdConfig_RegistryHosts[];
  writableCgroups: Cluster_AddonsConfig_AgentSandboxConfig[];
}

export interface Cluster_NodeConfig_EphemeralStorageLocalSsdConfig {
  dataCacheCount: number;
  localSsdCount: number;
}

export interface Cluster_NodeConfig_GuestAccelerator_GpuDriverInstallationConfig {
  gpuDriverVersion: string;
}

export interface Cluster_NodeConfig_GuestAccelerator_GpuSharingConfig {
  gpuSharingStrategy: string;
  maxSharedClientsPerGpu: number;
}

export interface Cluster_NodeConfig_GuestAccelerator {
  count: number;
  gpuPartitionSize: string;
  type: string;
  gpuDriverInstallationConfig: Cluster_NodeConfig_GuestAccelerator_GpuDriverInstallationConfig[];
  gpuSharingConfig: Cluster_NodeConfig_GuestAccelerator_GpuSharingConfig[];
}

export interface Cluster_NodeConfig_HostMaintenancePolicy {
  maintenanceInterval: string;
}

export interface Cluster_NodeConfig_KubeletConfig_CrashLoopBackOff {
  maxContainerRestartPeriod: string;
}

export interface Cluster_NodeConfig_KubeletConfig_EvictionMinimumReclaim {
  imagefsAvailable: string;
  imagefsInodesFree: string;
  memoryAvailable: string;
  nodefsAvailable: string;
  nodefsInodesFree: string;
  pidAvailable: string;
}

export interface Cluster_NodeConfig_KubeletConfig_MemoryManager {
  policy: string;
}

export interface Cluster_NodeConfig_KubeletConfig_TopologyManager {
  policy: string;
  scope: string;
}

export interface Cluster_NodeConfig_KubeletConfig {
  allowedUnsafeSysctls: string[];
  containerLogMaxFiles: number;
  containerLogMaxSize: string;
  cpuCfsQuota: boolean;
  cpuCfsQuotaPeriod: string;
  cpuManagerPolicy: string;
  evictionMaxPodGracePeriodSeconds: number;
  imageGcHighThresholdPercent: number;
  imageGcLowThresholdPercent: number;
  imageMaximumGcAge: string;
  imageMinimumGcAge: string;
  insecureKubeletReadonlyPortEnabled: string;
  maxParallelImagePulls: number;
  podPidsLimit: number;
  shutdownGracePeriodCriticalPodsSeconds: number;
  shutdownGracePeriodSeconds: number;
  singleProcessOomKill: boolean;
  crashLoopBackOff: Cluster_NodeConfig_KubeletConfig_CrashLoopBackOff[];
  evictionMinimumReclaim: Cluster_NodeConfig_KubeletConfig_EvictionMinimumReclaim[];
  evictionSoft: Cluster_NodeConfig_KubeletConfig_EvictionMinimumReclaim[];
  evictionSoftGracePeriod: Cluster_NodeConfig_KubeletConfig_EvictionMinimumReclaim[];
  memoryManager: Cluster_NodeConfig_KubeletConfig_MemoryManager[];
  topologyManager: Cluster_NodeConfig_KubeletConfig_TopologyManager[];
}

export interface Cluster_NodeConfig_LinuxNodeConfig_AccurateTimeConfig {
  enablePtpKvmTimeSync: boolean;
}

export interface Cluster_NodeConfig_LinuxNodeConfig_CustomNodeInit_InitScript {
  gcpSecretManagerSecretUri: string;
  gcsGeneration: number;
  gcsUri: string;
}

export interface Cluster_NodeConfig_LinuxNodeConfig_CustomNodeInit {
  initScript: Cluster_NodeConfig_LinuxNodeConfig_CustomNodeInit_InitScript[];
}

export interface Cluster_NodeConfig_LinuxNodeConfig_HugepagesConfig {
  hugepageSize1g: number;
  hugepageSize2m: number;
}

export interface Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_BootDiskProfile {
  swapSizeGib: number;
  swapSizePercent: number;
}

export interface Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_DedicatedLocalSsdProfile {
  diskCount: number;
}

export interface Cluster_NodeConfig_LinuxNodeConfig_SwapConfig {
  enabled: boolean;
  bootDiskProfile: Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_BootDiskProfile[];
  dedicatedLocalSsdProfile: Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_DedicatedLocalSsdProfile[];
  encryptionConfig: Cluster_AddonsConfig_HorizontalPodAutoscaling[];
  ephemeralLocalSsdProfile: Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_BootDiskProfile[];
}

export interface Cluster_NodeConfig_LinuxNodeConfig {
  cgroupMode: string;
  sysctls: Record<string, string>;
  transparentHugepageDefrag: string;
  transparentHugepageEnabled: string;
  accurateTimeConfig: Cluster_NodeConfig_LinuxNodeConfig_AccurateTimeConfig[];
  customNodeInit: Cluster_NodeConfig_LinuxNodeConfig_CustomNodeInit[];
  hugepagesConfig: Cluster_NodeConfig_LinuxNodeConfig_HugepagesConfig[];
  nodeKernelModuleLoading: Cluster_NodeConfig_KubeletConfig_MemoryManager[];
  swapConfig: Cluster_NodeConfig_LinuxNodeConfig_SwapConfig[];
}

export interface Cluster_NodeConfig_LocalNvmeSsdBlockConfig {
  localSsdCount: number;
}

export interface Cluster_NodeConfig_NodeImageConfig {
  image: string;
  imageProject: string;
}

export interface Cluster_NodeConfig_ReservationAffinity {
  consumeReservationType: string;
  key: string;
  values: string[];
}

export interface Cluster_NodeConfig_SandboxConfig {
  type: string;
}

export interface Cluster_NodeConfig_SecondaryBootDisks {
  diskImage: string;
  mode: string;
}

export interface Cluster_NodeConfig_SoleTenantConfig_NodeAffinity {
  key: string;
  operator: string;
  values: string[];
}

export interface Cluster_NodeConfig_SoleTenantConfig {
  minNodeCpus: number;
  nodeAffinity: Cluster_NodeConfig_SoleTenantConfig_NodeAffinity[];
}

export interface Cluster_NodeConfig_TaintConfig {
  architectureTaintBehavior: string;
}

export interface Cluster_NodeConfig_WindowsNodeConfig {
  osversion: string;
}

export interface Cluster_NodeConfig {
  bootDiskKmsKey: string;
  diskSizeGb: number;
  diskType: string;
  effectiveTaints: Cluster_NodeConfig_EffectiveTaints[];
  enableConfidentialStorage: boolean;
  flexStart: boolean;
  gpudirectStrategy: string;
  imageType: string;
  labels: Record<string, string>;
  localSsdCount: number;
  localSsdEncryptionMode: string;
  loggingVariant: string;
  machineType: string;
  maxRunDuration: string;
  metadata: Record<string, string>;
  minCpuPlatform: string;
  nodeGroup: string;
  oauthScopes: string[];
  preemptible: boolean;
  resourceLabels: Record<string, string>;
  resourceManagerTags: Record<string, string>;
  serviceAccount: string;
  spot: boolean;
  storagePools: string[];
  tags: string[];
  advancedMachineFeatures: Cluster_NodeConfig_AdvancedMachineFeatures[];
  bootDisk: Cluster_NodeConfig_BootDisk[];
  confidentialNodes: Cluster_ConfidentialNodes[];
  containerdConfig: Cluster_NodeConfig_ContainerdConfig[];
  ephemeralStorageLocalSsdConfig: Cluster_NodeConfig_EphemeralStorageLocalSsdConfig[];
  fastSocket: Cluster_AddonsConfig_AgentSandboxConfig[];
  gcfsConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  guestAccelerator: Cluster_NodeConfig_GuestAccelerator[];
  gvnic: Cluster_AddonsConfig_AgentSandboxConfig[];
  hostMaintenancePolicy: Cluster_NodeConfig_HostMaintenancePolicy[];
  kubeletConfig: Cluster_NodeConfig_KubeletConfig[];
  linuxNodeConfig: Cluster_NodeConfig_LinuxNodeConfig[];
  localNvmeSsdBlockConfig: Cluster_NodeConfig_LocalNvmeSsdBlockConfig[];
  nodeImageConfig: Cluster_NodeConfig_NodeImageConfig[];
  reservationAffinity: Cluster_NodeConfig_ReservationAffinity[];
  sandboxConfig: Cluster_NodeConfig_SandboxConfig[];
  secondaryBootDisks: Cluster_NodeConfig_SecondaryBootDisks[];
  shieldedInstanceConfig: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_ShieldedInstanceConfig[];
  soleTenantConfig: Cluster_NodeConfig_SoleTenantConfig[];
  taint: Cluster_NodeConfig_EffectiveTaints[];
  taintConfig: Cluster_NodeConfig_TaintConfig[];
  windowsNodeConfig: Cluster_NodeConfig_WindowsNodeConfig[];
  workloadMetadataConfig: Cluster_AnonymousAuthenticationConfig[];
}

export interface Cluster_NodeCreationConfig {
  nodeCreationMode: string;
}

export interface Cluster_NodePool_Autoscaling {
  locationPolicy: string;
  maxNodeCount: number;
  minNodeCount: number;
  totalMaxNodeCount: number;
  totalMinNodeCount: number;
}

export interface Cluster_NodePool_MaintenancePolicy_ExclusionUntilEndOfSupport {
  enabled: boolean;
  endTime: string;
  startTime: string;
}

export interface Cluster_NodePool_MaintenancePolicy {
  exclusionUntilEndOfSupport: Cluster_NodePool_MaintenancePolicy_ExclusionUntilEndOfSupport[];
}

export interface Cluster_NodePool_Management {
  autoRepair: boolean;
  autoUpgrade: boolean;
}

export interface Cluster_NodePool_NetworkConfig_AdditionalNodeNetworkConfigs {
  network: string;
  subnetwork: string;
}

export interface Cluster_NodePool_NetworkConfig_AdditionalPodNetworkConfigs {
  maxPodsPerNode: number;
  secondaryPodRange: string;
  subnetwork: string;
}

export interface Cluster_NodePool_NetworkConfig {
  acceleratorNetworkProfile: string;
  createPodRange: boolean;
  enablePrivateNodes: boolean;
  podIpv4CidrBlock: string;
  podRange: string;
  subnetwork: string;
  additionalNodeNetworkConfigs: Cluster_NodePool_NetworkConfig_AdditionalNodeNetworkConfigs[];
  additionalPodNetworkConfigs: Cluster_NodePool_NetworkConfig_AdditionalPodNetworkConfigs[];
  networkPerformanceConfig: Cluster_NetworkPerformanceConfig[];
  podCidrOverprovisionConfig: Cluster_AddonsConfig_HorizontalPodAutoscaling[];
}

export interface Cluster_NodePool_NodeDrainConfig {
  graceTerminationDuration: string;
  pdbTimeoutDuration: string;
  respectPdbDuringNodePoolDeletion: boolean;
}

export interface Cluster_NodePool_PlacementPolicy {
  policyName: string;
  tpuTopology: string;
  type: string;
}

export interface Cluster_NodePool {
  ignoreNodeCountChanges: boolean;
  initialNodeCount: number;
  instanceGroupUrls: string[];
  managedInstanceGroupUrls: string[];
  maxPodsPerNode: number;
  name: string;
  namePrefix: string;
  nodeCount: number;
  nodeLocations: string[];
  version: string;
  autoscaling: Cluster_NodePool_Autoscaling[];
  maintenancePolicy: Cluster_NodePool_MaintenancePolicy[];
  management: Cluster_NodePool_Management[];
  networkConfig: Cluster_NodePool_NetworkConfig[];
  nodeConfig: Cluster_NodeConfig[];
  nodeDrainConfig: Cluster_NodePool_NodeDrainConfig[];
  placementPolicy: Cluster_NodePool_PlacementPolicy[];
  queuedProvisioning: Cluster_AddonsConfig_AgentSandboxConfig[];
  upgradeSettings: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings[];
}

export interface Cluster_NodePoolAutoConfig_LinuxNodeConfig {
  cgroupMode: string;
  nodeKernelModuleLoading: Cluster_NodeConfig_KubeletConfig_MemoryManager[];
}

export interface Cluster_NodePoolAutoConfig_NetworkTags {
  tags: string[];
}

export interface Cluster_NodePoolAutoConfig_NodeKubeletConfig {
  insecureKubeletReadonlyPortEnabled: string;
}

export interface Cluster_NodePoolAutoConfig {
  resourceManagerTags: Record<string, string>;
  linuxNodeConfig: Cluster_NodePoolAutoConfig_LinuxNodeConfig[];
  networkTags: Cluster_NodePoolAutoConfig_NetworkTags[];
  nodeKubeletConfig: Cluster_NodePoolAutoConfig_NodeKubeletConfig[];
}

export interface Cluster_NodePoolDefaults_NodeConfigDefaults {
  insecureKubeletReadonlyPortEnabled: string;
  loggingVariant: string;
  containerdConfig: Cluster_NodeConfig_ContainerdConfig[];
  gcfsConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
}

export interface Cluster_NodePoolDefaults {
  nodeConfigDefaults: Cluster_NodePoolDefaults_NodeConfigDefaults[];
}

export interface Cluster_NotificationConfig_Pubsub_Filter {
  eventType: string[];
}

export interface Cluster_NotificationConfig_Pubsub {
  enabled: boolean;
  topic: string;
  filter: Cluster_NotificationConfig_Pubsub_Filter[];
}

export interface Cluster_NotificationConfig {
  pubsub: Cluster_NotificationConfig_Pubsub[];
}

export interface Cluster_PodAutoscaling {
  hpaProfile: string;
}

export interface Cluster_PrivateClusterConfig {
  enablePrivateEndpoint: boolean;
  enablePrivateNodes: boolean;
  masterIpv4CidrBlock: string;
  peeringName: string;
  privateEndpoint: string;
  privateEndpointSubnetwork: string;
  publicEndpoint: string;
  masterGlobalAccessConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
}

export interface Cluster_RbacBindingConfig {
  enableInsecureBindingSystemAuthenticated: boolean;
  enableInsecureBindingSystemUnauthenticated: boolean;
}

export interface Cluster_ResourceUsageExportConfig_BigqueryDestination {
  datasetId: string;
}

export interface Cluster_ResourceUsageExportConfig {
  enableNetworkEgressMetering: boolean;
  enableResourceConsumptionMetering: boolean;
  bigqueryDestination: Cluster_ResourceUsageExportConfig_BigqueryDestination[];
}

export interface Cluster_RollbackSafeUpgrade {
  controlPlaneSoakDuration: string;
}

export interface Cluster_SecretManagerConfig_RotationConfig {
  enabled: boolean;
  rotationInterval: string;
}

export interface Cluster_SecretManagerConfig {
  enabled: boolean;
  rotationConfig: Cluster_SecretManagerConfig_RotationConfig[];
}

export interface Cluster_SecurityPostureConfig {
  mode: string;
  vulnerabilityMode: string;
}

export interface Cluster_Timeouts {
  create: string;
  delete: string;
  read: string;
  update: string;
}

export interface Cluster_UserManagedKeysConfig {
  aggregationCa: string;
  clusterCa: string;
  controlPlaneDiskEncryptionKey: string;
  controlPlaneDiskEncryptionKeyVersions: string[];
  etcdApiCa: string;
  etcdPeerCa: string;
  gkeopsEtcdBackupEncryptionKey: string;
  serviceAccountSigningKeys: string[];
  serviceAccountVerificationKeys: string[];
}

export interface Cluster_WorkloadIdentityConfig {
  workloadPool: string;
}

const Cluster_AddonsConfig_AgentSandboxConfigFields: FieldMap = {
  enabled: "enabled",
};

const Cluster_AddonsConfig_CloudrunConfigFields: FieldMap = {
  disabled: "disabled",
  loadBalancerType: "load_balancer_type",
};

const Cluster_AddonsConfig_HorizontalPodAutoscalingFields: FieldMap = {
  disabled: "disabled",
};

const Cluster_AddonsConfig_LustreCsiDriverConfigFields: FieldMap = {
  disableMultiNic: "disable_multi_nic",
  enableLegacyLustrePort: "enable_legacy_lustre_port",
  enabled: "enabled",
};

const Cluster_AddonsConfig_RayOperatorConfigFields: FieldMap = {
  enabled: "enabled",
  rayClusterLoggingConfig: {
    wireName: "ray_cluster_logging_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  rayClusterMonitoringConfig: {
    wireName: "ray_cluster_monitoring_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
};

const Cluster_AddonsConfigFields: FieldMap = {
  agentSandboxConfig: {
    wireName: "agent_sandbox_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  cloudrunConfig: {
    wireName: "cloudrun_config",
    kind: "list",
    fields: Cluster_AddonsConfig_CloudrunConfigFields,
  },
  configConnectorConfig: {
    wireName: "config_connector_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  dnsCacheConfig: {
    wireName: "dns_cache_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  gcePersistentDiskCsiDriverConfig: {
    wireName: "gce_persistent_disk_csi_driver_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  gcpFilestoreCsiDriverConfig: {
    wireName: "gcp_filestore_csi_driver_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  gcsFuseCsiDriverConfig: {
    wireName: "gcs_fuse_csi_driver_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  gkeBackupAgentConfig: {
    wireName: "gke_backup_agent_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  horizontalPodAutoscaling: {
    wireName: "horizontal_pod_autoscaling",
    kind: "list",
    fields: Cluster_AddonsConfig_HorizontalPodAutoscalingFields,
  },
  httpLoadBalancing: {
    wireName: "http_load_balancing",
    kind: "list",
    fields: Cluster_AddonsConfig_HorizontalPodAutoscalingFields,
  },
  lustreCsiDriverConfig: {
    wireName: "lustre_csi_driver_config",
    kind: "list",
    fields: Cluster_AddonsConfig_LustreCsiDriverConfigFields,
  },
  networkPolicyConfig: {
    wireName: "network_policy_config",
    kind: "list",
    fields: Cluster_AddonsConfig_HorizontalPodAutoscalingFields,
  },
  nodeReadinessConfig: {
    wireName: "node_readiness_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  parallelstoreCsiDriverConfig: {
    wireName: "parallelstore_csi_driver_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  podSnapshotConfig: {
    wireName: "pod_snapshot_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  rayOperatorConfig: {
    wireName: "ray_operator_config",
    kind: "list",
    fields: Cluster_AddonsConfig_RayOperatorConfigFields,
  },
  sliceControllerConfig: {
    wireName: "slice_controller_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  slurmOperatorConfig: {
    wireName: "slurm_operator_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  statefulHaConfig: {
    wireName: "stateful_ha_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
};

const Cluster_AnonymousAuthenticationConfigFields: FieldMap = {
  mode: "mode",
};

const Cluster_AuthenticatorGroupsConfigFields: FieldMap = {
  securityGroup: "security_group",
};

const Cluster_AutopilotClusterPolicyConfigFields: FieldMap = {
  noStandardNodePools: "no_standard_node_pools",
  noSystemImpersonation: "no_system_impersonation",
  noSystemMutation: "no_system_mutation",
  noUnsafeWebhooks: "no_unsafe_webhooks",
};

const Cluster_BinaryAuthorizationFields: FieldMap = {
  enabled: "enabled",
  evaluationMode: "evaluation_mode",
};

const Cluster_ClusterAutoscaling_AutoProvisioningDefaults_Management_UpgradeOptionsFields: FieldMap = {
  autoUpgradeStartTime: "auto_upgrade_start_time",
  description: "description",
};

const Cluster_ClusterAutoscaling_AutoProvisioningDefaults_ManagementFields: FieldMap = {
  autoRepair: "auto_repair",
  autoUpgrade: "auto_upgrade",
  upgradeOptions: {
    wireName: "upgrade_options",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_Management_UpgradeOptionsFields,
  },
};

const Cluster_ClusterAutoscaling_AutoProvisioningDefaults_ShieldedInstanceConfigFields: FieldMap = {
  enableIntegrityMonitoring: "enable_integrity_monitoring",
  enableSecureBoot: "enable_secure_boot",
};

const Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings_BlueGreenSettings_StandardRolloutPolicyFields: FieldMap = {
  batchNodeCount: "batch_node_count",
  batchPercentage: "batch_percentage",
  batchSoakDuration: "batch_soak_duration",
};

const Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings_BlueGreenSettingsFields: FieldMap = {
  nodePoolSoakDuration: "node_pool_soak_duration",
  standardRolloutPolicy: {
    wireName: "standard_rollout_policy",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings_BlueGreenSettings_StandardRolloutPolicyFields,
  },
};

const Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettingsFields: FieldMap = {
  maxSurge: "max_surge",
  maxUnavailable: "max_unavailable",
  strategy: "strategy",
  blueGreenSettings: {
    wireName: "blue_green_settings",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettings_BlueGreenSettingsFields,
  },
};

const Cluster_ClusterAutoscaling_AutoProvisioningDefaultsFields: FieldMap = {
  bootDiskKmsKey: "boot_disk_kms_key",
  diskSize: "disk_size",
  diskType: "disk_type",
  imageType: "image_type",
  minCpuPlatform: "min_cpu_platform",
  oauthScopes: "oauth_scopes",
  serviceAccount: "service_account",
  management: {
    wireName: "management",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_ManagementFields,
  },
  shieldedInstanceConfig: {
    wireName: "shielded_instance_config",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_ShieldedInstanceConfigFields,
  },
  upgradeSettings: {
    wireName: "upgrade_settings",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettingsFields,
  },
};

const Cluster_ClusterAutoscaling_ResourceLimitsFields: FieldMap = {
  maximum: "maximum",
  minimum: "minimum",
  resourceType: "resource_type",
};

const Cluster_ClusterAutoscalingFields: FieldMap = {
  autoProvisioningLocations: "auto_provisioning_locations",
  autoscalingProfile: "autoscaling_profile",
  defaultComputeClassEnabled: "default_compute_class_enabled",
  enabled: "enabled",
  autoProvisioningDefaults: {
    wireName: "auto_provisioning_defaults",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaultsFields,
  },
  resourceLimits: {
    wireName: "resource_limits",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_ResourceLimitsFields,
  },
};

const Cluster_ConfidentialNodesFields: FieldMap = {
  confidentialInstanceType: "confidential_instance_type",
  enabled: "enabled",
};

const Cluster_ControlPlaneEndpointsConfig_DnsEndpointConfigFields: FieldMap = {
  allowExternalTraffic: "allow_external_traffic",
  enableK8sCertsViaDns: "enable_k8s_certs_via_dns",
  enableK8sTokensViaDns: "enable_k8s_tokens_via_dns",
  endpoint: "endpoint",
};

const Cluster_ControlPlaneEndpointsConfigFields: FieldMap = {
  dnsEndpointConfig: {
    wireName: "dns_endpoint_config",
    kind: "list",
    fields: Cluster_ControlPlaneEndpointsConfig_DnsEndpointConfigFields,
  },
  ipEndpointsConfig: {
    wireName: "ip_endpoints_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
};

const Cluster_DatabaseEncryptionFields: FieldMap = {
  keyName: "key_name",
  state: "state",
};

const Cluster_DnsConfigFields: FieldMap = {
  additiveVpcScopeDnsDomain: "additive_vpc_scope_dns_domain",
  clusterDns: "cluster_dns",
  clusterDnsDomain: "cluster_dns_domain",
  clusterDnsScope: "cluster_dns_scope",
};

const Cluster_EnableK8sBetaApisFields: FieldMap = {
  enabledApis: "enabled_apis",
};

const Cluster_EnterpriseConfigFields: FieldMap = {
  clusterTier: "cluster_tier",
  desiredTier: "desired_tier",
};

const Cluster_FleetFields: FieldMap = {
  membership: "membership",
  membershipId: "membership_id",
  membershipLocation: "membership_location",
  membershipType: "membership_type",
  preRegistered: "pre_registered",
  project: "project",
};

const Cluster_GatewayApiConfigFields: FieldMap = {
  channel: "channel",
};

const Cluster_GkeAutoUpgradeConfigFields: FieldMap = {
  patchMode: "patch_mode",
};

const Cluster_IpAllocationPolicy_AdditionalIpRangesConfigFields: FieldMap = {
  podIpv4RangeNames: "pod_ipv4_range_names",
  status: "status",
  subnetwork: "subnetwork",
};

const Cluster_IpAllocationPolicy_AdditionalPodRangesConfigFields: FieldMap = {
  podRangeNames: "pod_range_names",
};

const Cluster_IpAllocationPolicy_NetworkTierConfigFields: FieldMap = {
  networkTier: "network_tier",
};

const Cluster_IpAllocationPolicyFields: FieldMap = {
  clusterIpv4CidrBlock: "cluster_ipv4_cidr_block",
  clusterSecondaryRangeName: "cluster_secondary_range_name",
  servicesIpv4CidrBlock: "services_ipv4_cidr_block",
  servicesSecondaryRangeName: "services_secondary_range_name",
  stackType: "stack_type",
  additionalIpRangesConfig: {
    wireName: "additional_ip_ranges_config",
    kind: "list",
    fields: Cluster_IpAllocationPolicy_AdditionalIpRangesConfigFields,
  },
  additionalPodRangesConfig: {
    wireName: "additional_pod_ranges_config",
    kind: "list",
    fields: Cluster_IpAllocationPolicy_AdditionalPodRangesConfigFields,
  },
  autoIpamConfig: {
    wireName: "auto_ipam_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  networkTierConfig: {
    wireName: "network_tier_config",
    kind: "list",
    fields: Cluster_IpAllocationPolicy_NetworkTierConfigFields,
  },
  podCidrOverprovisionConfig: {
    wireName: "pod_cidr_overprovision_config",
    kind: "list",
    fields: Cluster_AddonsConfig_HorizontalPodAutoscalingFields,
  },
};

const Cluster_LoggingConfigFields: FieldMap = {
  enableComponents: "enable_components",
};

const Cluster_MaintenancePolicy_DailyMaintenanceWindowFields: FieldMap = {
  duration: "duration",
  startTime: "start_time",
};

const Cluster_MaintenancePolicy_DisruptionBudgetFields: FieldMap = {
  lastDisruptionTime: "last_disruption_time",
  lastMinorVersionDisruptionTime: "last_minor_version_disruption_time",
  minorVersionDisruptionInterval: "minor_version_disruption_interval",
  patchVersionDisruptionInterval: "patch_version_disruption_interval",
};

const Cluster_MaintenancePolicy_MaintenanceExclusion_ExclusionOptionsFields: FieldMap = {
  endTimeBehavior: "end_time_behavior",
  scope: "scope",
};

const Cluster_MaintenancePolicy_MaintenanceExclusionFields: FieldMap = {
  endTime: "end_time",
  exclusionName: "exclusion_name",
  startTime: "start_time",
  exclusionOptions: {
    wireName: "exclusion_options",
    kind: "list",
    fields: Cluster_MaintenancePolicy_MaintenanceExclusion_ExclusionOptionsFields,
  },
};

const Cluster_MaintenancePolicy_RecurringMaintenanceWindow_DelayUntilFields: FieldMap = {
  day: "day",
  month: "month",
  year: "year",
};

const Cluster_MaintenancePolicy_RecurringMaintenanceWindow_WindowStartTimeFields: FieldMap = {
  hours: "hours",
  minutes: "minutes",
  seconds: "seconds",
};

const Cluster_MaintenancePolicy_RecurringMaintenanceWindowFields: FieldMap = {
  recurrence: "recurrence",
  windowDuration: "window_duration",
  delayUntil: {
    wireName: "delay_until",
    kind: "list",
    fields: Cluster_MaintenancePolicy_RecurringMaintenanceWindow_DelayUntilFields,
  },
  windowStartTime: {
    wireName: "window_start_time",
    kind: "list",
    fields: Cluster_MaintenancePolicy_RecurringMaintenanceWindow_WindowStartTimeFields,
  },
};

const Cluster_MaintenancePolicy_RecurringWindowFields: FieldMap = {
  endTime: "end_time",
  recurrence: "recurrence",
  startTime: "start_time",
};

const Cluster_MaintenancePolicyFields: FieldMap = {
  dailyMaintenanceWindow: {
    wireName: "daily_maintenance_window",
    kind: "list",
    fields: Cluster_MaintenancePolicy_DailyMaintenanceWindowFields,
  },
  disruptionBudget: {
    wireName: "disruption_budget",
    kind: "list",
    fields: Cluster_MaintenancePolicy_DisruptionBudgetFields,
  },
  maintenanceExclusion: {
    wireName: "maintenance_exclusion",
    kind: "set",
    fields: Cluster_MaintenancePolicy_MaintenanceExclusionFields,
  },
  recurringMaintenanceWindow: {
    wireName: "recurring_maintenance_window",
    kind: "list",
    fields: Cluster_MaintenancePolicy_RecurringMaintenanceWindowFields,
  },
  recurringWindow: {
    wireName: "recurring_window",
    kind: "list",
    fields: Cluster_MaintenancePolicy_RecurringWindowFields,
  },
};

const Cluster_MasterAuth_ClientCertificateConfigFields: FieldMap = {
  issueClientCertificate: "issue_client_certificate",
};

const Cluster_MasterAuthFields: FieldMap = {
  clientCertificate: "client_certificate",
  clientKey: "client_key",
  clusterCaCertificate: "cluster_ca_certificate",
  clientCertificateConfig: {
    wireName: "client_certificate_config",
    kind: "list",
    fields: Cluster_MasterAuth_ClientCertificateConfigFields,
  },
};

const Cluster_MasterAuthorizedNetworksConfig_CidrBlocksFields: FieldMap = {
  cidrBlock: "cidr_block",
  displayName: "display_name",
};

const Cluster_MasterAuthorizedNetworksConfigFields: FieldMap = {
  gcpPublicCidrsAccessEnabled: "gcp_public_cidrs_access_enabled",
  privateEndpointEnforcementEnabled: "private_endpoint_enforcement_enabled",
  cidrBlocks: {
    wireName: "cidr_blocks",
    kind: "set",
    fields: Cluster_MasterAuthorizedNetworksConfig_CidrBlocksFields,
  },
};

const Cluster_MeshCertificatesFields: FieldMap = {
  enableCertificates: "enable_certificates",
};

const Cluster_MonitoringConfig_AdvancedDatapathObservabilityConfigFields: FieldMap = {
  enableMetrics: "enable_metrics",
  enableRelay: "enable_relay",
};

const Cluster_MonitoringConfig_ManagedPrometheus_AutoMonitoringConfigFields: FieldMap = {
  scope: "scope",
};

const Cluster_MonitoringConfig_ManagedPrometheusFields: FieldMap = {
  enabled: "enabled",
  autoMonitoringConfig: {
    wireName: "auto_monitoring_config",
    kind: "list",
    fields: Cluster_MonitoringConfig_ManagedPrometheus_AutoMonitoringConfigFields,
  },
};

const Cluster_MonitoringConfigFields: FieldMap = {
  enableComponents: "enable_components",
  advancedDatapathObservabilityConfig: {
    wireName: "advanced_datapath_observability_config",
    kind: "list",
    fields: Cluster_MonitoringConfig_AdvancedDatapathObservabilityConfigFields,
  },
  managedPrometheus: {
    wireName: "managed_prometheus",
    kind: "list",
    fields: Cluster_MonitoringConfig_ManagedPrometheusFields,
  },
};

const Cluster_NetworkPerformanceConfigFields: FieldMap = {
  totalEgressBandwidthTier: "total_egress_bandwidth_tier",
};

const Cluster_NetworkPolicyFields: FieldMap = {
  enabled: "enabled",
  provider: "provider",
};

const Cluster_NodeConfig_EffectiveTaintsFields: FieldMap = {
  effect: "effect",
  key: "key",
  value: "value",
};

const Cluster_NodeConfig_AdvancedMachineFeaturesFields: FieldMap = {
  enableNestedVirtualization: "enable_nested_virtualization",
  performanceMonitoringUnit: "performance_monitoring_unit",
  threadsPerCore: "threads_per_core",
};

const Cluster_NodeConfig_BootDiskFields: FieldMap = {
  diskType: "disk_type",
  provisionedIops: "provisioned_iops",
  provisionedThroughput: "provisioned_throughput",
  sizeGb: "size_gb",
};

const Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GcpSecretManagerCertificateConfigFields: FieldMap = {
  secretUri: "secret_uri",
};

const Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfigFields: FieldMap = {
  fqdns: "fqdns",
  gcpSecretManagerCertificateConfig: {
    wireName: "gcp_secret_manager_certificate_config",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GcpSecretManagerCertificateConfigFields,
  },
};

const Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfigFields: FieldMap = {
  enabled: "enabled",
  certificateAuthorityDomainConfig: {
    wireName: "certificate_authority_domain_config",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfigFields,
  },
};

const Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_CaFields: FieldMap = {
  gcpSecretManagerSecretUri: "gcp_secret_manager_secret_uri",
};

const Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_ClientFields: FieldMap = {
  cert: {
    wireName: "cert",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_CaFields,
  },
  key: {
    wireName: "key",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_CaFields,
  },
};

const Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_HeaderFields: FieldMap = {
  key: "key",
  value: "value",
};

const Cluster_NodeConfig_ContainerdConfig_RegistryHosts_HostsFields: FieldMap = {
  capabilities: "capabilities",
  dialTimeout: "dial_timeout",
  host: "host",
  overridePath: "override_path",
  ca: {
    wireName: "ca",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_CaFields,
  },
  client: {
    wireName: "client",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_ClientFields,
  },
  header: {
    wireName: "header",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_Hosts_HeaderFields,
  },
};

const Cluster_NodeConfig_ContainerdConfig_RegistryHostsFields: FieldMap = {
  server: "server",
  hosts: {
    wireName: "hosts",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_RegistryHosts_HostsFields,
  },
};

const Cluster_NodeConfig_ContainerdConfigFields: FieldMap = {
  privateRegistryAccessConfig: {
    wireName: "private_registry_access_config",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_PrivateRegistryAccessConfigFields,
  },
  registryHosts: {
    wireName: "registry_hosts",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfig_RegistryHostsFields,
  },
  writableCgroups: {
    wireName: "writable_cgroups",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
};

const Cluster_NodeConfig_EphemeralStorageLocalSsdConfigFields: FieldMap = {
  dataCacheCount: "data_cache_count",
  localSsdCount: "local_ssd_count",
};

const Cluster_NodeConfig_GuestAccelerator_GpuDriverInstallationConfigFields: FieldMap = {
  gpuDriverVersion: "gpu_driver_version",
};

const Cluster_NodeConfig_GuestAccelerator_GpuSharingConfigFields: FieldMap = {
  gpuSharingStrategy: "gpu_sharing_strategy",
  maxSharedClientsPerGpu: "max_shared_clients_per_gpu",
};

const Cluster_NodeConfig_GuestAcceleratorFields: FieldMap = {
  count: "count",
  gpuPartitionSize: "gpu_partition_size",
  type: "type",
  gpuDriverInstallationConfig: {
    wireName: "gpu_driver_installation_config",
    kind: "list",
    fields: Cluster_NodeConfig_GuestAccelerator_GpuDriverInstallationConfigFields,
  },
  gpuSharingConfig: {
    wireName: "gpu_sharing_config",
    kind: "list",
    fields: Cluster_NodeConfig_GuestAccelerator_GpuSharingConfigFields,
  },
};

const Cluster_NodeConfig_HostMaintenancePolicyFields: FieldMap = {
  maintenanceInterval: "maintenance_interval",
};

const Cluster_NodeConfig_KubeletConfig_CrashLoopBackOffFields: FieldMap = {
  maxContainerRestartPeriod: "max_container_restart_period",
};

const Cluster_NodeConfig_KubeletConfig_EvictionMinimumReclaimFields: FieldMap = {
  imagefsAvailable: "imagefs_available",
  imagefsInodesFree: "imagefs_inodes_free",
  memoryAvailable: "memory_available",
  nodefsAvailable: "nodefs_available",
  nodefsInodesFree: "nodefs_inodes_free",
  pidAvailable: "pid_available",
};

const Cluster_NodeConfig_KubeletConfig_MemoryManagerFields: FieldMap = {
  policy: "policy",
};

const Cluster_NodeConfig_KubeletConfig_TopologyManagerFields: FieldMap = {
  policy: "policy",
  scope: "scope",
};

const Cluster_NodeConfig_KubeletConfigFields: FieldMap = {
  allowedUnsafeSysctls: "allowed_unsafe_sysctls",
  containerLogMaxFiles: "container_log_max_files",
  containerLogMaxSize: "container_log_max_size",
  cpuCfsQuota: "cpu_cfs_quota",
  cpuCfsQuotaPeriod: "cpu_cfs_quota_period",
  cpuManagerPolicy: "cpu_manager_policy",
  evictionMaxPodGracePeriodSeconds: "eviction_max_pod_grace_period_seconds",
  imageGcHighThresholdPercent: "image_gc_high_threshold_percent",
  imageGcLowThresholdPercent: "image_gc_low_threshold_percent",
  imageMaximumGcAge: "image_maximum_gc_age",
  imageMinimumGcAge: "image_minimum_gc_age",
  insecureKubeletReadonlyPortEnabled: "insecure_kubelet_readonly_port_enabled",
  maxParallelImagePulls: "max_parallel_image_pulls",
  podPidsLimit: "pod_pids_limit",
  shutdownGracePeriodCriticalPodsSeconds: "shutdown_grace_period_critical_pods_seconds",
  shutdownGracePeriodSeconds: "shutdown_grace_period_seconds",
  singleProcessOomKill: "single_process_oom_kill",
  crashLoopBackOff: {
    wireName: "crash_loop_back_off",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfig_CrashLoopBackOffFields,
  },
  evictionMinimumReclaim: {
    wireName: "eviction_minimum_reclaim",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfig_EvictionMinimumReclaimFields,
  },
  evictionSoft: {
    wireName: "eviction_soft",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfig_EvictionMinimumReclaimFields,
  },
  evictionSoftGracePeriod: {
    wireName: "eviction_soft_grace_period",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfig_EvictionMinimumReclaimFields,
  },
  memoryManager: {
    wireName: "memory_manager",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfig_MemoryManagerFields,
  },
  topologyManager: {
    wireName: "topology_manager",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfig_TopologyManagerFields,
  },
};

const Cluster_NodeConfig_LinuxNodeConfig_AccurateTimeConfigFields: FieldMap = {
  enablePtpKvmTimeSync: "enable_ptp_kvm_time_sync",
};

const Cluster_NodeConfig_LinuxNodeConfig_CustomNodeInit_InitScriptFields: FieldMap = {
  gcpSecretManagerSecretUri: "gcp_secret_manager_secret_uri",
  gcsGeneration: "gcs_generation",
  gcsUri: "gcs_uri",
};

const Cluster_NodeConfig_LinuxNodeConfig_CustomNodeInitFields: FieldMap = {
  initScript: {
    wireName: "init_script",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfig_CustomNodeInit_InitScriptFields,
  },
};

const Cluster_NodeConfig_LinuxNodeConfig_HugepagesConfigFields: FieldMap = {
  hugepageSize1g: "hugepage_size_1g",
  hugepageSize2m: "hugepage_size_2m",
};

const Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_BootDiskProfileFields: FieldMap = {
  swapSizeGib: "swap_size_gib",
  swapSizePercent: "swap_size_percent",
};

const Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_DedicatedLocalSsdProfileFields: FieldMap = {
  diskCount: "disk_count",
};

const Cluster_NodeConfig_LinuxNodeConfig_SwapConfigFields: FieldMap = {
  enabled: "enabled",
  bootDiskProfile: {
    wireName: "boot_disk_profile",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_BootDiskProfileFields,
  },
  dedicatedLocalSsdProfile: {
    wireName: "dedicated_local_ssd_profile",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_DedicatedLocalSsdProfileFields,
  },
  encryptionConfig: {
    wireName: "encryption_config",
    kind: "list",
    fields: Cluster_AddonsConfig_HorizontalPodAutoscalingFields,
  },
  ephemeralLocalSsdProfile: {
    wireName: "ephemeral_local_ssd_profile",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfig_SwapConfig_BootDiskProfileFields,
  },
};

const Cluster_NodeConfig_LinuxNodeConfigFields: FieldMap = {
  cgroupMode: "cgroup_mode",
  sysctls: "sysctls",
  transparentHugepageDefrag: "transparent_hugepage_defrag",
  transparentHugepageEnabled: "transparent_hugepage_enabled",
  accurateTimeConfig: {
    wireName: "accurate_time_config",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfig_AccurateTimeConfigFields,
  },
  customNodeInit: {
    wireName: "custom_node_init",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfig_CustomNodeInitFields,
  },
  hugepagesConfig: {
    wireName: "hugepages_config",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfig_HugepagesConfigFields,
  },
  nodeKernelModuleLoading: {
    wireName: "node_kernel_module_loading",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfig_MemoryManagerFields,
  },
  swapConfig: {
    wireName: "swap_config",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfig_SwapConfigFields,
  },
};

const Cluster_NodeConfig_LocalNvmeSsdBlockConfigFields: FieldMap = {
  localSsdCount: "local_ssd_count",
};

const Cluster_NodeConfig_NodeImageConfigFields: FieldMap = {
  image: "image",
  imageProject: "image_project",
};

const Cluster_NodeConfig_ReservationAffinityFields: FieldMap = {
  consumeReservationType: "consume_reservation_type",
  key: "key",
  values: "values",
};

const Cluster_NodeConfig_SandboxConfigFields: FieldMap = {
  type: "type",
};

const Cluster_NodeConfig_SecondaryBootDisksFields: FieldMap = {
  diskImage: "disk_image",
  mode: "mode",
};

const Cluster_NodeConfig_SoleTenantConfig_NodeAffinityFields: FieldMap = {
  key: "key",
  operator: "operator",
  values: "values",
};

const Cluster_NodeConfig_SoleTenantConfigFields: FieldMap = {
  minNodeCpus: "min_node_cpus",
  nodeAffinity: {
    wireName: "node_affinity",
    kind: "set",
    fields: Cluster_NodeConfig_SoleTenantConfig_NodeAffinityFields,
  },
};

const Cluster_NodeConfig_TaintConfigFields: FieldMap = {
  architectureTaintBehavior: "architecture_taint_behavior",
};

const Cluster_NodeConfig_WindowsNodeConfigFields: FieldMap = {
  osversion: "osversion",
};

const Cluster_NodeConfigFields: FieldMap = {
  bootDiskKmsKey: "boot_disk_kms_key",
  diskSizeGb: "disk_size_gb",
  diskType: "disk_type",
  effectiveTaints: {
    wireName: "effective_taints",
    kind: "list",
    fields: Cluster_NodeConfig_EffectiveTaintsFields,
  },
  enableConfidentialStorage: "enable_confidential_storage",
  flexStart: "flex_start",
  gpudirectStrategy: "gpudirect_strategy",
  imageType: "image_type",
  labels: "labels",
  localSsdCount: "local_ssd_count",
  localSsdEncryptionMode: "local_ssd_encryption_mode",
  loggingVariant: "logging_variant",
  machineType: "machine_type",
  maxRunDuration: "max_run_duration",
  metadata: "metadata",
  minCpuPlatform: "min_cpu_platform",
  nodeGroup: "node_group",
  oauthScopes: "oauth_scopes",
  preemptible: "preemptible",
  resourceLabels: "resource_labels",
  resourceManagerTags: "resource_manager_tags",
  serviceAccount: "service_account",
  spot: "spot",
  storagePools: "storage_pools",
  tags: "tags",
  advancedMachineFeatures: {
    wireName: "advanced_machine_features",
    kind: "list",
    fields: Cluster_NodeConfig_AdvancedMachineFeaturesFields,
  },
  bootDisk: {
    wireName: "boot_disk",
    kind: "list",
    fields: Cluster_NodeConfig_BootDiskFields,
  },
  confidentialNodes: {
    wireName: "confidential_nodes",
    kind: "list",
    fields: Cluster_ConfidentialNodesFields,
  },
  containerdConfig: {
    wireName: "containerd_config",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfigFields,
  },
  ephemeralStorageLocalSsdConfig: {
    wireName: "ephemeral_storage_local_ssd_config",
    kind: "list",
    fields: Cluster_NodeConfig_EphemeralStorageLocalSsdConfigFields,
  },
  fastSocket: {
    wireName: "fast_socket",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  gcfsConfig: {
    wireName: "gcfs_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  guestAccelerator: {
    wireName: "guest_accelerator",
    kind: "list",
    fields: Cluster_NodeConfig_GuestAcceleratorFields,
  },
  gvnic: {
    wireName: "gvnic",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  hostMaintenancePolicy: {
    wireName: "host_maintenance_policy",
    kind: "list",
    fields: Cluster_NodeConfig_HostMaintenancePolicyFields,
  },
  kubeletConfig: {
    wireName: "kubelet_config",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfigFields,
  },
  linuxNodeConfig: {
    wireName: "linux_node_config",
    kind: "list",
    fields: Cluster_NodeConfig_LinuxNodeConfigFields,
  },
  localNvmeSsdBlockConfig: {
    wireName: "local_nvme_ssd_block_config",
    kind: "list",
    fields: Cluster_NodeConfig_LocalNvmeSsdBlockConfigFields,
  },
  nodeImageConfig: {
    wireName: "node_image_config",
    kind: "list",
    fields: Cluster_NodeConfig_NodeImageConfigFields,
  },
  reservationAffinity: {
    wireName: "reservation_affinity",
    kind: "list",
    fields: Cluster_NodeConfig_ReservationAffinityFields,
  },
  sandboxConfig: {
    wireName: "sandbox_config",
    kind: "list",
    fields: Cluster_NodeConfig_SandboxConfigFields,
  },
  secondaryBootDisks: {
    wireName: "secondary_boot_disks",
    kind: "list",
    fields: Cluster_NodeConfig_SecondaryBootDisksFields,
  },
  shieldedInstanceConfig: {
    wireName: "shielded_instance_config",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_ShieldedInstanceConfigFields,
  },
  soleTenantConfig: {
    wireName: "sole_tenant_config",
    kind: "list",
    fields: Cluster_NodeConfig_SoleTenantConfigFields,
  },
  taint: {
    wireName: "taint",
    kind: "list",
    fields: Cluster_NodeConfig_EffectiveTaintsFields,
  },
  taintConfig: {
    wireName: "taint_config",
    kind: "list",
    fields: Cluster_NodeConfig_TaintConfigFields,
  },
  windowsNodeConfig: {
    wireName: "windows_node_config",
    kind: "list",
    fields: Cluster_NodeConfig_WindowsNodeConfigFields,
  },
  workloadMetadataConfig: {
    wireName: "workload_metadata_config",
    kind: "list",
    fields: Cluster_AnonymousAuthenticationConfigFields,
  },
};

const Cluster_NodeCreationConfigFields: FieldMap = {
  nodeCreationMode: "node_creation_mode",
};

const Cluster_NodePool_AutoscalingFields: FieldMap = {
  locationPolicy: "location_policy",
  maxNodeCount: "max_node_count",
  minNodeCount: "min_node_count",
  totalMaxNodeCount: "total_max_node_count",
  totalMinNodeCount: "total_min_node_count",
};

const Cluster_NodePool_MaintenancePolicy_ExclusionUntilEndOfSupportFields: FieldMap = {
  enabled: "enabled",
  endTime: "end_time",
  startTime: "start_time",
};

const Cluster_NodePool_MaintenancePolicyFields: FieldMap = {
  exclusionUntilEndOfSupport: {
    wireName: "exclusion_until_end_of_support",
    kind: "list",
    fields: Cluster_NodePool_MaintenancePolicy_ExclusionUntilEndOfSupportFields,
  },
};

const Cluster_NodePool_ManagementFields: FieldMap = {
  autoRepair: "auto_repair",
  autoUpgrade: "auto_upgrade",
};

const Cluster_NodePool_NetworkConfig_AdditionalNodeNetworkConfigsFields: FieldMap = {
  network: "network",
  subnetwork: "subnetwork",
};

const Cluster_NodePool_NetworkConfig_AdditionalPodNetworkConfigsFields: FieldMap = {
  maxPodsPerNode: "max_pods_per_node",
  secondaryPodRange: "secondary_pod_range",
  subnetwork: "subnetwork",
};

const Cluster_NodePool_NetworkConfigFields: FieldMap = {
  acceleratorNetworkProfile: "accelerator_network_profile",
  createPodRange: "create_pod_range",
  enablePrivateNodes: "enable_private_nodes",
  podIpv4CidrBlock: "pod_ipv4_cidr_block",
  podRange: "pod_range",
  subnetwork: "subnetwork",
  additionalNodeNetworkConfigs: {
    wireName: "additional_node_network_configs",
    kind: "list",
    fields: Cluster_NodePool_NetworkConfig_AdditionalNodeNetworkConfigsFields,
  },
  additionalPodNetworkConfigs: {
    wireName: "additional_pod_network_configs",
    kind: "list",
    fields: Cluster_NodePool_NetworkConfig_AdditionalPodNetworkConfigsFields,
  },
  networkPerformanceConfig: {
    wireName: "network_performance_config",
    kind: "list",
    fields: Cluster_NetworkPerformanceConfigFields,
  },
  podCidrOverprovisionConfig: {
    wireName: "pod_cidr_overprovision_config",
    kind: "list",
    fields: Cluster_AddonsConfig_HorizontalPodAutoscalingFields,
  },
};

const Cluster_NodePool_NodeDrainConfigFields: FieldMap = {
  graceTerminationDuration: "grace_termination_duration",
  pdbTimeoutDuration: "pdb_timeout_duration",
  respectPdbDuringNodePoolDeletion: "respect_pdb_during_node_pool_deletion",
};

const Cluster_NodePool_PlacementPolicyFields: FieldMap = {
  policyName: "policy_name",
  tpuTopology: "tpu_topology",
  type: "type",
};

const Cluster_NodePoolFields: FieldMap = {
  ignoreNodeCountChanges: "ignore_node_count_changes",
  initialNodeCount: "initial_node_count",
  instanceGroupUrls: "instance_group_urls",
  managedInstanceGroupUrls: "managed_instance_group_urls",
  maxPodsPerNode: "max_pods_per_node",
  name: "name",
  namePrefix: "name_prefix",
  nodeCount: "node_count",
  nodeLocations: "node_locations",
  version: "version",
  autoscaling: {
    wireName: "autoscaling",
    kind: "list",
    fields: Cluster_NodePool_AutoscalingFields,
  },
  maintenancePolicy: {
    wireName: "maintenance_policy",
    kind: "list",
    fields: Cluster_NodePool_MaintenancePolicyFields,
  },
  management: {
    wireName: "management",
    kind: "list",
    fields: Cluster_NodePool_ManagementFields,
  },
  networkConfig: {
    wireName: "network_config",
    kind: "list",
    fields: Cluster_NodePool_NetworkConfigFields,
  },
  nodeConfig: {
    wireName: "node_config",
    kind: "list",
    fields: Cluster_NodeConfigFields,
  },
  nodeDrainConfig: {
    wireName: "node_drain_config",
    kind: "list",
    fields: Cluster_NodePool_NodeDrainConfigFields,
  },
  placementPolicy: {
    wireName: "placement_policy",
    kind: "list",
    fields: Cluster_NodePool_PlacementPolicyFields,
  },
  queuedProvisioning: {
    wireName: "queued_provisioning",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
  upgradeSettings: {
    wireName: "upgrade_settings",
    kind: "list",
    fields: Cluster_ClusterAutoscaling_AutoProvisioningDefaults_UpgradeSettingsFields,
  },
};

const Cluster_NodePoolAutoConfig_LinuxNodeConfigFields: FieldMap = {
  cgroupMode: "cgroup_mode",
  nodeKernelModuleLoading: {
    wireName: "node_kernel_module_loading",
    kind: "list",
    fields: Cluster_NodeConfig_KubeletConfig_MemoryManagerFields,
  },
};

const Cluster_NodePoolAutoConfig_NetworkTagsFields: FieldMap = {
  tags: "tags",
};

const Cluster_NodePoolAutoConfig_NodeKubeletConfigFields: FieldMap = {
  insecureKubeletReadonlyPortEnabled: "insecure_kubelet_readonly_port_enabled",
};

const Cluster_NodePoolAutoConfigFields: FieldMap = {
  resourceManagerTags: "resource_manager_tags",
  linuxNodeConfig: {
    wireName: "linux_node_config",
    kind: "list",
    fields: Cluster_NodePoolAutoConfig_LinuxNodeConfigFields,
  },
  networkTags: {
    wireName: "network_tags",
    kind: "list",
    fields: Cluster_NodePoolAutoConfig_NetworkTagsFields,
  },
  nodeKubeletConfig: {
    wireName: "node_kubelet_config",
    kind: "list",
    fields: Cluster_NodePoolAutoConfig_NodeKubeletConfigFields,
  },
};

const Cluster_NodePoolDefaults_NodeConfigDefaultsFields: FieldMap = {
  insecureKubeletReadonlyPortEnabled: "insecure_kubelet_readonly_port_enabled",
  loggingVariant: "logging_variant",
  containerdConfig: {
    wireName: "containerd_config",
    kind: "list",
    fields: Cluster_NodeConfig_ContainerdConfigFields,
  },
  gcfsConfig: {
    wireName: "gcfs_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
};

const Cluster_NodePoolDefaultsFields: FieldMap = {
  nodeConfigDefaults: {
    wireName: "node_config_defaults",
    kind: "list",
    fields: Cluster_NodePoolDefaults_NodeConfigDefaultsFields,
  },
};

const Cluster_NotificationConfig_Pubsub_FilterFields: FieldMap = {
  eventType: "event_type",
};

const Cluster_NotificationConfig_PubsubFields: FieldMap = {
  enabled: "enabled",
  topic: "topic",
  filter: {
    wireName: "filter",
    kind: "list",
    fields: Cluster_NotificationConfig_Pubsub_FilterFields,
  },
};

const Cluster_NotificationConfigFields: FieldMap = {
  pubsub: {
    wireName: "pubsub",
    kind: "list",
    fields: Cluster_NotificationConfig_PubsubFields,
  },
};

const Cluster_PodAutoscalingFields: FieldMap = {
  hpaProfile: "hpa_profile",
};

const Cluster_PrivateClusterConfigFields: FieldMap = {
  enablePrivateEndpoint: "enable_private_endpoint",
  enablePrivateNodes: "enable_private_nodes",
  masterIpv4CidrBlock: "master_ipv4_cidr_block",
  peeringName: "peering_name",
  privateEndpoint: "private_endpoint",
  privateEndpointSubnetwork: "private_endpoint_subnetwork",
  publicEndpoint: "public_endpoint",
  masterGlobalAccessConfig: {
    wireName: "master_global_access_config",
    kind: "list",
    fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
  },
};

const Cluster_RbacBindingConfigFields: FieldMap = {
  enableInsecureBindingSystemAuthenticated: "enable_insecure_binding_system_authenticated",
  enableInsecureBindingSystemUnauthenticated: "enable_insecure_binding_system_unauthenticated",
};

const Cluster_ResourceUsageExportConfig_BigqueryDestinationFields: FieldMap = {
  datasetId: "dataset_id",
};

const Cluster_ResourceUsageExportConfigFields: FieldMap = {
  enableNetworkEgressMetering: "enable_network_egress_metering",
  enableResourceConsumptionMetering: "enable_resource_consumption_metering",
  bigqueryDestination: {
    wireName: "bigquery_destination",
    kind: "list",
    fields: Cluster_ResourceUsageExportConfig_BigqueryDestinationFields,
  },
};

const Cluster_RollbackSafeUpgradeFields: FieldMap = {
  controlPlaneSoakDuration: "control_plane_soak_duration",
};

const Cluster_SecretManagerConfig_RotationConfigFields: FieldMap = {
  enabled: "enabled",
  rotationInterval: "rotation_interval",
};

const Cluster_SecretManagerConfigFields: FieldMap = {
  enabled: "enabled",
  rotationConfig: {
    wireName: "rotation_config",
    kind: "list",
    fields: Cluster_SecretManagerConfig_RotationConfigFields,
  },
};

const Cluster_SecurityPostureConfigFields: FieldMap = {
  mode: "mode",
  vulnerabilityMode: "vulnerability_mode",
};

const Cluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  read: "read",
  update: "update",
};

const Cluster_UserManagedKeysConfigFields: FieldMap = {
  aggregationCa: "aggregation_ca",
  clusterCa: "cluster_ca",
  controlPlaneDiskEncryptionKey: "control_plane_disk_encryption_key",
  controlPlaneDiskEncryptionKeyVersions: "control_plane_disk_encryption_key_versions",
  etcdApiCa: "etcd_api_ca",
  etcdPeerCa: "etcd_peer_ca",
  gkeopsEtcdBackupEncryptionKey: "gkeops_etcd_backup_encryption_key",
  serviceAccountSigningKeys: "service_account_signing_keys",
  serviceAccountVerificationKeys: "service_account_verification_keys",
};

const Cluster_WorkloadIdentityConfigFields: FieldMap = {
  workloadPool: "workload_pool",
};

export interface ClusterConfig {
  allowNetAdmin?: boolean | Computed<boolean>;
  autopilotPrivilegedAdmission?: string[] | Computed<string[]>;
  clusterIpv4Cidr?: string | Computed<string>;
  datapathProvider?: string | Computed<string>;
  dataplaneOptimizationMode?: string | Computed<string>;
  defaultMaxPodsPerNode?: number | Computed<number>;
  deletionPolicy?: string | Computed<string>;
  deletionProtection?: boolean | Computed<boolean>;
  description?: string | Computed<string>;
  desiredEmulatedVersion?: string | Computed<string>;
  disableL4LbFirewallReconciliation?: boolean | Computed<boolean>;
  enableAutopilot?: boolean | Computed<boolean>;
  enableCiliumClusterwideNetworkPolicy?: boolean | Computed<boolean>;
  enableFqdnNetworkPolicy?: boolean | Computed<boolean>;
  enableIntranodeVisibility?: boolean | Computed<boolean>;
  enableKubernetesAlpha?: boolean | Computed<boolean>;
  enableL4IlbSubsetting?: boolean | Computed<boolean>;
  enableLegacyAbac?: boolean | Computed<boolean>;
  enableMultiNetworking?: boolean | Computed<boolean>;
  enableShieldedNodes?: boolean | Computed<boolean>;
  enableTpu?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  ignoreNodeCountChanges?: boolean | Computed<boolean>;
  inTransitEncryptionConfig?: string | Computed<string>;
  initialNodeCount?: number | Computed<number>;
  location?: string | Computed<string>;
  loggingService?: string | Computed<string>;
  minMasterVersion?: string | Computed<string>;
  monitoringService?: string | Computed<string>;
  name: string | Computed<string>;
  network?: string | Computed<string>;
  networkingMode?: string | Computed<string>;
  nodeLocations?: string[] | Computed<string[]>;
  nodeVersion?: string | Computed<string>;
  privateIpv6GoogleAccess?: string | Computed<string>;
  project?: string | Computed<string>;
  removeDefaultNodePool?: boolean | Computed<boolean>;
  resourceLabels?: Record<string, string> | Computed<Record<string, string>>;
  skipNodePoolRefresh?: boolean | Computed<boolean>;
  subnetwork?: string | Computed<string>;
  addonsConfig?: Cluster_AddonsConfig[] | Computed<Cluster_AddonsConfig[]>;
  anonymousAuthenticationConfig?: Cluster_AnonymousAuthenticationConfig[] | Computed<Cluster_AnonymousAuthenticationConfig[]>;
  authenticatorGroupsConfig?: Cluster_AuthenticatorGroupsConfig[] | Computed<Cluster_AuthenticatorGroupsConfig[]>;
  autopilotClusterPolicyConfig?: Cluster_AutopilotClusterPolicyConfig[] | Computed<Cluster_AutopilotClusterPolicyConfig[]>;
  binaryAuthorization?: Cluster_BinaryAuthorization[] | Computed<Cluster_BinaryAuthorization[]>;
  clusterAutoscaling?: Cluster_ClusterAutoscaling[] | Computed<Cluster_ClusterAutoscaling[]>;
  confidentialNodes?: Cluster_ConfidentialNodes[] | Computed<Cluster_ConfidentialNodes[]>;
  controlPlaneEndpointsConfig?: Cluster_ControlPlaneEndpointsConfig[] | Computed<Cluster_ControlPlaneEndpointsConfig[]>;
  costManagementConfig?: Cluster_AddonsConfig_AgentSandboxConfig[] | Computed<Cluster_AddonsConfig_AgentSandboxConfig[]>;
  databaseEncryption?: Cluster_DatabaseEncryption[] | Computed<Cluster_DatabaseEncryption[]>;
  defaultSnatStatus?: Cluster_AddonsConfig_HorizontalPodAutoscaling[] | Computed<Cluster_AddonsConfig_HorizontalPodAutoscaling[]>;
  dnsConfig?: Cluster_DnsConfig[] | Computed<Cluster_DnsConfig[]>;
  enableK8sBetaApis?: Cluster_EnableK8sBetaApis[] | Computed<Cluster_EnableK8sBetaApis[]>;
  enterpriseConfig?: Cluster_EnterpriseConfig[] | Computed<Cluster_EnterpriseConfig[]>;
  fleet?: Cluster_Fleet[] | Computed<Cluster_Fleet[]>;
  gatewayApiConfig?: Cluster_GatewayApiConfig[] | Computed<Cluster_GatewayApiConfig[]>;
  gkeAutoUpgradeConfig?: Cluster_GkeAutoUpgradeConfig[] | Computed<Cluster_GkeAutoUpgradeConfig[]>;
  identityServiceConfig?: Cluster_AddonsConfig_AgentSandboxConfig[] | Computed<Cluster_AddonsConfig_AgentSandboxConfig[]>;
  ipAllocationPolicy?: Cluster_IpAllocationPolicy[] | Computed<Cluster_IpAllocationPolicy[]>;
  loggingConfig?: Cluster_LoggingConfig[] | Computed<Cluster_LoggingConfig[]>;
  maintenancePolicy?: Cluster_MaintenancePolicy[] | Computed<Cluster_MaintenancePolicy[]>;
  masterAuth?: Cluster_MasterAuth[] | Computed<Cluster_MasterAuth[]>;
  masterAuthorizedNetworksConfig?: Cluster_MasterAuthorizedNetworksConfig[] | Computed<Cluster_MasterAuthorizedNetworksConfig[]>;
  meshCertificates?: Cluster_MeshCertificates[] | Computed<Cluster_MeshCertificates[]>;
  monitoringConfig?: Cluster_MonitoringConfig[] | Computed<Cluster_MonitoringConfig[]>;
  networkPerformanceConfig?: Cluster_NetworkPerformanceConfig[] | Computed<Cluster_NetworkPerformanceConfig[]>;
  networkPolicy?: Cluster_NetworkPolicy[] | Computed<Cluster_NetworkPolicy[]>;
  nodeConfig?: Cluster_NodeConfig[] | Computed<Cluster_NodeConfig[]>;
  nodeCreationConfig?: Cluster_NodeCreationConfig[] | Computed<Cluster_NodeCreationConfig[]>;
  nodePool?: Cluster_NodePool[] | Computed<Cluster_NodePool[]>;
  nodePoolAutoConfig?: Cluster_NodePoolAutoConfig[] | Computed<Cluster_NodePoolAutoConfig[]>;
  nodePoolDefaults?: Cluster_NodePoolDefaults[] | Computed<Cluster_NodePoolDefaults[]>;
  notificationConfig?: Cluster_NotificationConfig[] | Computed<Cluster_NotificationConfig[]>;
  podAutoscaling?: Cluster_PodAutoscaling[] | Computed<Cluster_PodAutoscaling[]>;
  privateClusterConfig?: Cluster_PrivateClusterConfig[] | Computed<Cluster_PrivateClusterConfig[]>;
  rbacBindingConfig?: Cluster_RbacBindingConfig[] | Computed<Cluster_RbacBindingConfig[]>;
  releaseChannel?: Cluster_GatewayApiConfig[] | Computed<Cluster_GatewayApiConfig[]>;
  resourceUsageExportConfig?: Cluster_ResourceUsageExportConfig[] | Computed<Cluster_ResourceUsageExportConfig[]>;
  rollbackSafeUpgrade?: Cluster_RollbackSafeUpgrade[] | Computed<Cluster_RollbackSafeUpgrade[]>;
  secretManagerConfig?: Cluster_SecretManagerConfig[] | Computed<Cluster_SecretManagerConfig[]>;
  secretSyncConfig?: Cluster_SecretManagerConfig[] | Computed<Cluster_SecretManagerConfig[]>;
  securityPostureConfig?: Cluster_SecurityPostureConfig[] | Computed<Cluster_SecurityPostureConfig[]>;
  serviceExternalIpsConfig?: Cluster_AddonsConfig_AgentSandboxConfig[] | Computed<Cluster_AddonsConfig_AgentSandboxConfig[]>;
  timeouts?: Cluster_Timeouts | Computed<Cluster_Timeouts>;
  userManagedKeysConfig?: Cluster_UserManagedKeysConfig[] | Computed<Cluster_UserManagedKeysConfig[]>;
  verticalPodAutoscaling?: Cluster_AddonsConfig_AgentSandboxConfig[] | Computed<Cluster_AddonsConfig_AgentSandboxConfig[]>;
  workloadIdentityConfig?: Cluster_WorkloadIdentityConfig[] | Computed<Cluster_WorkloadIdentityConfig[]>;
}

export interface ClusterAttrs {
  allowNetAdmin: boolean;
  autopilotPrivilegedAdmission: string[];
  clusterIpv4Cidr: string;
  datapathProvider: string;
  dataplaneOptimizationMode: string;
  defaultMaxPodsPerNode: number;
  deletionPolicy: string;
  deletionProtection: boolean;
  description: string;
  desiredEmulatedVersion: string;
  disableL4LbFirewallReconciliation: boolean;
  effectiveLabels: Record<string, string>;
  emulatedVersion: string;
  enableAutopilot: boolean;
  enableCiliumClusterwideNetworkPolicy: boolean;
  enableFqdnNetworkPolicy: boolean;
  enableIntranodeVisibility: boolean;
  enableKubernetesAlpha: boolean;
  enableL4IlbSubsetting: boolean;
  enableLegacyAbac: boolean;
  enableMultiNetworking: boolean;
  enableShieldedNodes: boolean;
  enableTpu: boolean;
  endpoint: string;
  id: string;
  ignoreNodeCountChanges: boolean;
  inTransitEncryptionConfig: string;
  initialNodeCount: number;
  labelFingerprint: string;
  location: string;
  loggingService: string;
  masterVersion: string;
  minMasterVersion: string;
  monitoringService: string;
  name: string;
  network: string;
  networkingMode: string;
  nodeLocations: string[];
  nodeVersion: string;
  operation: string;
  privateIpv6GoogleAccess: string;
  project: string;
  removeDefaultNodePool: boolean;
  resourceLabels: Record<string, string>;
  selfLink: string;
  servicesIpv4Cidr: string;
  skipNodePoolRefresh: boolean;
  subnetwork: string;
  terraformLabels: Record<string, string>;
  tpuIpv4CidrBlock: string;
  addonsConfig: Cluster_AddonsConfig[];
  anonymousAuthenticationConfig: Cluster_AnonymousAuthenticationConfig[];
  authenticatorGroupsConfig: Cluster_AuthenticatorGroupsConfig[];
  autopilotClusterPolicyConfig: Cluster_AutopilotClusterPolicyConfig[];
  binaryAuthorization: Cluster_BinaryAuthorization[];
  clusterAutoscaling: Cluster_ClusterAutoscaling[];
  confidentialNodes: Cluster_ConfidentialNodes[];
  controlPlaneEndpointsConfig: Cluster_ControlPlaneEndpointsConfig[];
  costManagementConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  databaseEncryption: Cluster_DatabaseEncryption[];
  defaultSnatStatus: Cluster_AddonsConfig_HorizontalPodAutoscaling[];
  dnsConfig: Cluster_DnsConfig[];
  enableK8sBetaApis: Cluster_EnableK8sBetaApis[];
  enterpriseConfig: Cluster_EnterpriseConfig[];
  fleet: Cluster_Fleet[];
  gatewayApiConfig: Cluster_GatewayApiConfig[];
  gkeAutoUpgradeConfig: Cluster_GkeAutoUpgradeConfig[];
  identityServiceConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  ipAllocationPolicy: Cluster_IpAllocationPolicy[];
  loggingConfig: Cluster_LoggingConfig[];
  maintenancePolicy: Cluster_MaintenancePolicy[];
  masterAuth: Cluster_MasterAuth[];
  masterAuthorizedNetworksConfig: Cluster_MasterAuthorizedNetworksConfig[];
  meshCertificates: Cluster_MeshCertificates[];
  monitoringConfig: Cluster_MonitoringConfig[];
  networkPerformanceConfig: Cluster_NetworkPerformanceConfig[];
  networkPolicy: Cluster_NetworkPolicy[];
  nodeConfig: Cluster_NodeConfig[];
  nodeCreationConfig: Cluster_NodeCreationConfig[];
  nodePool: Cluster_NodePool[];
  nodePoolAutoConfig: Cluster_NodePoolAutoConfig[];
  nodePoolDefaults: Cluster_NodePoolDefaults[];
  notificationConfig: Cluster_NotificationConfig[];
  podAutoscaling: Cluster_PodAutoscaling[];
  privateClusterConfig: Cluster_PrivateClusterConfig[];
  rbacBindingConfig: Cluster_RbacBindingConfig[];
  releaseChannel: Cluster_GatewayApiConfig[];
  resourceUsageExportConfig: Cluster_ResourceUsageExportConfig[];
  rollbackSafeUpgrade: Cluster_RollbackSafeUpgrade[];
  secretManagerConfig: Cluster_SecretManagerConfig[];
  secretSyncConfig: Cluster_SecretManagerConfig[];
  securityPostureConfig: Cluster_SecurityPostureConfig[];
  serviceExternalIpsConfig: Cluster_AddonsConfig_AgentSandboxConfig[];
  timeouts: Cluster_Timeouts;
  userManagedKeysConfig: Cluster_UserManagedKeysConfig[];
  verticalPodAutoscaling: Cluster_AddonsConfig_AgentSandboxConfig[];
  workloadIdentityConfig: Cluster_WorkloadIdentityConfig[];
}

export const Cluster: ResourceBinding<ClusterConfig, ClusterAttrs> = {
  wireType: "google_container_cluster",
  fields: {
    allowNetAdmin: "allow_net_admin",
    autopilotPrivilegedAdmission: "autopilot_privileged_admission",
    clusterIpv4Cidr: "cluster_ipv4_cidr",
    datapathProvider: "datapath_provider",
    dataplaneOptimizationMode: "dataplane_optimization_mode",
    defaultMaxPodsPerNode: "default_max_pods_per_node",
    deletionPolicy: "deletion_policy",
    deletionProtection: "deletion_protection",
    description: "description",
    desiredEmulatedVersion: "desired_emulated_version",
    disableL4LbFirewallReconciliation: "disable_l4_lb_firewall_reconciliation",
    enableAutopilot: "enable_autopilot",
    enableCiliumClusterwideNetworkPolicy: "enable_cilium_clusterwide_network_policy",
    enableFqdnNetworkPolicy: "enable_fqdn_network_policy",
    enableIntranodeVisibility: "enable_intranode_visibility",
    enableKubernetesAlpha: "enable_kubernetes_alpha",
    enableL4IlbSubsetting: "enable_l4_ilb_subsetting",
    enableLegacyAbac: "enable_legacy_abac",
    enableMultiNetworking: "enable_multi_networking",
    enableShieldedNodes: "enable_shielded_nodes",
    enableTpu: "enable_tpu",
    id: "id",
    ignoreNodeCountChanges: "ignore_node_count_changes",
    inTransitEncryptionConfig: "in_transit_encryption_config",
    initialNodeCount: "initial_node_count",
    location: "location",
    loggingService: "logging_service",
    minMasterVersion: "min_master_version",
    monitoringService: "monitoring_service",
    name: "name",
    network: "network",
    networkingMode: "networking_mode",
    nodeLocations: "node_locations",
    nodeVersion: "node_version",
    privateIpv6GoogleAccess: "private_ipv6_google_access",
    project: "project",
    removeDefaultNodePool: "remove_default_node_pool",
    resourceLabels: "resource_labels",
    skipNodePoolRefresh: "skip_node_pool_refresh",
    subnetwork: "subnetwork",
    addonsConfig: {
      wireName: "addons_config",
      kind: "list",
      fields: Cluster_AddonsConfigFields,
    },
    anonymousAuthenticationConfig: {
      wireName: "anonymous_authentication_config",
      kind: "list",
      fields: Cluster_AnonymousAuthenticationConfigFields,
    },
    authenticatorGroupsConfig: {
      wireName: "authenticator_groups_config",
      kind: "list",
      fields: Cluster_AuthenticatorGroupsConfigFields,
    },
    autopilotClusterPolicyConfig: {
      wireName: "autopilot_cluster_policy_config",
      kind: "list",
      fields: Cluster_AutopilotClusterPolicyConfigFields,
    },
    binaryAuthorization: {
      wireName: "binary_authorization",
      kind: "list",
      fields: Cluster_BinaryAuthorizationFields,
    },
    clusterAutoscaling: {
      wireName: "cluster_autoscaling",
      kind: "list",
      fields: Cluster_ClusterAutoscalingFields,
    },
    confidentialNodes: {
      wireName: "confidential_nodes",
      kind: "list",
      fields: Cluster_ConfidentialNodesFields,
    },
    controlPlaneEndpointsConfig: {
      wireName: "control_plane_endpoints_config",
      kind: "list",
      fields: Cluster_ControlPlaneEndpointsConfigFields,
    },
    costManagementConfig: {
      wireName: "cost_management_config",
      kind: "list",
      fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
    },
    databaseEncryption: {
      wireName: "database_encryption",
      kind: "list",
      fields: Cluster_DatabaseEncryptionFields,
    },
    defaultSnatStatus: {
      wireName: "default_snat_status",
      kind: "list",
      fields: Cluster_AddonsConfig_HorizontalPodAutoscalingFields,
    },
    dnsConfig: {
      wireName: "dns_config",
      kind: "list",
      fields: Cluster_DnsConfigFields,
    },
    enableK8sBetaApis: {
      wireName: "enable_k8s_beta_apis",
      kind: "list",
      fields: Cluster_EnableK8sBetaApisFields,
    },
    enterpriseConfig: {
      wireName: "enterprise_config",
      kind: "list",
      fields: Cluster_EnterpriseConfigFields,
    },
    fleet: {
      wireName: "fleet",
      kind: "list",
      fields: Cluster_FleetFields,
    },
    gatewayApiConfig: {
      wireName: "gateway_api_config",
      kind: "list",
      fields: Cluster_GatewayApiConfigFields,
    },
    gkeAutoUpgradeConfig: {
      wireName: "gke_auto_upgrade_config",
      kind: "list",
      fields: Cluster_GkeAutoUpgradeConfigFields,
    },
    identityServiceConfig: {
      wireName: "identity_service_config",
      kind: "list",
      fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
    },
    ipAllocationPolicy: {
      wireName: "ip_allocation_policy",
      kind: "list",
      fields: Cluster_IpAllocationPolicyFields,
    },
    loggingConfig: {
      wireName: "logging_config",
      kind: "list",
      fields: Cluster_LoggingConfigFields,
    },
    maintenancePolicy: {
      wireName: "maintenance_policy",
      kind: "list",
      fields: Cluster_MaintenancePolicyFields,
    },
    masterAuth: {
      wireName: "master_auth",
      kind: "list",
      fields: Cluster_MasterAuthFields,
    },
    masterAuthorizedNetworksConfig: {
      wireName: "master_authorized_networks_config",
      kind: "list",
      fields: Cluster_MasterAuthorizedNetworksConfigFields,
    },
    meshCertificates: {
      wireName: "mesh_certificates",
      kind: "list",
      fields: Cluster_MeshCertificatesFields,
    },
    monitoringConfig: {
      wireName: "monitoring_config",
      kind: "list",
      fields: Cluster_MonitoringConfigFields,
    },
    networkPerformanceConfig: {
      wireName: "network_performance_config",
      kind: "list",
      fields: Cluster_NetworkPerformanceConfigFields,
    },
    networkPolicy: {
      wireName: "network_policy",
      kind: "list",
      fields: Cluster_NetworkPolicyFields,
    },
    nodeConfig: {
      wireName: "node_config",
      kind: "list",
      fields: Cluster_NodeConfigFields,
    },
    nodeCreationConfig: {
      wireName: "node_creation_config",
      kind: "list",
      fields: Cluster_NodeCreationConfigFields,
    },
    nodePool: {
      wireName: "node_pool",
      kind: "list",
      fields: Cluster_NodePoolFields,
    },
    nodePoolAutoConfig: {
      wireName: "node_pool_auto_config",
      kind: "list",
      fields: Cluster_NodePoolAutoConfigFields,
    },
    nodePoolDefaults: {
      wireName: "node_pool_defaults",
      kind: "list",
      fields: Cluster_NodePoolDefaultsFields,
    },
    notificationConfig: {
      wireName: "notification_config",
      kind: "list",
      fields: Cluster_NotificationConfigFields,
    },
    podAutoscaling: {
      wireName: "pod_autoscaling",
      kind: "list",
      fields: Cluster_PodAutoscalingFields,
    },
    privateClusterConfig: {
      wireName: "private_cluster_config",
      kind: "list",
      fields: Cluster_PrivateClusterConfigFields,
    },
    rbacBindingConfig: {
      wireName: "rbac_binding_config",
      kind: "list",
      fields: Cluster_RbacBindingConfigFields,
    },
    releaseChannel: {
      wireName: "release_channel",
      kind: "list",
      fields: Cluster_GatewayApiConfigFields,
    },
    resourceUsageExportConfig: {
      wireName: "resource_usage_export_config",
      kind: "list",
      fields: Cluster_ResourceUsageExportConfigFields,
    },
    rollbackSafeUpgrade: {
      wireName: "rollback_safe_upgrade",
      kind: "list",
      fields: Cluster_RollbackSafeUpgradeFields,
    },
    secretManagerConfig: {
      wireName: "secret_manager_config",
      kind: "list",
      fields: Cluster_SecretManagerConfigFields,
    },
    secretSyncConfig: {
      wireName: "secret_sync_config",
      kind: "list",
      fields: Cluster_SecretManagerConfigFields,
    },
    securityPostureConfig: {
      wireName: "security_posture_config",
      kind: "list",
      fields: Cluster_SecurityPostureConfigFields,
    },
    serviceExternalIpsConfig: {
      wireName: "service_external_ips_config",
      kind: "list",
      fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Cluster_TimeoutsFields,
    },
    userManagedKeysConfig: {
      wireName: "user_managed_keys_config",
      kind: "list",
      fields: Cluster_UserManagedKeysConfigFields,
    },
    verticalPodAutoscaling: {
      wireName: "vertical_pod_autoscaling",
      kind: "list",
      fields: Cluster_AddonsConfig_AgentSandboxConfigFields,
    },
    workloadIdentityConfig: {
      wireName: "workload_identity_config",
      kind: "list",
      fields: Cluster_WorkloadIdentityConfigFields,
    },
  },
};
