// Code generated by `ubx sdk gen` from google_data_catalog_policy_tag_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CatalogPolicyTagIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const CatalogPolicyTagIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface CatalogPolicyTagIamBindingConfig {
  id?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  policyTag: string | Computed<string>;
  role: string | Computed<string>;
  condition?: CatalogPolicyTagIamBinding_Condition[] | Computed<CatalogPolicyTagIamBinding_Condition[]>;
}

export interface CatalogPolicyTagIamBindingAttrs {
  etag: string;
  id: string;
  members: string[];
  policyTag: string;
  role: string;
  condition: CatalogPolicyTagIamBinding_Condition[];
}

export const CatalogPolicyTagIamBinding: ResourceBinding<CatalogPolicyTagIamBindingConfig, CatalogPolicyTagIamBindingAttrs> = {
  wireType: "google_data_catalog_policy_tag_iam_binding",
  fields: {
    id: "id",
    members: "members",
    policyTag: "policy_tag",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: CatalogPolicyTagIamBinding_ConditionFields,
    },
  },
};
