// Code generated by `ubx sdk gen` from google_data_fusion_instance. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface FusionInstance_MaintenanceEvents {
  endTime: string;
  startTime: string;
  state: string;
}

export interface FusionInstance_Accelerators {
  acceleratorType: string;
  state: string;
}

export interface FusionInstance_CryptoKeyConfig {
  keyReference: string;
}

export interface FusionInstance_EventPublishConfig {
  enabled: boolean;
  topic: string;
}

export interface FusionInstance_MaintenancePolicy_MaintenanceWindow_RecurringTimeWindow_Window {
  endTime: string;
  startTime: string;
}

export interface FusionInstance_MaintenancePolicy_MaintenanceWindow_RecurringTimeWindow {
  recurrence: string;
  window: FusionInstance_MaintenancePolicy_MaintenanceWindow_RecurringTimeWindow_Window[];
}

export interface FusionInstance_MaintenancePolicy_MaintenanceWindow {
  recurringTimeWindow: FusionInstance_MaintenancePolicy_MaintenanceWindow_RecurringTimeWindow[];
}

export interface FusionInstance_MaintenancePolicy {
  maintenanceWindow: FusionInstance_MaintenancePolicy_MaintenanceWindow[];
}

export interface FusionInstance_NetworkConfig_PrivateServiceConnectConfig {
  effectiveUnreachableCidrBlock: string;
  networkAttachment: string;
  unreachableCidrBlock: string;
}

export interface FusionInstance_NetworkConfig {
  connectionType: string;
  ipAllocation: string;
  network: string;
  privateServiceConnectConfig: FusionInstance_NetworkConfig_PrivateServiceConnectConfig[];
}

export interface FusionInstance_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const FusionInstance_AcceleratorsFields: FieldMap = {
  acceleratorType: "accelerator_type",
  state: "state",
};

const FusionInstance_CryptoKeyConfigFields: FieldMap = {
  keyReference: "key_reference",
};

const FusionInstance_EventPublishConfigFields: FieldMap = {
  enabled: "enabled",
  topic: "topic",
};

const FusionInstance_MaintenancePolicy_MaintenanceWindow_RecurringTimeWindow_WindowFields: FieldMap = {
  endTime: "end_time",
  startTime: "start_time",
};

const FusionInstance_MaintenancePolicy_MaintenanceWindow_RecurringTimeWindowFields: FieldMap = {
  recurrence: "recurrence",
  window: {
    wireName: "window",
    kind: "list",
    fields: FusionInstance_MaintenancePolicy_MaintenanceWindow_RecurringTimeWindow_WindowFields,
  },
};

const FusionInstance_MaintenancePolicy_MaintenanceWindowFields: FieldMap = {
  recurringTimeWindow: {
    wireName: "recurring_time_window",
    kind: "list",
    fields: FusionInstance_MaintenancePolicy_MaintenanceWindow_RecurringTimeWindowFields,
  },
};

const FusionInstance_MaintenancePolicyFields: FieldMap = {
  maintenanceWindow: {
    wireName: "maintenance_window",
    kind: "list",
    fields: FusionInstance_MaintenancePolicy_MaintenanceWindowFields,
  },
};

const FusionInstance_NetworkConfig_PrivateServiceConnectConfigFields: FieldMap = {
  effectiveUnreachableCidrBlock: "effective_unreachable_cidr_block",
  networkAttachment: "network_attachment",
  unreachableCidrBlock: "unreachable_cidr_block",
};

const FusionInstance_NetworkConfigFields: FieldMap = {
  connectionType: "connection_type",
  ipAllocation: "ip_allocation",
  network: "network",
  privateServiceConnectConfig: {
    wireName: "private_service_connect_config",
    kind: "list",
    fields: FusionInstance_NetworkConfig_PrivateServiceConnectConfigFields,
  },
};

const FusionInstance_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface FusionInstanceConfig {
  dataprocServiceAccount?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  enableRbac?: boolean | Computed<boolean>;
  enableStackdriverLogging?: boolean | Computed<boolean>;
  enableStackdriverMonitoring?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  name: string | Computed<string>;
  options?: Record<string, string> | Computed<Record<string, string>>;
  patchRevision?: string | Computed<string>;
  privateInstance?: boolean | Computed<boolean>;
  project?: string | Computed<string>;
  region?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  type: string | Computed<string>;
  version?: string | Computed<string>;
  zone?: string | Computed<string>;
  accelerators?: FusionInstance_Accelerators[] | Computed<FusionInstance_Accelerators[]>;
  cryptoKeyConfig?: FusionInstance_CryptoKeyConfig[] | Computed<FusionInstance_CryptoKeyConfig[]>;
  eventPublishConfig?: FusionInstance_EventPublishConfig[] | Computed<FusionInstance_EventPublishConfig[]>;
  maintenancePolicy?: FusionInstance_MaintenancePolicy[] | Computed<FusionInstance_MaintenancePolicy[]>;
  networkConfig?: FusionInstance_NetworkConfig[] | Computed<FusionInstance_NetworkConfig[]>;
  timeouts?: FusionInstance_Timeouts | Computed<FusionInstance_Timeouts>;
}

export interface FusionInstanceAttrs {
  apiEndpoint: string;
  createTime: string;
  dataprocServiceAccount: string;
  deletionPolicy: string;
  description: string;
  displayName: string;
  effectiveLabels: Record<string, string>;
  enableRbac: boolean;
  enableStackdriverLogging: boolean;
  enableStackdriverMonitoring: boolean;
  gcsBucket: string;
  id: string;
  labels: Record<string, string>;
  maintenanceEvents: FusionInstance_MaintenanceEvents[];
  name: string;
  options: Record<string, string>;
  p4ServiceAccount: string;
  patchRevision: string;
  privateInstance: boolean;
  project: string;
  region: string;
  serviceEndpoint: string;
  state: string;
  stateMessage: string;
  tags: Record<string, string>;
  tenantProjectId: string;
  terraformLabels: Record<string, string>;
  type: string;
  updateTime: string;
  version: string;
  zone: string;
  accelerators: FusionInstance_Accelerators[];
  cryptoKeyConfig: FusionInstance_CryptoKeyConfig[];
  eventPublishConfig: FusionInstance_EventPublishConfig[];
  maintenancePolicy: FusionInstance_MaintenancePolicy[];
  networkConfig: FusionInstance_NetworkConfig[];
  timeouts: FusionInstance_Timeouts;
}

export const FusionInstance: ResourceBinding<FusionInstanceConfig, FusionInstanceAttrs> = {
  wireType: "google_data_fusion_instance",
  fields: {
    dataprocServiceAccount: "dataproc_service_account",
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    enableRbac: "enable_rbac",
    enableStackdriverLogging: "enable_stackdriver_logging",
    enableStackdriverMonitoring: "enable_stackdriver_monitoring",
    id: "id",
    labels: "labels",
    name: "name",
    options: "options",
    patchRevision: "patch_revision",
    privateInstance: "private_instance",
    project: "project",
    region: "region",
    tags: "tags",
    type: "type",
    version: "version",
    zone: "zone",
    accelerators: {
      wireName: "accelerators",
      kind: "list",
      fields: FusionInstance_AcceleratorsFields,
    },
    cryptoKeyConfig: {
      wireName: "crypto_key_config",
      kind: "list",
      fields: FusionInstance_CryptoKeyConfigFields,
    },
    eventPublishConfig: {
      wireName: "event_publish_config",
      kind: "list",
      fields: FusionInstance_EventPublishConfigFields,
    },
    maintenancePolicy: {
      wireName: "maintenance_policy",
      kind: "list",
      fields: FusionInstance_MaintenancePolicyFields,
    },
    networkConfig: {
      wireName: "network_config",
      kind: "list",
      fields: FusionInstance_NetworkConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: FusionInstance_TimeoutsFields,
    },
  },
};
