// Code generated by `ubx sdk gen` from google_data_loss_prevention_inspect_template. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary_CloudStoragePath {
  path: string;
}

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary_WordList {
  words: string[];
}

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary {
  cloudStoragePath: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary_CloudStoragePath[];
  wordList: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary_WordList[];
}

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType_SensitivityScore {
  score: string;
}

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType {
  name: string;
  version: string;
  sensitivityScore: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType_SensitivityScore[];
}

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Regex {
  groupIndexes: number[];
  pattern: string;
}

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_StoredType {
  name: string;
}

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_SurrogateType {
}

export interface LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes {
  exclusionType: string;
  likelihood: string;
  dictionary: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary[];
  infoType: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType[];
  regex: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Regex[];
  sensitivityScore: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType_SensitivityScore[];
  storedType: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_StoredType[];
  surrogateType: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_SurrogateType[];
}

export interface LossPreventionInspectTemplate_InspectConfig_Limits_MaxFindingsPerInfoType {
  maxFindings: number;
  infoType: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType[];
}

export interface LossPreventionInspectTemplate_InspectConfig_Limits {
  maxFindingsPerItem: number;
  maxFindingsPerRequest: number;
  maxFindingsPerInfoType: LossPreventionInspectTemplate_InspectConfig_Limits_MaxFindingsPerInfoType[];
}

export interface LossPreventionInspectTemplate_InspectConfig_MinLikelihoodPerInfoType_InfoType {
  name: string;
  version: string;
}

export interface LossPreventionInspectTemplate_InspectConfig_MinLikelihoodPerInfoType {
  minLikelihood: string;
  infoType: LossPreventionInspectTemplate_InspectConfig_MinLikelihoodPerInfoType_InfoType[];
}

export interface LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotword_Proximity {
  windowAfter: number;
  windowBefore: number;
}

export interface LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotword {
  hotwordRegex: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Regex[];
  proximity: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotword_Proximity[];
}

export interface LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeInfoTypes {
  infoTypes: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType[];
}

export interface LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule {
  matchingType: string;
  dictionary: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary[];
  excludeByHotword: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotword[];
  excludeInfoTypes: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeInfoTypes[];
  regex: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Regex[];
}

export interface LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_HotwordRule_LikelihoodAdjustment {
  fixedLikelihood: string;
  relativeLikelihood: number;
}

export interface LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_HotwordRule {
  hotwordRegex: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Regex[];
  likelihoodAdjustment: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_HotwordRule_LikelihoodAdjustment[];
  proximity: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotword_Proximity[];
}

export interface LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules {
  exclusionRule: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule[];
  hotwordRule: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_HotwordRule[];
}

export interface LossPreventionInspectTemplate_InspectConfig_RuleSet {
  infoTypes: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType[];
  rules: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules[];
}

export interface LossPreventionInspectTemplate_InspectConfig {
  contentOptions: string[];
  excludeInfoTypes: boolean;
  includeQuote: boolean;
  minLikelihood: string;
  customInfoTypes: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes[];
  infoTypes: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType[];
  limits: LossPreventionInspectTemplate_InspectConfig_Limits[];
  minLikelihoodPerInfoType: LossPreventionInspectTemplate_InspectConfig_MinLikelihoodPerInfoType[];
  ruleSet: LossPreventionInspectTemplate_InspectConfig_RuleSet[];
}

export interface LossPreventionInspectTemplate_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary_CloudStoragePathFields: FieldMap = {
  path: "path",
};

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary_WordListFields: FieldMap = {
  words: "words",
};

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_DictionaryFields: FieldMap = {
  cloudStoragePath: {
    wireName: "cloud_storage_path",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary_CloudStoragePathFields,
  },
  wordList: {
    wireName: "word_list",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_Dictionary_WordListFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType_SensitivityScoreFields: FieldMap = {
  score: "score",
};

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoTypeFields: FieldMap = {
  name: "name",
  version: "version",
  sensitivityScore: {
    wireName: "sensitivity_score",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType_SensitivityScoreFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_RegexFields: FieldMap = {
  groupIndexes: "group_indexes",
  pattern: "pattern",
};

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_StoredTypeFields: FieldMap = {
  name: "name",
};

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_SurrogateTypeFields: FieldMap = {
};

const LossPreventionInspectTemplate_InspectConfig_CustomInfoTypesFields: FieldMap = {
  exclusionType: "exclusion_type",
  likelihood: "likelihood",
  dictionary: {
    wireName: "dictionary",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_DictionaryFields,
  },
  infoType: {
    wireName: "info_type",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoTypeFields,
  },
  regex: {
    wireName: "regex",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_RegexFields,
  },
  sensitivityScore: {
    wireName: "sensitivity_score",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoType_SensitivityScoreFields,
  },
  storedType: {
    wireName: "stored_type",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_StoredTypeFields,
  },
  surrogateType: {
    wireName: "surrogate_type",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_SurrogateTypeFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_Limits_MaxFindingsPerInfoTypeFields: FieldMap = {
  maxFindings: "max_findings",
  infoType: {
    wireName: "info_type",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoTypeFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_LimitsFields: FieldMap = {
  maxFindingsPerItem: "max_findings_per_item",
  maxFindingsPerRequest: "max_findings_per_request",
  maxFindingsPerInfoType: {
    wireName: "max_findings_per_info_type",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_Limits_MaxFindingsPerInfoTypeFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_MinLikelihoodPerInfoType_InfoTypeFields: FieldMap = {
  name: "name",
  version: "version",
};

const LossPreventionInspectTemplate_InspectConfig_MinLikelihoodPerInfoTypeFields: FieldMap = {
  minLikelihood: "min_likelihood",
  infoType: {
    wireName: "info_type",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_MinLikelihoodPerInfoType_InfoTypeFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotword_ProximityFields: FieldMap = {
  windowAfter: "window_after",
  windowBefore: "window_before",
};

const LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotwordFields: FieldMap = {
  hotwordRegex: {
    wireName: "hotword_regex",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_RegexFields,
  },
  proximity: {
    wireName: "proximity",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotword_ProximityFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeInfoTypesFields: FieldMap = {
  infoTypes: {
    wireName: "info_types",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoTypeFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRuleFields: FieldMap = {
  matchingType: "matching_type",
  dictionary: {
    wireName: "dictionary",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_DictionaryFields,
  },
  excludeByHotword: {
    wireName: "exclude_by_hotword",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotwordFields,
  },
  excludeInfoTypes: {
    wireName: "exclude_info_types",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeInfoTypesFields,
  },
  regex: {
    wireName: "regex",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_RegexFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_HotwordRule_LikelihoodAdjustmentFields: FieldMap = {
  fixedLikelihood: "fixed_likelihood",
  relativeLikelihood: "relative_likelihood",
};

const LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_HotwordRuleFields: FieldMap = {
  hotwordRegex: {
    wireName: "hotword_regex",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_RegexFields,
  },
  likelihoodAdjustment: {
    wireName: "likelihood_adjustment",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_HotwordRule_LikelihoodAdjustmentFields,
  },
  proximity: {
    wireName: "proximity",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRule_ExcludeByHotword_ProximityFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_RuleSet_RulesFields: FieldMap = {
  exclusionRule: {
    wireName: "exclusion_rule",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_ExclusionRuleFields,
  },
  hotwordRule: {
    wireName: "hotword_rule",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSet_Rules_HotwordRuleFields,
  },
};

const LossPreventionInspectTemplate_InspectConfig_RuleSetFields: FieldMap = {
  infoTypes: {
    wireName: "info_types",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoTypeFields,
  },
  rules: {
    wireName: "rules",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSet_RulesFields,
  },
};

const LossPreventionInspectTemplate_InspectConfigFields: FieldMap = {
  contentOptions: "content_options",
  excludeInfoTypes: "exclude_info_types",
  includeQuote: "include_quote",
  minLikelihood: "min_likelihood",
  customInfoTypes: {
    wireName: "custom_info_types",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypesFields,
  },
  infoTypes: {
    wireName: "info_types",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_CustomInfoTypes_InfoTypeFields,
  },
  limits: {
    wireName: "limits",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_LimitsFields,
  },
  minLikelihoodPerInfoType: {
    wireName: "min_likelihood_per_info_type",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_MinLikelihoodPerInfoTypeFields,
  },
  ruleSet: {
    wireName: "rule_set",
    kind: "list",
    fields: LossPreventionInspectTemplate_InspectConfig_RuleSetFields,
  },
};

const LossPreventionInspectTemplate_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface LossPreventionInspectTemplateConfig {
  allowLimitedAvailabilityInfoTypes?: boolean | Computed<boolean>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  parent: string | Computed<string>;
  templateId?: string | Computed<string>;
  inspectConfig?: LossPreventionInspectTemplate_InspectConfig[] | Computed<LossPreventionInspectTemplate_InspectConfig[]>;
  timeouts?: LossPreventionInspectTemplate_Timeouts | Computed<LossPreventionInspectTemplate_Timeouts>;
}

export interface LossPreventionInspectTemplateAttrs {
  allowLimitedAvailabilityInfoTypes: boolean;
  deletionPolicy: string;
  description: string;
  displayName: string;
  id: string;
  name: string;
  parent: string;
  templateId: string;
  inspectConfig: LossPreventionInspectTemplate_InspectConfig[];
  timeouts: LossPreventionInspectTemplate_Timeouts;
}

export const LossPreventionInspectTemplate: ResourceBinding<LossPreventionInspectTemplateConfig, LossPreventionInspectTemplateAttrs> = {
  wireType: "google_data_loss_prevention_inspect_template",
  fields: {
    allowLimitedAvailabilityInfoTypes: "allow_limited_availability_info_types",
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    id: "id",
    parent: "parent",
    templateId: "template_id",
    inspectConfig: {
      wireName: "inspect_config",
      kind: "list",
      fields: LossPreventionInspectTemplate_InspectConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: LossPreventionInspectTemplate_TimeoutsFields,
    },
  },
};
