// Code generated by `ubx sdk gen` from google_dataplex_aspect_type. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AspectType_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const AspectType_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface AspectTypeConfig {
  aspectTypeId?: string | Computed<string>;
  dataClassification?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location?: string | Computed<string>;
  metadataTemplate?: string | Computed<string>;
  project?: string | Computed<string>;
  timeouts?: AspectType_Timeouts | Computed<AspectType_Timeouts>;
}

export interface AspectTypeAttrs {
  aspectTypeId: string;
  createTime: string;
  dataClassification: string;
  deletionPolicy: string;
  description: string;
  displayName: string;
  effectiveLabels: Record<string, string>;
  id: string;
  labels: Record<string, string>;
  location: string;
  metadataTemplate: string;
  name: string;
  project: string;
  terraformLabels: Record<string, string>;
  transferStatus: string;
  uid: string;
  updateTime: string;
  timeouts: AspectType_Timeouts;
}

export const AspectType: ResourceBinding<AspectTypeConfig, AspectTypeAttrs> = {
  wireType: "google_dataplex_aspect_type",
  fields: {
    aspectTypeId: "aspect_type_id",
    dataClassification: "data_classification",
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    id: "id",
    labels: "labels",
    location: "location",
    metadataTemplate: "metadata_template",
    project: "project",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: AspectType_TimeoutsFields,
    },
  },
};
