// Code generated by `ubx sdk gen` from google_dataplex_aspect_type_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface AspectTypeIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const AspectTypeIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface AspectTypeIamBindingConfig {
  aspectTypeId: string | Computed<string>;
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  condition?: AspectTypeIamBinding_Condition[] | Computed<AspectTypeIamBinding_Condition[]>;
}

export interface AspectTypeIamBindingAttrs {
  aspectTypeId: string;
  etag: string;
  id: string;
  location: string;
  members: string[];
  project: string;
  role: string;
  condition: AspectTypeIamBinding_Condition[];
}

export const AspectTypeIamBinding: ResourceBinding<AspectTypeIamBindingConfig, AspectTypeIamBindingAttrs> = {
  wireType: "google_dataplex_aspect_type_iam_binding",
  fields: {
    aspectTypeId: "aspect_type_id",
    id: "id",
    location: "location",
    members: "members",
    project: "project",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: AspectTypeIamBinding_ConditionFields,
    },
  },
};
