// Code generated by `ubx sdk gen` from google_dataplex_data_product_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataProductIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const DataProductIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface DataProductIamBindingConfig {
  dataProductId: string | Computed<string>;
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  condition?: DataProductIamBinding_Condition[] | Computed<DataProductIamBinding_Condition[]>;
}

export interface DataProductIamBindingAttrs {
  dataProductId: string;
  etag: string;
  id: string;
  location: string;
  members: string[];
  project: string;
  role: string;
  condition: DataProductIamBinding_Condition[];
}

export const DataProductIamBinding: ResourceBinding<DataProductIamBindingConfig, DataProductIamBindingAttrs> = {
  wireType: "google_dataplex_data_product_iam_binding",
  fields: {
    dataProductId: "data_product_id",
    id: "id",
    location: "location",
    members: "members",
    project: "project",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: DataProductIamBinding_ConditionFields,
    },
  },
};
