// Code generated by `ubx sdk gen` from google_dataplex_data_product. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataProduct_AccessApprovalConfig {
  approverEmails: string[];
}

export interface DataProduct_AccessGroups_Principal {
  googleGroup: string;
  serviceAccount: string;
}

export interface DataProduct_AccessGroups {
  description: string;
  displayName: string;
  groupId: string;
  id: string;
  principal: DataProduct_AccessGroups_Principal[];
}

export interface DataProduct_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const DataProduct_AccessApprovalConfigFields: FieldMap = {
  approverEmails: "approver_emails",
};

const DataProduct_AccessGroups_PrincipalFields: FieldMap = {
  googleGroup: "google_group",
  serviceAccount: "service_account",
};

const DataProduct_AccessGroupsFields: FieldMap = {
  description: "description",
  displayName: "display_name",
  groupId: "group_id",
  id: "id",
  principal: {
    wireName: "principal",
    kind: "list",
    fields: DataProduct_AccessGroups_PrincipalFields,
  },
};

const DataProduct_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface DataProductConfig {
  dataProductId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName: string | Computed<string>;
  icon?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  ownerEmails: string[] | Computed<string[]>;
  project?: string | Computed<string>;
  accessApprovalConfig?: DataProduct_AccessApprovalConfig[] | Computed<DataProduct_AccessApprovalConfig[]>;
  accessGroups?: DataProduct_AccessGroups[] | Computed<DataProduct_AccessGroups[]>;
  timeouts?: DataProduct_Timeouts | Computed<DataProduct_Timeouts>;
}

export interface DataProductAttrs {
  assetCount: number;
  createTime: string;
  dataProductId: string;
  deletionPolicy: string;
  description: string;
  displayName: string;
  effectiveLabels: Record<string, string>;
  etag: string;
  icon: string;
  id: string;
  labels: Record<string, string>;
  location: string;
  name: string;
  ownerEmails: string[];
  project: string;
  terraformLabels: Record<string, string>;
  uid: string;
  updateTime: string;
  accessApprovalConfig: DataProduct_AccessApprovalConfig[];
  accessGroups: DataProduct_AccessGroups[];
  timeouts: DataProduct_Timeouts;
}

export const DataProduct: ResourceBinding<DataProductConfig, DataProductAttrs> = {
  wireType: "google_dataplex_data_product",
  fields: {
    dataProductId: "data_product_id",
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    icon: "icon",
    id: "id",
    labels: "labels",
    location: "location",
    ownerEmails: "owner_emails",
    project: "project",
    accessApprovalConfig: {
      wireName: "access_approval_config",
      kind: "list",
      fields: DataProduct_AccessApprovalConfigFields,
    },
    accessGroups: {
      wireName: "access_groups",
      kind: "set",
      fields: DataProduct_AccessGroupsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DataProduct_TimeoutsFields,
    },
  },
};
