// Code generated by `ubx sdk gen` from google_dataplex_entry_type_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EntryTypeIamPolicyConfig {
  entryTypeId: string | Computed<string>;
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  policyData: string | Computed<string>;
  project?: string | Computed<string>;
}

export interface EntryTypeIamPolicyAttrs {
  entryTypeId: string;
  etag: string;
  id: string;
  location: string;
  policyData: string;
  project: string;
}

export const EntryTypeIamPolicy: ResourceBinding<EntryTypeIamPolicyConfig, EntryTypeIamPolicyAttrs> = {
  wireType: "google_dataplex_entry_type_iam_policy",
  fields: {
    entryTypeId: "entry_type_id",
    id: "id",
    location: "location",
    policyData: "policy_data",
    project: "project",
  },
};
