// Code generated by `ubx sdk gen` from google_dataplex_glossary_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface GlossaryIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const GlossaryIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface GlossaryIamBindingConfig {
  glossaryId: string | Computed<string>;
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  condition?: GlossaryIamBinding_Condition[] | Computed<GlossaryIamBinding_Condition[]>;
}

export interface GlossaryIamBindingAttrs {
  etag: string;
  glossaryId: string;
  id: string;
  location: string;
  members: string[];
  project: string;
  role: string;
  condition: GlossaryIamBinding_Condition[];
}

export const GlossaryIamBinding: ResourceBinding<GlossaryIamBindingConfig, GlossaryIamBindingAttrs> = {
  wireType: "google_dataplex_glossary_iam_binding",
  fields: {
    glossaryId: "glossary_id",
    id: "id",
    location: "location",
    members: "members",
    project: "project",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: GlossaryIamBinding_ConditionFields,
    },
  },
};
