// Code generated by `ubx sdk gen` from google_kms_key_ring. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface KeyRing_Timeouts {
  create: string;
  delete: string;
}

const KeyRing_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
};

export interface KeyRingConfig {
  id?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  timeouts?: KeyRing_Timeouts | Computed<KeyRing_Timeouts>;
}

export interface KeyRingAttrs {
  id: string;
  location: string;
  name: string;
  project: string;
  timeouts: KeyRing_Timeouts;
}

export const KeyRing: ResourceBinding<KeyRingConfig, KeyRingAttrs> = {
  wireType: "google_kms_key_ring",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    project: "project",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: KeyRing_TimeoutsFields,
    },
  },
};
