// Code generated by `ubx sdk gen` from google_kms_key_ring_iam_member. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface KeyRingIamMember_Condition {
  description: string;
  expression: string;
  title: string;
}

const KeyRingIamMember_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface KeyRingIamMemberConfig {
  id?: string | Computed<string>;
  keyRingId: string | Computed<string>;
  member: string | Computed<string>;
  role: string | Computed<string>;
  condition?: KeyRingIamMember_Condition[] | Computed<KeyRingIamMember_Condition[]>;
}

export interface KeyRingIamMemberAttrs {
  etag: string;
  id: string;
  keyRingId: string;
  member: string;
  role: string;
  condition: KeyRingIamMember_Condition[];
}

export const KeyRingIamMember: ResourceBinding<KeyRingIamMemberConfig, KeyRingIamMemberAttrs> = {
  wireType: "google_kms_key_ring_iam_member",
  fields: {
    id: "id",
    keyRingId: "key_ring_id",
    member: "member",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: KeyRingIamMember_ConditionFields,
    },
  },
};
