// Code generated by `ubx sdk gen` from google_kms_project_autokey_config. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ProjectAutokeyConfig_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ProjectAutokeyConfig_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ProjectAutokeyConfigConfig {
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  keyProjectResolutionMode?: string | Computed<string>;
  project?: string | Computed<string>;
  timeouts?: ProjectAutokeyConfig_Timeouts | Computed<ProjectAutokeyConfig_Timeouts>;
}

export interface ProjectAutokeyConfigAttrs {
  deletionPolicy: string;
  etag: string;
  id: string;
  keyProjectResolutionMode: string;
  project: string;
  timeouts: ProjectAutokeyConfig_Timeouts;
}

export const ProjectAutokeyConfig: ResourceBinding<ProjectAutokeyConfigConfig, ProjectAutokeyConfigAttrs> = {
  wireType: "google_kms_project_autokey_config",
  fields: {
    deletionPolicy: "deletion_policy",
    id: "id",
    keyProjectResolutionMode: "key_project_resolution_mode",
    project: "project",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ProjectAutokeyConfig_TimeoutsFields,
    },
  },
};
