// Code generated by `ubx sdk gen` from google_clouddeploy_custom_target_type_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CustomTargetTypeIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const CustomTargetTypeIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface CustomTargetTypeIamBindingConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  condition?: CustomTargetTypeIamBinding_Condition[] | Computed<CustomTargetTypeIamBinding_Condition[]>;
}

export interface CustomTargetTypeIamBindingAttrs {
  etag: string;
  id: string;
  location: string;
  members: string[];
  name: string;
  project: string;
  role: string;
  condition: CustomTargetTypeIamBinding_Condition[];
}

export const CustomTargetTypeIamBinding: ResourceBinding<CustomTargetTypeIamBindingConfig, CustomTargetTypeIamBindingAttrs> = {
  wireType: "google_clouddeploy_custom_target_type_iam_binding",
  fields: {
    id: "id",
    location: "location",
    members: "members",
    name: "name",
    project: "project",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: CustomTargetTypeIamBinding_ConditionFields,
    },
  },
};
