// Code generated by `ubx sdk gen` from google_clouddeploy_delivery_pipeline_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DeliveryPipelineIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const DeliveryPipelineIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface DeliveryPipelineIamBindingConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  condition?: DeliveryPipelineIamBinding_Condition[] | Computed<DeliveryPipelineIamBinding_Condition[]>;
}

export interface DeliveryPipelineIamBindingAttrs {
  etag: string;
  id: string;
  location: string;
  members: string[];
  name: string;
  project: string;
  role: string;
  condition: DeliveryPipelineIamBinding_Condition[];
}

export const DeliveryPipelineIamBinding: ResourceBinding<DeliveryPipelineIamBindingConfig, DeliveryPipelineIamBindingAttrs> = {
  wireType: "google_clouddeploy_delivery_pipeline_iam_binding",
  fields: {
    id: "id",
    location: "location",
    members: "members",
    name: "name",
    project: "project",
    role: "role",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: DeliveryPipelineIamBinding_ConditionFields,
    },
  },
};
