// Code generated by `ubx sdk gen` from google_clouddeploy_delivery_pipeline_iam_policy. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DeliveryPipelineIamPolicyConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  name: string | Computed<string>;
  policyData: string | Computed<string>;
  project?: string | Computed<string>;
}

export interface DeliveryPipelineIamPolicyAttrs {
  etag: string;
  id: string;
  location: string;
  name: string;
  policyData: string;
  project: string;
}

export const DeliveryPipelineIamPolicy: ResourceBinding<DeliveryPipelineIamPolicyConfig, DeliveryPipelineIamPolicyAttrs> = {
  wireType: "google_clouddeploy_delivery_pipeline_iam_policy",
  fields: {
    id: "id",
    location: "location",
    name: "name",
    policyData: "policy_data",
    project: "project",
  },
};
