// Code generated by `ubx sdk gen` from google_apigee_data_collector. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataCollector_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const DataCollector_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface DataCollectorConfig {
  dataCollectorId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  orgId: string | Computed<string>;
  type: string | Computed<string>;
  timeouts?: DataCollector_Timeouts | Computed<DataCollector_Timeouts>;
}

export interface DataCollectorAttrs {
  createdAt: string;
  dataCollectorId: string;
  deletionPolicy: string;
  description: string;
  id: string;
  lastModifiedAt: string;
  name: string;
  orgId: string;
  type: string;
  timeouts: DataCollector_Timeouts;
}

export const DataCollector: ResourceBinding<DataCollectorConfig, DataCollectorAttrs> = {
  wireType: "google_apigee_data_collector",
  fields: {
    dataCollectorId: "data_collector_id",
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    orgId: "org_id",
    type: "type",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DataCollector_TimeoutsFields,
    },
  },
};
