// Code generated by `ubx sdk gen` from google_apigee_nat_address. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface NatAddress_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const NatAddress_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface NatAddressConfig {
  activate?: boolean | Computed<boolean>;
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  instanceId: string | Computed<string>;
  name: string | Computed<string>;
  timeouts?: NatAddress_Timeouts | Computed<NatAddress_Timeouts>;
}

export interface NatAddressAttrs {
  activate: boolean;
  deletionPolicy: string;
  id: string;
  instanceId: string;
  ipAddress: string;
  name: string;
  state: string;
  timeouts: NatAddress_Timeouts;
}

export const NatAddress: ResourceBinding<NatAddressConfig, NatAddressAttrs> = {
  wireType: "google_apigee_nat_address",
  fields: {
    activate: "activate",
    deletionPolicy: "deletion_policy",
    id: "id",
    instanceId: "instance_id",
    name: "name",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: NatAddress_TimeoutsFields,
    },
  },
};
