// Code generated by `ubx sdk gen` from google_apigee_security_profile_v2. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SecurityProfileV2_ProfileAssessmentConfigs {
  assessment: string;
  weight: string;
}

export interface SecurityProfileV2_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const SecurityProfileV2_ProfileAssessmentConfigsFields: FieldMap = {
  assessment: "assessment",
  weight: "weight",
};

const SecurityProfileV2_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SecurityProfileV2Config {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  orgId: string | Computed<string>;
  profileId: string | Computed<string>;
  profileAssessmentConfigs?: SecurityProfileV2_ProfileAssessmentConfigs[] | Computed<SecurityProfileV2_ProfileAssessmentConfigs[]>;
  timeouts?: SecurityProfileV2_Timeouts | Computed<SecurityProfileV2_Timeouts>;
}

export interface SecurityProfileV2Attrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  id: string;
  name: string;
  orgId: string;
  profileId: string;
  updateTime: string;
  profileAssessmentConfigs: SecurityProfileV2_ProfileAssessmentConfigs[];
  timeouts: SecurityProfileV2_Timeouts;
}

export const SecurityProfileV2: ResourceBinding<SecurityProfileV2Config, SecurityProfileV2Attrs> = {
  wireType: "google_apigee_security_profile_v2",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    orgId: "org_id",
    profileId: "profile_id",
    profileAssessmentConfigs: {
      wireName: "profile_assessment_configs",
      kind: "set",
      fields: SecurityProfileV2_ProfileAssessmentConfigsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SecurityProfileV2_TimeoutsFields,
    },
  },
};
