// Code generated by `ubx sdk gen` from google_discovery_engine_schema. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EngineSchema_Timeouts {
  create: string;
  delete: string;
}

const EngineSchema_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
};

export interface EngineSchemaConfig {
  dataStoreId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  jsonSchema?: string | Computed<string>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  schemaId: string | Computed<string>;
  timeouts?: EngineSchema_Timeouts | Computed<EngineSchema_Timeouts>;
}

export interface EngineSchemaAttrs {
  dataStoreId: string;
  deletionPolicy: string;
  id: string;
  jsonSchema: string;
  location: string;
  name: string;
  project: string;
  schemaId: string;
  timeouts: EngineSchema_Timeouts;
}

export const EngineSchema: ResourceBinding<EngineSchemaConfig, EngineSchemaAttrs> = {
  wireType: "google_discovery_engine_schema",
  fields: {
    dataStoreId: "data_store_id",
    deletionPolicy: "deletion_policy",
    id: "id",
    jsonSchema: "json_schema",
    location: "location",
    project: "project",
    schemaId: "schema_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: EngineSchema_TimeoutsFields,
    },
  },
};
