// Code generated by `ubx sdk gen` from google_discovery_engine_recommendation_engine. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface EngineRecommendationEngine_CommonConfig {
  companyName: string;
}

export interface EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig_MostPopularConfig {
  timeWindowDays: number;
}

export interface EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig_RecommendedForYouConfig {
  contextEventType: string;
}

export interface EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig {
  mostPopularConfig: EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig_MostPopularConfig[];
  recommendedForYouConfig: EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig_RecommendedForYouConfig[];
}

export interface EngineRecommendationEngine_MediaRecommendationEngineConfig_OptimizationObjectiveConfig {
  targetField: string;
  targetFieldValueFloat: number;
}

export interface EngineRecommendationEngine_MediaRecommendationEngineConfig {
  optimizationObjective: string;
  trainingState: string;
  type: string;
  engineFeaturesConfig: EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig[];
  optimizationObjectiveConfig: EngineRecommendationEngine_MediaRecommendationEngineConfig_OptimizationObjectiveConfig[];
}

export interface EngineRecommendationEngine_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const EngineRecommendationEngine_CommonConfigFields: FieldMap = {
  companyName: "company_name",
};

const EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig_MostPopularConfigFields: FieldMap = {
  timeWindowDays: "time_window_days",
};

const EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig_RecommendedForYouConfigFields: FieldMap = {
  contextEventType: "context_event_type",
};

const EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfigFields: FieldMap = {
  mostPopularConfig: {
    wireName: "most_popular_config",
    kind: "list",
    fields: EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig_MostPopularConfigFields,
  },
  recommendedForYouConfig: {
    wireName: "recommended_for_you_config",
    kind: "list",
    fields: EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfig_RecommendedForYouConfigFields,
  },
};

const EngineRecommendationEngine_MediaRecommendationEngineConfig_OptimizationObjectiveConfigFields: FieldMap = {
  targetField: "target_field",
  targetFieldValueFloat: "target_field_value_float",
};

const EngineRecommendationEngine_MediaRecommendationEngineConfigFields: FieldMap = {
  optimizationObjective: "optimization_objective",
  trainingState: "training_state",
  type: "type",
  engineFeaturesConfig: {
    wireName: "engine_features_config",
    kind: "list",
    fields: EngineRecommendationEngine_MediaRecommendationEngineConfig_EngineFeaturesConfigFields,
  },
  optimizationObjectiveConfig: {
    wireName: "optimization_objective_config",
    kind: "list",
    fields: EngineRecommendationEngine_MediaRecommendationEngineConfig_OptimizationObjectiveConfigFields,
  },
};

const EngineRecommendationEngine_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface EngineRecommendationEngineConfig {
  dataStoreIds: string[] | Computed<string[]>;
  deletionPolicy?: string | Computed<string>;
  displayName: string | Computed<string>;
  engineId: string | Computed<string>;
  id?: string | Computed<string>;
  industryVertical?: string | Computed<string>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  commonConfig?: EngineRecommendationEngine_CommonConfig[] | Computed<EngineRecommendationEngine_CommonConfig[]>;
  mediaRecommendationEngineConfig?: EngineRecommendationEngine_MediaRecommendationEngineConfig[] | Computed<EngineRecommendationEngine_MediaRecommendationEngineConfig[]>;
  timeouts?: EngineRecommendationEngine_Timeouts | Computed<EngineRecommendationEngine_Timeouts>;
}

export interface EngineRecommendationEngineAttrs {
  createTime: string;
  dataStoreIds: string[];
  deletionPolicy: string;
  displayName: string;
  engineId: string;
  id: string;
  industryVertical: string;
  location: string;
  name: string;
  project: string;
  updateTime: string;
  commonConfig: EngineRecommendationEngine_CommonConfig[];
  mediaRecommendationEngineConfig: EngineRecommendationEngine_MediaRecommendationEngineConfig[];
  timeouts: EngineRecommendationEngine_Timeouts;
}

export const EngineRecommendationEngine: ResourceBinding<EngineRecommendationEngineConfig, EngineRecommendationEngineAttrs> = {
  wireType: "google_discovery_engine_recommendation_engine",
  fields: {
    dataStoreIds: "data_store_ids",
    deletionPolicy: "deletion_policy",
    displayName: "display_name",
    engineId: "engine_id",
    id: "id",
    industryVertical: "industry_vertical",
    location: "location",
    project: "project",
    commonConfig: {
      wireName: "common_config",
      kind: "list",
      fields: EngineRecommendationEngine_CommonConfigFields,
    },
    mediaRecommendationEngineConfig: {
      wireName: "media_recommendation_engine_config",
      kind: "list",
      fields: EngineRecommendationEngine_MediaRecommendationEngineConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: EngineRecommendationEngine_TimeoutsFields,
    },
  },
};
