// Code generated by `ubx sdk gen` from google_securityposture_posture_deployment. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface PostureDeployment_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const PostureDeployment_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface PostureDeploymentConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  parent: string | Computed<string>;
  postureDeploymentId: string | Computed<string>;
  postureId: string | Computed<string>;
  postureRevisionId: string | Computed<string>;
  targetResource: string | Computed<string>;
  timeouts?: PostureDeployment_Timeouts | Computed<PostureDeployment_Timeouts>;
}

export interface PostureDeploymentAttrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  desiredPostureId: string;
  desiredPostureRevisionId: string;
  etag: string;
  failureMessage: string;
  id: string;
  location: string;
  name: string;
  parent: string;
  postureDeploymentId: string;
  postureId: string;
  postureRevisionId: string;
  reconciling: boolean;
  state: string;
  targetResource: string;
  updateTime: string;
  timeouts: PostureDeployment_Timeouts;
}

export const PostureDeployment: ResourceBinding<PostureDeploymentConfig, PostureDeploymentAttrs> = {
  wireType: "google_securityposture_posture_deployment",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    location: "location",
    parent: "parent",
    postureDeploymentId: "posture_deployment_id",
    postureId: "posture_id",
    postureRevisionId: "posture_revision_id",
    targetResource: "target_resource",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: PostureDeployment_TimeoutsFields,
    },
  },
};
