// Code generated by `ubx sdk gen` from google_contact_center_insights_assessment_rule. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CenterInsightsAssessmentRule_SampleRule {
  conversationFilter: string;
  dimension: string;
  samplePercentage: number;
  sampleRow: number;
}

export interface CenterInsightsAssessmentRule_ScheduleInfo {
  endTime: string;
  schedule: string;
  startTime: string;
  timeZone: string;
}

export interface CenterInsightsAssessmentRule_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const CenterInsightsAssessmentRule_SampleRuleFields: FieldMap = {
  conversationFilter: "conversation_filter",
  dimension: "dimension",
  samplePercentage: "sample_percentage",
  sampleRow: "sample_row",
};

const CenterInsightsAssessmentRule_ScheduleInfoFields: FieldMap = {
  endTime: "end_time",
  schedule: "schedule",
  startTime: "start_time",
  timeZone: "time_zone",
};

const CenterInsightsAssessmentRule_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface CenterInsightsAssessmentRuleConfig {
  active?: boolean | Computed<boolean>;
  assessmentRuleId?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  sampleRule?: CenterInsightsAssessmentRule_SampleRule[] | Computed<CenterInsightsAssessmentRule_SampleRule[]>;
  scheduleInfo?: CenterInsightsAssessmentRule_ScheduleInfo[] | Computed<CenterInsightsAssessmentRule_ScheduleInfo[]>;
  timeouts?: CenterInsightsAssessmentRule_Timeouts | Computed<CenterInsightsAssessmentRule_Timeouts>;
}

export interface CenterInsightsAssessmentRuleAttrs {
  active: boolean;
  assessmentRuleId: string;
  createTime: string;
  deletionPolicy: string;
  displayName: string;
  id: string;
  location: string;
  name: string;
  project: string;
  updateTime: string;
  sampleRule: CenterInsightsAssessmentRule_SampleRule[];
  scheduleInfo: CenterInsightsAssessmentRule_ScheduleInfo[];
  timeouts: CenterInsightsAssessmentRule_Timeouts;
}

export const CenterInsightsAssessmentRule: ResourceBinding<CenterInsightsAssessmentRuleConfig, CenterInsightsAssessmentRuleAttrs> = {
  wireType: "google_contact_center_insights_assessment_rule",
  fields: {
    active: "active",
    assessmentRuleId: "assessment_rule_id",
    deletionPolicy: "deletion_policy",
    displayName: "display_name",
    id: "id",
    location: "location",
    project: "project",
    sampleRule: {
      wireName: "sample_rule",
      kind: "list",
      fields: CenterInsightsAssessmentRule_SampleRuleFields,
    },
    scheduleInfo: {
      wireName: "schedule_info",
      kind: "list",
      fields: CenterInsightsAssessmentRule_ScheduleInfoFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CenterInsightsAssessmentRule_TimeoutsFields,
    },
  },
};
