// Code generated by `ubx sdk gen` from google_bigtable_instance. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Instance_Cluster_AutoscalingConfig {
  cpuTarget: number;
  maxNodes: number;
  minNodes: number;
  storageTarget: number;
}

export interface Instance_Cluster {
  clusterId: string;
  kmsKeyName: string;
  nodeScalingFactor: string;
  numNodes: number;
  state: string;
  storageType: string;
  zone: string;
  autoscalingConfig: Instance_Cluster_AutoscalingConfig[];
}

export interface Instance_Timeouts {
  create: string;
  read: string;
  update: string;
}

const Instance_Cluster_AutoscalingConfigFields: FieldMap = {
  cpuTarget: "cpu_target",
  maxNodes: "max_nodes",
  minNodes: "min_nodes",
  storageTarget: "storage_target",
};

const Instance_ClusterFields: FieldMap = {
  clusterId: "cluster_id",
  kmsKeyName: "kms_key_name",
  nodeScalingFactor: "node_scaling_factor",
  numNodes: "num_nodes",
  state: "state",
  storageType: "storage_type",
  zone: "zone",
  autoscalingConfig: {
    wireName: "autoscaling_config",
    kind: "list",
    fields: Instance_Cluster_AutoscalingConfigFields,
  },
};

const Instance_TimeoutsFields: FieldMap = {
  create: "create",
  read: "read",
  update: "update",
};

export interface InstanceConfig {
  deletionPolicy?: string | Computed<string>;
  deletionProtection?: boolean | Computed<boolean>;
  displayName?: string | Computed<string>;
  edition?: string | Computed<string>;
  forceDestroy?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  instanceType?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  cluster?: Instance_Cluster[] | Computed<Instance_Cluster[]>;
  timeouts?: Instance_Timeouts | Computed<Instance_Timeouts>;
}

export interface InstanceAttrs {
  deletionPolicy: string;
  deletionProtection: boolean;
  displayName: string;
  edition: string;
  effectiveLabels: Record<string, string>;
  forceDestroy: boolean;
  id: string;
  instanceType: string;
  labels: Record<string, string>;
  name: string;
  project: string;
  tags: Record<string, string>;
  terraformLabels: Record<string, string>;
  cluster: Instance_Cluster[];
  timeouts: Instance_Timeouts;
}

export const Instance: ResourceBinding<InstanceConfig, InstanceAttrs> = {
  wireType: "google_bigtable_instance",
  fields: {
    deletionPolicy: "deletion_policy",
    deletionProtection: "deletion_protection",
    displayName: "display_name",
    edition: "edition",
    forceDestroy: "force_destroy",
    id: "id",
    instanceType: "instance_type",
    labels: "labels",
    name: "name",
    project: "project",
    tags: "tags",
    cluster: {
      wireName: "cluster",
      kind: "list",
      fields: Instance_ClusterFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Instance_TimeoutsFields,
    },
  },
};
