// Code generated by `ubx sdk gen` from google_bigtable_materialized_view. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface MaterializedView_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const MaterializedView_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface MaterializedViewConfig {
  deletionPolicy?: string | Computed<string>;
  deletionProtection?: boolean | Computed<boolean>;
  id?: string | Computed<string>;
  instance?: string | Computed<string>;
  materializedViewId: string | Computed<string>;
  project?: string | Computed<string>;
  query: string | Computed<string>;
  timeouts?: MaterializedView_Timeouts | Computed<MaterializedView_Timeouts>;
}

export interface MaterializedViewAttrs {
  deletionPolicy: string;
  deletionProtection: boolean;
  id: string;
  instance: string;
  materializedViewId: string;
  name: string;
  project: string;
  query: string;
  timeouts: MaterializedView_Timeouts;
}

export const MaterializedView: ResourceBinding<MaterializedViewConfig, MaterializedViewAttrs> = {
  wireType: "google_bigtable_materialized_view",
  fields: {
    deletionPolicy: "deletion_policy",
    deletionProtection: "deletion_protection",
    id: "id",
    instance: "instance",
    materializedViewId: "materialized_view_id",
    project: "project",
    query: "query",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: MaterializedView_TimeoutsFields,
    },
  },
};
