// Code generated by `ubx sdk gen` from google_monitoring_custom_service. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface CustomService_Telemetry {
  resourceName: string;
}

export interface CustomService_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const CustomService_TelemetryFields: FieldMap = {
  resourceName: "resource_name",
};

const CustomService_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface CustomServiceConfig {
  deletionPolicy?: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  project?: string | Computed<string>;
  serviceId?: string | Computed<string>;
  userLabels?: Record<string, string> | Computed<Record<string, string>>;
  telemetry?: CustomService_Telemetry[] | Computed<CustomService_Telemetry[]>;
  timeouts?: CustomService_Timeouts | Computed<CustomService_Timeouts>;
}

export interface CustomServiceAttrs {
  deletionPolicy: string;
  displayName: string;
  id: string;
  name: string;
  project: string;
  serviceId: string;
  userLabels: Record<string, string>;
  telemetry: CustomService_Telemetry[];
  timeouts: CustomService_Timeouts;
}

export const CustomService: ResourceBinding<CustomServiceConfig, CustomServiceAttrs> = {
  wireType: "google_monitoring_custom_service",
  fields: {
    deletionPolicy: "deletion_policy",
    displayName: "display_name",
    id: "id",
    project: "project",
    serviceId: "service_id",
    userLabels: "user_labels",
    telemetry: {
      wireName: "telemetry",
      kind: "list",
      fields: CustomService_TelemetryFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: CustomService_TimeoutsFields,
    },
  },
};
