// Code generated by `ubx sdk gen` from google_monitoring_slo. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Slo_BasicSli_Availability {
  enabled: boolean;
}

export interface Slo_BasicSli_Latency {
  threshold: string;
}

export interface Slo_BasicSli {
  location: string[];
  method: string[];
  version: string[];
  availability: Slo_BasicSli_Availability[];
  latency: Slo_BasicSli_Latency[];
}

export interface Slo_RequestBasedSli_DistributionCut_Range {
  max: number;
  min: number;
}

export interface Slo_RequestBasedSli_DistributionCut {
  distributionFilter: string;
  range: Slo_RequestBasedSli_DistributionCut_Range[];
}

export interface Slo_RequestBasedSli_GoodTotalRatio {
  badServiceFilter: string;
  goodServiceFilter: string;
  totalServiceFilter: string;
}

export interface Slo_RequestBasedSli {
  distributionCut: Slo_RequestBasedSli_DistributionCut[];
  goodTotalRatio: Slo_RequestBasedSli_GoodTotalRatio[];
}

export interface Slo_Timeouts {
  create: string;
  delete: string;
  update: string;
}

export interface Slo_WindowsBasedSli_GoodTotalRatioThreshold {
  threshold: number;
  basicSliPerformance: Slo_BasicSli[];
  performance: Slo_RequestBasedSli[];
}

export interface Slo_WindowsBasedSli_MetricMeanInRange {
  timeSeries: string;
  range: Slo_RequestBasedSli_DistributionCut_Range[];
}

export interface Slo_WindowsBasedSli {
  goodBadMetricFilter: string;
  windowPeriod: string;
  goodTotalRatioThreshold: Slo_WindowsBasedSli_GoodTotalRatioThreshold[];
  metricMeanInRange: Slo_WindowsBasedSli_MetricMeanInRange[];
  metricSumInRange: Slo_WindowsBasedSli_MetricMeanInRange[];
}

const Slo_BasicSli_AvailabilityFields: FieldMap = {
  enabled: "enabled",
};

const Slo_BasicSli_LatencyFields: FieldMap = {
  threshold: "threshold",
};

const Slo_BasicSliFields: FieldMap = {
  location: "location",
  method: "method",
  version: "version",
  availability: {
    wireName: "availability",
    kind: "list",
    fields: Slo_BasicSli_AvailabilityFields,
  },
  latency: {
    wireName: "latency",
    kind: "list",
    fields: Slo_BasicSli_LatencyFields,
  },
};

const Slo_RequestBasedSli_DistributionCut_RangeFields: FieldMap = {
  max: "max",
  min: "min",
};

const Slo_RequestBasedSli_DistributionCutFields: FieldMap = {
  distributionFilter: "distribution_filter",
  range: {
    wireName: "range",
    kind: "list",
    fields: Slo_RequestBasedSli_DistributionCut_RangeFields,
  },
};

const Slo_RequestBasedSli_GoodTotalRatioFields: FieldMap = {
  badServiceFilter: "bad_service_filter",
  goodServiceFilter: "good_service_filter",
  totalServiceFilter: "total_service_filter",
};

const Slo_RequestBasedSliFields: FieldMap = {
  distributionCut: {
    wireName: "distribution_cut",
    kind: "list",
    fields: Slo_RequestBasedSli_DistributionCutFields,
  },
  goodTotalRatio: {
    wireName: "good_total_ratio",
    kind: "list",
    fields: Slo_RequestBasedSli_GoodTotalRatioFields,
  },
};

const Slo_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

const Slo_WindowsBasedSli_GoodTotalRatioThresholdFields: FieldMap = {
  threshold: "threshold",
  basicSliPerformance: {
    wireName: "basic_sli_performance",
    kind: "list",
    fields: Slo_BasicSliFields,
  },
  performance: {
    wireName: "performance",
    kind: "list",
    fields: Slo_RequestBasedSliFields,
  },
};

const Slo_WindowsBasedSli_MetricMeanInRangeFields: FieldMap = {
  timeSeries: "time_series",
  range: {
    wireName: "range",
    kind: "list",
    fields: Slo_RequestBasedSli_DistributionCut_RangeFields,
  },
};

const Slo_WindowsBasedSliFields: FieldMap = {
  goodBadMetricFilter: "good_bad_metric_filter",
  windowPeriod: "window_period",
  goodTotalRatioThreshold: {
    wireName: "good_total_ratio_threshold",
    kind: "list",
    fields: Slo_WindowsBasedSli_GoodTotalRatioThresholdFields,
  },
  metricMeanInRange: {
    wireName: "metric_mean_in_range",
    kind: "list",
    fields: Slo_WindowsBasedSli_MetricMeanInRangeFields,
  },
  metricSumInRange: {
    wireName: "metric_sum_in_range",
    kind: "list",
    fields: Slo_WindowsBasedSli_MetricMeanInRangeFields,
  },
};

export interface SloConfig {
  calendarPeriod?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  displayName?: string | Computed<string>;
  goal: number | Computed<number>;
  id?: string | Computed<string>;
  project?: string | Computed<string>;
  rollingPeriodDays?: number | Computed<number>;
  service: string | Computed<string>;
  sloId?: string | Computed<string>;
  userLabels?: Record<string, string> | Computed<Record<string, string>>;
  basicSli?: Slo_BasicSli[] | Computed<Slo_BasicSli[]>;
  requestBasedSli?: Slo_RequestBasedSli[] | Computed<Slo_RequestBasedSli[]>;
  timeouts?: Slo_Timeouts | Computed<Slo_Timeouts>;
  windowsBasedSli?: Slo_WindowsBasedSli[] | Computed<Slo_WindowsBasedSli[]>;
}

export interface SloAttrs {
  calendarPeriod: string;
  deletionPolicy: string;
  displayName: string;
  goal: number;
  id: string;
  name: string;
  project: string;
  rollingPeriodDays: number;
  service: string;
  sloId: string;
  userLabels: Record<string, string>;
  basicSli: Slo_BasicSli[];
  requestBasedSli: Slo_RequestBasedSli[];
  timeouts: Slo_Timeouts;
  windowsBasedSli: Slo_WindowsBasedSli[];
}

export const Slo: ResourceBinding<SloConfig, SloAttrs> = {
  wireType: "google_monitoring_slo",
  fields: {
    calendarPeriod: "calendar_period",
    deletionPolicy: "deletion_policy",
    displayName: "display_name",
    goal: "goal",
    id: "id",
    project: "project",
    rollingPeriodDays: "rolling_period_days",
    service: "service",
    sloId: "slo_id",
    userLabels: "user_labels",
    basicSli: {
      wireName: "basic_sli",
      kind: "list",
      fields: Slo_BasicSliFields,
    },
    requestBasedSli: {
      wireName: "request_based_sli",
      kind: "list",
      fields: Slo_RequestBasedSliFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Slo_TimeoutsFields,
    },
    windowsBasedSli: {
      wireName: "windows_based_sli",
      kind: "list",
      fields: Slo_WindowsBasedSliFields,
    },
  },
};
