// Code generated by `ubx sdk gen` from google_service_directory_service. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DirectoryService_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const DirectoryService_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface DirectoryServiceConfig {
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  metadata?: Record<string, string> | Computed<Record<string, string>>;
  namespace: string | Computed<string>;
  serviceId: string | Computed<string>;
  timeouts?: DirectoryService_Timeouts | Computed<DirectoryService_Timeouts>;
}

export interface DirectoryServiceAttrs {
  deletionPolicy: string;
  id: string;
  metadata: Record<string, string>;
  name: string;
  namespace: string;
  serviceId: string;
  timeouts: DirectoryService_Timeouts;
}

export const DirectoryService: ResourceBinding<DirectoryServiceConfig, DirectoryServiceAttrs> = {
  wireType: "google_service_directory_service",
  fields: {
    deletionPolicy: "deletion_policy",
    id: "id",
    metadata: "metadata",
    namespace: "namespace",
    serviceId: "service_id",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DirectoryService_TimeoutsFields,
    },
  },
};
