// Code generated by `ubx sdk gen` from google_vector_search_collection. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SearchCollection_EncryptionSpec {
  cryptoKeyName: string;
}

export interface SearchCollection_Timeouts {
  create: string;
  delete: string;
  update: string;
}

export interface SearchCollection_VectorSchema_DenseVector_VertexEmbeddingConfig {
  modelId: string;
  taskType: string;
  textTemplate: string;
}

export interface SearchCollection_VectorSchema_DenseVector {
  dimensions: number;
  vertexEmbeddingConfig: SearchCollection_VectorSchema_DenseVector_VertexEmbeddingConfig[];
}

export interface SearchCollection_VectorSchema_SparseVector {
}

export interface SearchCollection_VectorSchema {
  fieldName: string;
  denseVector: SearchCollection_VectorSchema_DenseVector[];
  sparseVector: SearchCollection_VectorSchema_SparseVector[];
}

const SearchCollection_EncryptionSpecFields: FieldMap = {
  cryptoKeyName: "crypto_key_name",
};

const SearchCollection_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

const SearchCollection_VectorSchema_DenseVector_VertexEmbeddingConfigFields: FieldMap = {
  modelId: "model_id",
  taskType: "task_type",
  textTemplate: "text_template",
};

const SearchCollection_VectorSchema_DenseVectorFields: FieldMap = {
  dimensions: "dimensions",
  vertexEmbeddingConfig: {
    wireName: "vertex_embedding_config",
    kind: "list",
    fields: SearchCollection_VectorSchema_DenseVector_VertexEmbeddingConfigFields,
  },
};

const SearchCollection_VectorSchema_SparseVectorFields: FieldMap = {
};

const SearchCollection_VectorSchemaFields: FieldMap = {
  fieldName: "field_name",
  denseVector: {
    wireName: "dense_vector",
    kind: "list",
    fields: SearchCollection_VectorSchema_DenseVectorFields,
  },
  sparseVector: {
    wireName: "sparse_vector",
    kind: "list",
    fields: SearchCollection_VectorSchema_SparseVectorFields,
  },
};

export interface SearchCollectionConfig {
  collectionId: string | Computed<string>;
  dataSchema?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  encryptionSpec?: SearchCollection_EncryptionSpec[] | Computed<SearchCollection_EncryptionSpec[]>;
  timeouts?: SearchCollection_Timeouts | Computed<SearchCollection_Timeouts>;
  vectorSchema?: SearchCollection_VectorSchema[] | Computed<SearchCollection_VectorSchema[]>;
}

export interface SearchCollectionAttrs {
  collectionId: string;
  createTime: string;
  dataSchema: string;
  deletionPolicy: string;
  description: string;
  displayName: string;
  effectiveLabels: Record<string, string>;
  id: string;
  labels: Record<string, string>;
  location: string;
  name: string;
  project: string;
  terraformLabels: Record<string, string>;
  updateTime: string;
  encryptionSpec: SearchCollection_EncryptionSpec[];
  timeouts: SearchCollection_Timeouts;
  vectorSchema: SearchCollection_VectorSchema[];
}

export const SearchCollection: ResourceBinding<SearchCollectionConfig, SearchCollectionAttrs> = {
  wireType: "google_vector_search_collection",
  fields: {
    collectionId: "collection_id",
    dataSchema: "data_schema",
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    id: "id",
    labels: "labels",
    location: "location",
    project: "project",
    encryptionSpec: {
      wireName: "encryption_spec",
      kind: "list",
      fields: SearchCollection_EncryptionSpecFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SearchCollection_TimeoutsFields,
    },
    vectorSchema: {
      wireName: "vector_schema",
      kind: "set",
      fields: SearchCollection_VectorSchemaFields,
    },
  },
};
