// Code generated by `ubx sdk gen` from google_cloudbuild_trigger. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Trigger_ApprovalConfig {
  approvalRequired: boolean;
}

export interface Trigger_BitbucketServerTriggerConfig_PullRequest {
  branch: string;
  commentControl: string;
  invertRegex: boolean;
}

export interface Trigger_BitbucketServerTriggerConfig_Push {
  branch: string;
  invertRegex: boolean;
  tag: string;
}

export interface Trigger_BitbucketServerTriggerConfig {
  bitbucketServerConfigResource: string;
  projectKey: string;
  repoSlug: string;
  pullRequest: Trigger_BitbucketServerTriggerConfig_PullRequest[];
  push: Trigger_BitbucketServerTriggerConfig_Push[];
}

export interface Trigger_Build_Artifacts_MavenArtifacts {
  artifactId: string;
  groupId: string;
  path: string;
  repository: string;
  version: string;
}

export interface Trigger_Build_Artifacts_NpmPackages {
  packagePath: string;
  repository: string;
}

export interface Trigger_Build_Artifacts_Objects_Timing {
  endTime: string;
  startTime: string;
}

export interface Trigger_Build_Artifacts_Objects {
  location: string;
  paths: string[];
  timing: Trigger_Build_Artifacts_Objects_Timing[];
}

export interface Trigger_Build_Artifacts_PythonPackages {
  paths: string[];
  repository: string;
}

export interface Trigger_Build_Artifacts {
  images: string[];
  mavenArtifacts: Trigger_Build_Artifacts_MavenArtifacts[];
  npmPackages: Trigger_Build_Artifacts_NpmPackages[];
  objects: Trigger_Build_Artifacts_Objects[];
  pythonPackages: Trigger_Build_Artifacts_PythonPackages[];
}

export interface Trigger_Build_AvailableSecrets_SecretManager {
  env: string;
  versionName: string;
}

export interface Trigger_Build_AvailableSecrets {
  secretManager: Trigger_Build_AvailableSecrets_SecretManager[];
}

export interface Trigger_Build_Options_Volumes {
  name: string;
  path: string;
}

export interface Trigger_Build_Options {
  diskSizeGb: number;
  dynamicSubstitutions: boolean;
  env: string[];
  logStreamingOption: string;
  logging: string;
  machineType: string;
  requestedVerifyOption: string;
  secretEnv: string[];
  sourceProvenanceHash: string[];
  substitutionOption: string;
  workerPool: string;
  volumes: Trigger_Build_Options_Volumes[];
}

export interface Trigger_Build_Secret {
  kmsKeyName: string;
  secretEnv: Record<string, string>;
}

export interface Trigger_Build_Source_RepoSource {
  branchName: string;
  commitSha: string;
  dir: string;
  invertRegex: boolean;
  projectId: string;
  repoName: string;
  substitutions: Record<string, string>;
  tagName: string;
}

export interface Trigger_Build_Source_StorageSource {
  bucket: string;
  generation: string;
  object: string;
}

export interface Trigger_Build_Source {
  repoSource: Trigger_Build_Source_RepoSource[];
  storageSource: Trigger_Build_Source_StorageSource[];
}

export interface Trigger_Build_Step {
  allowExitCodes: number[];
  allowFailure: boolean;
  args: string[];
  dir: string;
  entrypoint: string;
  env: string[];
  id: string;
  name: string;
  script: string;
  secretEnv: string[];
  timeout: string;
  timing: string;
  waitFor: string[];
  volumes: Trigger_Build_Options_Volumes[];
}

export interface Trigger_Build {
  images: string[];
  logsBucket: string;
  queueTtl: string;
  substitutions: Record<string, string>;
  tags: string[];
  timeout: string;
  artifacts: Trigger_Build_Artifacts[];
  availableSecrets: Trigger_Build_AvailableSecrets[];
  options: Trigger_Build_Options[];
  secret: Trigger_Build_Secret[];
  source: Trigger_Build_Source[];
  step: Trigger_Build_Step[];
}

export interface Trigger_DeveloperConnectEventConfig {
  gitRepositoryLink: string;
  gitRepositoryLinkType: string;
  pullRequest: Trigger_BitbucketServerTriggerConfig_PullRequest[];
  push: Trigger_BitbucketServerTriggerConfig_Push[];
}

export interface Trigger_GitFileSource {
  bitbucketServerConfig: string;
  githubEnterpriseConfig: string;
  path: string;
  repoType: string;
  repository: string;
  revision: string;
  uri: string;
}

export interface Trigger_Github {
  enterpriseConfigResourceName: string;
  name: string;
  owner: string;
  pullRequest: Trigger_BitbucketServerTriggerConfig_PullRequest[];
  push: Trigger_BitbucketServerTriggerConfig_Push[];
}

export interface Trigger_PubsubConfig {
  serviceAccountEmail: string;
  state: string;
  subscription: string;
  topic: string;
}

export interface Trigger_RepositoryEventConfig {
  repository: string;
  pullRequest: Trigger_BitbucketServerTriggerConfig_PullRequest[];
  push: Trigger_BitbucketServerTriggerConfig_Push[];
}

export interface Trigger_SourceToBuild {
  bitbucketServerConfig: string;
  githubEnterpriseConfig: string;
  ref: string;
  repoType: string;
  repository: string;
  uri: string;
}

export interface Trigger_Timeouts {
  create: string;
  delete: string;
  update: string;
}

export interface Trigger_TriggerTemplate {
  branchName: string;
  commitSha: string;
  dir: string;
  invertRegex: boolean;
  projectId: string;
  repoName: string;
  tagName: string;
}

export interface Trigger_WebhookConfig {
  secret: string;
  state: string;
}

const Trigger_ApprovalConfigFields: FieldMap = {
  approvalRequired: "approval_required",
};

const Trigger_BitbucketServerTriggerConfig_PullRequestFields: FieldMap = {
  branch: "branch",
  commentControl: "comment_control",
  invertRegex: "invert_regex",
};

const Trigger_BitbucketServerTriggerConfig_PushFields: FieldMap = {
  branch: "branch",
  invertRegex: "invert_regex",
  tag: "tag",
};

const Trigger_BitbucketServerTriggerConfigFields: FieldMap = {
  bitbucketServerConfigResource: "bitbucket_server_config_resource",
  projectKey: "project_key",
  repoSlug: "repo_slug",
  pullRequest: {
    wireName: "pull_request",
    kind: "list",
    fields: Trigger_BitbucketServerTriggerConfig_PullRequestFields,
  },
  push: {
    wireName: "push",
    kind: "list",
    fields: Trigger_BitbucketServerTriggerConfig_PushFields,
  },
};

const Trigger_Build_Artifacts_MavenArtifactsFields: FieldMap = {
  artifactId: "artifact_id",
  groupId: "group_id",
  path: "path",
  repository: "repository",
  version: "version",
};

const Trigger_Build_Artifacts_NpmPackagesFields: FieldMap = {
  packagePath: "package_path",
  repository: "repository",
};

const Trigger_Build_Artifacts_Objects_TimingFields: FieldMap = {
  endTime: "end_time",
  startTime: "start_time",
};

const Trigger_Build_Artifacts_ObjectsFields: FieldMap = {
  location: "location",
  paths: "paths",
  timing: {
    wireName: "timing",
    kind: "list",
    fields: Trigger_Build_Artifacts_Objects_TimingFields,
  },
};

const Trigger_Build_Artifacts_PythonPackagesFields: FieldMap = {
  paths: "paths",
  repository: "repository",
};

const Trigger_Build_ArtifactsFields: FieldMap = {
  images: "images",
  mavenArtifacts: {
    wireName: "maven_artifacts",
    kind: "list",
    fields: Trigger_Build_Artifacts_MavenArtifactsFields,
  },
  npmPackages: {
    wireName: "npm_packages",
    kind: "list",
    fields: Trigger_Build_Artifacts_NpmPackagesFields,
  },
  objects: {
    wireName: "objects",
    kind: "list",
    fields: Trigger_Build_Artifacts_ObjectsFields,
  },
  pythonPackages: {
    wireName: "python_packages",
    kind: "list",
    fields: Trigger_Build_Artifacts_PythonPackagesFields,
  },
};

const Trigger_Build_AvailableSecrets_SecretManagerFields: FieldMap = {
  env: "env",
  versionName: "version_name",
};

const Trigger_Build_AvailableSecretsFields: FieldMap = {
  secretManager: {
    wireName: "secret_manager",
    kind: "list",
    fields: Trigger_Build_AvailableSecrets_SecretManagerFields,
  },
};

const Trigger_Build_Options_VolumesFields: FieldMap = {
  name: "name",
  path: "path",
};

const Trigger_Build_OptionsFields: FieldMap = {
  diskSizeGb: "disk_size_gb",
  dynamicSubstitutions: "dynamic_substitutions",
  env: "env",
  logStreamingOption: "log_streaming_option",
  logging: "logging",
  machineType: "machine_type",
  requestedVerifyOption: "requested_verify_option",
  secretEnv: "secret_env",
  sourceProvenanceHash: "source_provenance_hash",
  substitutionOption: "substitution_option",
  workerPool: "worker_pool",
  volumes: {
    wireName: "volumes",
    kind: "list",
    fields: Trigger_Build_Options_VolumesFields,
  },
};

const Trigger_Build_SecretFields: FieldMap = {
  kmsKeyName: "kms_key_name",
  secretEnv: "secret_env",
};

const Trigger_Build_Source_RepoSourceFields: FieldMap = {
  branchName: "branch_name",
  commitSha: "commit_sha",
  dir: "dir",
  invertRegex: "invert_regex",
  projectId: "project_id",
  repoName: "repo_name",
  substitutions: "substitutions",
  tagName: "tag_name",
};

const Trigger_Build_Source_StorageSourceFields: FieldMap = {
  bucket: "bucket",
  generation: "generation",
  object: "object",
};

const Trigger_Build_SourceFields: FieldMap = {
  repoSource: {
    wireName: "repo_source",
    kind: "list",
    fields: Trigger_Build_Source_RepoSourceFields,
  },
  storageSource: {
    wireName: "storage_source",
    kind: "list",
    fields: Trigger_Build_Source_StorageSourceFields,
  },
};

const Trigger_Build_StepFields: FieldMap = {
  allowExitCodes: "allow_exit_codes",
  allowFailure: "allow_failure",
  args: "args",
  dir: "dir",
  entrypoint: "entrypoint",
  env: "env",
  id: "id",
  name: "name",
  script: "script",
  secretEnv: "secret_env",
  timeout: "timeout",
  timing: "timing",
  waitFor: "wait_for",
  volumes: {
    wireName: "volumes",
    kind: "list",
    fields: Trigger_Build_Options_VolumesFields,
  },
};

const Trigger_BuildFields: FieldMap = {
  images: "images",
  logsBucket: "logs_bucket",
  queueTtl: "queue_ttl",
  substitutions: "substitutions",
  tags: "tags",
  timeout: "timeout",
  artifacts: {
    wireName: "artifacts",
    kind: "list",
    fields: Trigger_Build_ArtifactsFields,
  },
  availableSecrets: {
    wireName: "available_secrets",
    kind: "list",
    fields: Trigger_Build_AvailableSecretsFields,
  },
  options: {
    wireName: "options",
    kind: "list",
    fields: Trigger_Build_OptionsFields,
  },
  secret: {
    wireName: "secret",
    kind: "list",
    fields: Trigger_Build_SecretFields,
  },
  source: {
    wireName: "source",
    kind: "list",
    fields: Trigger_Build_SourceFields,
  },
  step: {
    wireName: "step",
    kind: "list",
    fields: Trigger_Build_StepFields,
  },
};

const Trigger_DeveloperConnectEventConfigFields: FieldMap = {
  gitRepositoryLink: "git_repository_link",
  gitRepositoryLinkType: "git_repository_link_type",
  pullRequest: {
    wireName: "pull_request",
    kind: "list",
    fields: Trigger_BitbucketServerTriggerConfig_PullRequestFields,
  },
  push: {
    wireName: "push",
    kind: "list",
    fields: Trigger_BitbucketServerTriggerConfig_PushFields,
  },
};

const Trigger_GitFileSourceFields: FieldMap = {
  bitbucketServerConfig: "bitbucket_server_config",
  githubEnterpriseConfig: "github_enterprise_config",
  path: "path",
  repoType: "repo_type",
  repository: "repository",
  revision: "revision",
  uri: "uri",
};

const Trigger_GithubFields: FieldMap = {
  enterpriseConfigResourceName: "enterprise_config_resource_name",
  name: "name",
  owner: "owner",
  pullRequest: {
    wireName: "pull_request",
    kind: "list",
    fields: Trigger_BitbucketServerTriggerConfig_PullRequestFields,
  },
  push: {
    wireName: "push",
    kind: "list",
    fields: Trigger_BitbucketServerTriggerConfig_PushFields,
  },
};

const Trigger_PubsubConfigFields: FieldMap = {
  serviceAccountEmail: "service_account_email",
  state: "state",
  subscription: "subscription",
  topic: "topic",
};

const Trigger_RepositoryEventConfigFields: FieldMap = {
  repository: "repository",
  pullRequest: {
    wireName: "pull_request",
    kind: "list",
    fields: Trigger_BitbucketServerTriggerConfig_PullRequestFields,
  },
  push: {
    wireName: "push",
    kind: "list",
    fields: Trigger_BitbucketServerTriggerConfig_PushFields,
  },
};

const Trigger_SourceToBuildFields: FieldMap = {
  bitbucketServerConfig: "bitbucket_server_config",
  githubEnterpriseConfig: "github_enterprise_config",
  ref: "ref",
  repoType: "repo_type",
  repository: "repository",
  uri: "uri",
};

const Trigger_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

const Trigger_TriggerTemplateFields: FieldMap = {
  branchName: "branch_name",
  commitSha: "commit_sha",
  dir: "dir",
  invertRegex: "invert_regex",
  projectId: "project_id",
  repoName: "repo_name",
  tagName: "tag_name",
};

const Trigger_WebhookConfigFields: FieldMap = {
  secret: "secret",
  state: "state",
};

export interface TriggerConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  filename?: string | Computed<string>;
  filter?: string | Computed<string>;
  id?: string | Computed<string>;
  ignoredFiles?: string[] | Computed<string[]>;
  includeBuildLogs?: string | Computed<string>;
  includedFiles?: string[] | Computed<string[]>;
  location?: string | Computed<string>;
  name?: string | Computed<string>;
  project?: string | Computed<string>;
  serviceAccount?: string | Computed<string>;
  substitutions?: Record<string, string> | Computed<Record<string, string>>;
  tags?: string[] | Computed<string[]>;
  approvalConfig?: Trigger_ApprovalConfig[] | Computed<Trigger_ApprovalConfig[]>;
  bitbucketServerTriggerConfig?: Trigger_BitbucketServerTriggerConfig[] | Computed<Trigger_BitbucketServerTriggerConfig[]>;
  build?: Trigger_Build[] | Computed<Trigger_Build[]>;
  developerConnectEventConfig?: Trigger_DeveloperConnectEventConfig[] | Computed<Trigger_DeveloperConnectEventConfig[]>;
  gitFileSource?: Trigger_GitFileSource[] | Computed<Trigger_GitFileSource[]>;
  github?: Trigger_Github[] | Computed<Trigger_Github[]>;
  pubsubConfig?: Trigger_PubsubConfig[] | Computed<Trigger_PubsubConfig[]>;
  repositoryEventConfig?: Trigger_RepositoryEventConfig[] | Computed<Trigger_RepositoryEventConfig[]>;
  sourceToBuild?: Trigger_SourceToBuild[] | Computed<Trigger_SourceToBuild[]>;
  timeouts?: Trigger_Timeouts | Computed<Trigger_Timeouts>;
  triggerTemplate?: Trigger_TriggerTemplate[] | Computed<Trigger_TriggerTemplate[]>;
  webhookConfig?: Trigger_WebhookConfig[] | Computed<Trigger_WebhookConfig[]>;
}

export interface TriggerAttrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  disabled: boolean;
  filename: string;
  filter: string;
  id: string;
  ignoredFiles: string[];
  includeBuildLogs: string;
  includedFiles: string[];
  location: string;
  name: string;
  project: string;
  serviceAccount: string;
  substitutions: Record<string, string>;
  tags: string[];
  triggerId: string;
  approvalConfig: Trigger_ApprovalConfig[];
  bitbucketServerTriggerConfig: Trigger_BitbucketServerTriggerConfig[];
  build: Trigger_Build[];
  developerConnectEventConfig: Trigger_DeveloperConnectEventConfig[];
  gitFileSource: Trigger_GitFileSource[];
  github: Trigger_Github[];
  pubsubConfig: Trigger_PubsubConfig[];
  repositoryEventConfig: Trigger_RepositoryEventConfig[];
  sourceToBuild: Trigger_SourceToBuild[];
  timeouts: Trigger_Timeouts;
  triggerTemplate: Trigger_TriggerTemplate[];
  webhookConfig: Trigger_WebhookConfig[];
}

export const Trigger: ResourceBinding<TriggerConfig, TriggerAttrs> = {
  wireType: "google_cloudbuild_trigger",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    disabled: "disabled",
    filename: "filename",
    filter: "filter",
    id: "id",
    ignoredFiles: "ignored_files",
    includeBuildLogs: "include_build_logs",
    includedFiles: "included_files",
    location: "location",
    name: "name",
    project: "project",
    serviceAccount: "service_account",
    substitutions: "substitutions",
    tags: "tags",
    approvalConfig: {
      wireName: "approval_config",
      kind: "list",
      fields: Trigger_ApprovalConfigFields,
    },
    bitbucketServerTriggerConfig: {
      wireName: "bitbucket_server_trigger_config",
      kind: "list",
      fields: Trigger_BitbucketServerTriggerConfigFields,
    },
    build: {
      wireName: "build",
      kind: "list",
      fields: Trigger_BuildFields,
    },
    developerConnectEventConfig: {
      wireName: "developer_connect_event_config",
      kind: "list",
      fields: Trigger_DeveloperConnectEventConfigFields,
    },
    gitFileSource: {
      wireName: "git_file_source",
      kind: "list",
      fields: Trigger_GitFileSourceFields,
    },
    github: {
      wireName: "github",
      kind: "list",
      fields: Trigger_GithubFields,
    },
    pubsubConfig: {
      wireName: "pubsub_config",
      kind: "list",
      fields: Trigger_PubsubConfigFields,
    },
    repositoryEventConfig: {
      wireName: "repository_event_config",
      kind: "list",
      fields: Trigger_RepositoryEventConfigFields,
    },
    sourceToBuild: {
      wireName: "source_to_build",
      kind: "list",
      fields: Trigger_SourceToBuildFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Trigger_TimeoutsFields,
    },
    triggerTemplate: {
      wireName: "trigger_template",
      kind: "list",
      fields: Trigger_TriggerTemplateFields,
    },
    webhookConfig: {
      wireName: "webhook_config",
      kind: "list",
      fields: Trigger_WebhookConfigFields,
    },
  },
};
