// Code generated by `ubx sdk gen` from google_certificate_manager_certificate_map. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface ManagerCertificateMap_GclbTargets_IpConfigs {
  ipAddress: string;
  ports: number[];
}

export interface ManagerCertificateMap_GclbTargets {
  ipConfigs: ManagerCertificateMap_GclbTargets_IpConfigs[];
  targetHttpsProxy: string;
  targetSslProxy: string;
}

export interface ManagerCertificateMap_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const ManagerCertificateMap_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface ManagerCertificateMapConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  timeouts?: ManagerCertificateMap_Timeouts | Computed<ManagerCertificateMap_Timeouts>;
}

export interface ManagerCertificateMapAttrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  effectiveLabels: Record<string, string>;
  gclbTargets: ManagerCertificateMap_GclbTargets[];
  id: string;
  labels: Record<string, string>;
  name: string;
  project: string;
  terraformLabels: Record<string, string>;
  updateTime: string;
  timeouts: ManagerCertificateMap_Timeouts;
}

export const ManagerCertificateMap: ResourceBinding<ManagerCertificateMapConfig, ManagerCertificateMapAttrs> = {
  wireType: "google_certificate_manager_certificate_map",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    labels: "labels",
    name: "name",
    project: "project",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: ManagerCertificateMap_TimeoutsFields,
    },
  },
};
