// Code generated by `ubx sdk gen` from google_logging_organization_exclusion. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface OrganizationExclusionConfig {
  description?: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  filter: string | Computed<string>;
  id?: string | Computed<string>;
  name: string | Computed<string>;
  orgId: string | Computed<string>;
}

export interface OrganizationExclusionAttrs {
  description: string;
  disabled: boolean;
  filter: string;
  id: string;
  name: string;
  orgId: string;
}

export const OrganizationExclusion: ResourceBinding<OrganizationExclusionConfig, OrganizationExclusionAttrs> = {
  wireType: "google_logging_organization_exclusion",
  fields: {
    description: "description",
    disabled: "disabled",
    filter: "filter",
    id: "id",
    name: "name",
    orgId: "org_id",
  },
};
