// Code generated by `ubx sdk gen` from google_managed_kafka_connect_cluster. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface KafkaConnectCluster_CapacityConfig {
  memoryBytes: string;
  vcpuCount: string;
}

export interface KafkaConnectCluster_GcpConfig_AccessConfig_NetworkConfigs {
  additionalSubnets: string[];
  dnsDomainNames: string[];
  primarySubnet: string;
}

export interface KafkaConnectCluster_GcpConfig_AccessConfig {
  networkConfigs: KafkaConnectCluster_GcpConfig_AccessConfig_NetworkConfigs[];
}

export interface KafkaConnectCluster_GcpConfig {
  accessConfig: KafkaConnectCluster_GcpConfig_AccessConfig[];
}

export interface KafkaConnectCluster_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const KafkaConnectCluster_CapacityConfigFields: FieldMap = {
  memoryBytes: "memory_bytes",
  vcpuCount: "vcpu_count",
};

const KafkaConnectCluster_GcpConfig_AccessConfig_NetworkConfigsFields: FieldMap = {
  additionalSubnets: "additional_subnets",
  dnsDomainNames: "dns_domain_names",
  primarySubnet: "primary_subnet",
};

const KafkaConnectCluster_GcpConfig_AccessConfigFields: FieldMap = {
  networkConfigs: {
    wireName: "network_configs",
    kind: "list",
    fields: KafkaConnectCluster_GcpConfig_AccessConfig_NetworkConfigsFields,
  },
};

const KafkaConnectCluster_GcpConfigFields: FieldMap = {
  accessConfig: {
    wireName: "access_config",
    kind: "list",
    fields: KafkaConnectCluster_GcpConfig_AccessConfigFields,
  },
};

const KafkaConnectCluster_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface KafkaConnectClusterConfig {
  connectClusterId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  kafkaCluster: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  capacityConfig?: KafkaConnectCluster_CapacityConfig[] | Computed<KafkaConnectCluster_CapacityConfig[]>;
  gcpConfig?: KafkaConnectCluster_GcpConfig[] | Computed<KafkaConnectCluster_GcpConfig[]>;
  timeouts?: KafkaConnectCluster_Timeouts | Computed<KafkaConnectCluster_Timeouts>;
}

export interface KafkaConnectClusterAttrs {
  connectClusterId: string;
  createTime: string;
  deletionPolicy: string;
  effectiveLabels: Record<string, string>;
  id: string;
  kafkaCluster: string;
  labels: Record<string, string>;
  location: string;
  name: string;
  project: string;
  state: string;
  terraformLabels: Record<string, string>;
  updateTime: string;
  capacityConfig: KafkaConnectCluster_CapacityConfig[];
  gcpConfig: KafkaConnectCluster_GcpConfig[];
  timeouts: KafkaConnectCluster_Timeouts;
}

export const KafkaConnectCluster: ResourceBinding<KafkaConnectClusterConfig, KafkaConnectClusterAttrs> = {
  wireType: "google_managed_kafka_connect_cluster",
  fields: {
    connectClusterId: "connect_cluster_id",
    deletionPolicy: "deletion_policy",
    id: "id",
    kafkaCluster: "kafka_cluster",
    labels: "labels",
    location: "location",
    project: "project",
    capacityConfig: {
      wireName: "capacity_config",
      kind: "list",
      fields: KafkaConnectCluster_CapacityConfigFields,
    },
    gcpConfig: {
      wireName: "gcp_config",
      kind: "list",
      fields: KafkaConnectCluster_GcpConfigFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: KafkaConnectCluster_TimeoutsFields,
    },
  },
};
