// Code generated by `ubx sdk gen` from google_dataform_folder. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Folder_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const Folder_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface FolderConfig {
  containingFolder?: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  displayName: string | Computed<string>;
  id?: string | Computed<string>;
  project?: string | Computed<string>;
  region: string | Computed<string>;
  timeouts?: Folder_Timeouts | Computed<Folder_Timeouts>;
}

export interface FolderAttrs {
  containingFolder: string;
  deletionPolicy: string;
  displayName: string;
  folderId: string;
  id: string;
  name: string;
  project: string;
  region: string;
  timeouts: Folder_Timeouts;
}

export const Folder: ResourceBinding<FolderConfig, FolderAttrs> = {
  wireType: "google_dataform_folder",
  fields: {
    containingFolder: "containing_folder",
    deletionPolicy: "deletion_policy",
    displayName: "display_name",
    id: "id",
    project: "project",
    region: "region",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Folder_TimeoutsFields,
    },
  },
};
