// Code generated by `ubx sdk gen` from google_cloud_run_service_iam_binding. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RunServiceIamBinding_Condition {
  description: string;
  expression: string;
  title: string;
}

const RunServiceIamBinding_ConditionFields: FieldMap = {
  description: "description",
  expression: "expression",
  title: "title",
};

export interface RunServiceIamBindingConfig {
  id?: string | Computed<string>;
  location?: string | Computed<string>;
  members: string[] | Computed<string[]>;
  project?: string | Computed<string>;
  role: string | Computed<string>;
  service: string | Computed<string>;
  condition?: RunServiceIamBinding_Condition[] | Computed<RunServiceIamBinding_Condition[]>;
}

export interface RunServiceIamBindingAttrs {
  etag: string;
  id: string;
  location: string;
  members: string[];
  project: string;
  role: string;
  service: string;
  condition: RunServiceIamBinding_Condition[];
}

export const RunServiceIamBinding: ResourceBinding<RunServiceIamBindingConfig, RunServiceIamBindingAttrs> = {
  wireType: "google_cloud_run_service_iam_binding",
  fields: {
    id: "id",
    location: "location",
    members: "members",
    project: "project",
    role: "role",
    service: "service",
    condition: {
      wireName: "condition",
      kind: "list",
      fields: RunServiceIamBinding_ConditionFields,
    },
  },
};
