// Code generated by `ubx sdk gen` from google_cloud_run_v2_worker_pool. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface RunV2WorkerPool_Conditions {
  executionReason: string;
  lastTransitionTime: string;
  message: string;
  reason: string;
  revisionReason: string;
  severity: string;
  state: string;
  type: string;
}

export interface RunV2WorkerPool_InstanceSplitStatuses {
  percent: number;
  revision: string;
  type: string;
}

export interface RunV2WorkerPool_BinaryAuthorization {
  breakglassJustification: string;
  policy: string;
  useDefault: boolean;
}

export interface RunV2WorkerPool_Scaling {
  manualInstanceCount: number;
  maxInstanceCount: number;
  minInstanceCount: number;
  scalingMode: string;
}

export interface RunV2WorkerPool_Template_Containers_Env_ValueSource_SecretKeyRef {
  secret: string;
  version: string;
}

export interface RunV2WorkerPool_Template_Containers_Env_ValueSource {
  secretKeyRef: RunV2WorkerPool_Template_Containers_Env_ValueSource_SecretKeyRef[];
}

export interface RunV2WorkerPool_Template_Containers_Env {
  name: string;
  value: string;
  valueSource: RunV2WorkerPool_Template_Containers_Env_ValueSource[];
}

export interface RunV2WorkerPool_Template_Containers_LivenessProbe_Grpc {
  port: number;
  service: string;
}

export interface RunV2WorkerPool_Template_Containers_LivenessProbe_HttpGet_HttpHeaders {
  name: string;
  port: number;
  value: string;
}

export interface RunV2WorkerPool_Template_Containers_LivenessProbe_HttpGet {
  path: string;
  port: number;
  httpHeaders: RunV2WorkerPool_Template_Containers_LivenessProbe_HttpGet_HttpHeaders[];
}

export interface RunV2WorkerPool_Template_Containers_LivenessProbe_TcpSocket {
  port: number;
}

export interface RunV2WorkerPool_Template_Containers_LivenessProbe {
  failureThreshold: number;
  initialDelaySeconds: number;
  periodSeconds: number;
  timeoutSeconds: number;
  grpc: RunV2WorkerPool_Template_Containers_LivenessProbe_Grpc[];
  httpGet: RunV2WorkerPool_Template_Containers_LivenessProbe_HttpGet[];
  tcpSocket: RunV2WorkerPool_Template_Containers_LivenessProbe_TcpSocket[];
}

export interface RunV2WorkerPool_Template_Containers_Resources {
  limits: Record<string, string>;
}

export interface RunV2WorkerPool_Template_Containers_VolumeMounts {
  mountPath: string;
  name: string;
  subPath: string;
}

export interface RunV2WorkerPool_Template_Containers {
  args: string[];
  command: string[];
  dependsOn: string[];
  image: string;
  name: string;
  workingDir: string;
  env: RunV2WorkerPool_Template_Containers_Env[];
  livenessProbe: RunV2WorkerPool_Template_Containers_LivenessProbe[];
  resources: RunV2WorkerPool_Template_Containers_Resources[];
  startupProbe: RunV2WorkerPool_Template_Containers_LivenessProbe[];
  volumeMounts: RunV2WorkerPool_Template_Containers_VolumeMounts[];
}

export interface RunV2WorkerPool_Template_NodeSelector {
  accelerator: string;
}

export interface RunV2WorkerPool_Template_Volumes_CloudSqlInstance {
  instances: string[];
}

export interface RunV2WorkerPool_Template_Volumes_EmptyDir {
  medium: string;
  sizeLimit: string;
}

export interface RunV2WorkerPool_Template_Volumes_Gcs {
  bucket: string;
  mountOptions: string[];
  readOnly: boolean;
}

export interface RunV2WorkerPool_Template_Volumes_Nfs {
  path: string;
  readOnly: boolean;
  server: string;
}

export interface RunV2WorkerPool_Template_Volumes_Secret_Items {
  mode: number;
  path: string;
  version: string;
}

export interface RunV2WorkerPool_Template_Volumes_Secret {
  defaultMode: number;
  secret: string;
  items: RunV2WorkerPool_Template_Volumes_Secret_Items[];
}

export interface RunV2WorkerPool_Template_Volumes {
  name: string;
  cloudSqlInstance: RunV2WorkerPool_Template_Volumes_CloudSqlInstance[];
  emptyDir: RunV2WorkerPool_Template_Volumes_EmptyDir[];
  gcs: RunV2WorkerPool_Template_Volumes_Gcs[];
  nfs: RunV2WorkerPool_Template_Volumes_Nfs[];
  secret: RunV2WorkerPool_Template_Volumes_Secret[];
}

export interface RunV2WorkerPool_Template_VpcAccess_NetworkInterfaces {
  network: string;
  subnetwork: string;
  tags: string[];
}

export interface RunV2WorkerPool_Template_VpcAccess {
  connector: string;
  egress: string;
  networkInterfaces: RunV2WorkerPool_Template_VpcAccess_NetworkInterfaces[];
}

export interface RunV2WorkerPool_Template {
  annotations: Record<string, string>;
  client: string;
  clientVersion: string;
  encryptionKey: string;
  encryptionKeyRevocationAction: string;
  encryptionKeyShutdownDuration: string;
  gpuZonalRedundancyDisabled: boolean;
  labels: Record<string, string>;
  revision: string;
  serviceAccount: string;
  containers: RunV2WorkerPool_Template_Containers[];
  nodeSelector: RunV2WorkerPool_Template_NodeSelector[];
  volumes: RunV2WorkerPool_Template_Volumes[];
  vpcAccess: RunV2WorkerPool_Template_VpcAccess[];
}

export interface RunV2WorkerPool_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const RunV2WorkerPool_BinaryAuthorizationFields: FieldMap = {
  breakglassJustification: "breakglass_justification",
  policy: "policy",
  useDefault: "use_default",
};

const RunV2WorkerPool_InstanceSplitStatusesFields: FieldMap = {
  percent: "percent",
  revision: "revision",
  type: "type",
};

const RunV2WorkerPool_ScalingFields: FieldMap = {
  manualInstanceCount: "manual_instance_count",
  maxInstanceCount: "max_instance_count",
  minInstanceCount: "min_instance_count",
  scalingMode: "scaling_mode",
};

const RunV2WorkerPool_Template_Containers_Env_ValueSource_SecretKeyRefFields: FieldMap = {
  secret: "secret",
  version: "version",
};

const RunV2WorkerPool_Template_Containers_Env_ValueSourceFields: FieldMap = {
  secretKeyRef: {
    wireName: "secret_key_ref",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_Env_ValueSource_SecretKeyRefFields,
  },
};

const RunV2WorkerPool_Template_Containers_EnvFields: FieldMap = {
  name: "name",
  value: "value",
  valueSource: {
    wireName: "value_source",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_Env_ValueSourceFields,
  },
};

const RunV2WorkerPool_Template_Containers_LivenessProbe_GrpcFields: FieldMap = {
  port: "port",
  service: "service",
};

const RunV2WorkerPool_Template_Containers_LivenessProbe_HttpGet_HttpHeadersFields: FieldMap = {
  name: "name",
  port: "port",
  value: "value",
};

const RunV2WorkerPool_Template_Containers_LivenessProbe_HttpGetFields: FieldMap = {
  path: "path",
  port: "port",
  httpHeaders: {
    wireName: "http_headers",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_LivenessProbe_HttpGet_HttpHeadersFields,
  },
};

const RunV2WorkerPool_Template_Containers_LivenessProbe_TcpSocketFields: FieldMap = {
  port: "port",
};

const RunV2WorkerPool_Template_Containers_LivenessProbeFields: FieldMap = {
  failureThreshold: "failure_threshold",
  initialDelaySeconds: "initial_delay_seconds",
  periodSeconds: "period_seconds",
  timeoutSeconds: "timeout_seconds",
  grpc: {
    wireName: "grpc",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_LivenessProbe_GrpcFields,
  },
  httpGet: {
    wireName: "http_get",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_LivenessProbe_HttpGetFields,
  },
  tcpSocket: {
    wireName: "tcp_socket",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_LivenessProbe_TcpSocketFields,
  },
};

const RunV2WorkerPool_Template_Containers_ResourcesFields: FieldMap = {
  limits: "limits",
};

const RunV2WorkerPool_Template_Containers_VolumeMountsFields: FieldMap = {
  mountPath: "mount_path",
  name: "name",
  subPath: "sub_path",
};

const RunV2WorkerPool_Template_ContainersFields: FieldMap = {
  args: "args",
  command: "command",
  dependsOn: "depends_on",
  image: "image",
  name: "name",
  workingDir: "working_dir",
  env: {
    wireName: "env",
    kind: "set",
    fields: RunV2WorkerPool_Template_Containers_EnvFields,
  },
  livenessProbe: {
    wireName: "liveness_probe",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_LivenessProbeFields,
  },
  resources: {
    wireName: "resources",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_ResourcesFields,
  },
  startupProbe: {
    wireName: "startup_probe",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_LivenessProbeFields,
  },
  volumeMounts: {
    wireName: "volume_mounts",
    kind: "list",
    fields: RunV2WorkerPool_Template_Containers_VolumeMountsFields,
  },
};

const RunV2WorkerPool_Template_NodeSelectorFields: FieldMap = {
  accelerator: "accelerator",
};

const RunV2WorkerPool_Template_Volumes_CloudSqlInstanceFields: FieldMap = {
  instances: "instances",
};

const RunV2WorkerPool_Template_Volumes_EmptyDirFields: FieldMap = {
  medium: "medium",
  sizeLimit: "size_limit",
};

const RunV2WorkerPool_Template_Volumes_GcsFields: FieldMap = {
  bucket: "bucket",
  mountOptions: "mount_options",
  readOnly: "read_only",
};

const RunV2WorkerPool_Template_Volumes_NfsFields: FieldMap = {
  path: "path",
  readOnly: "read_only",
  server: "server",
};

const RunV2WorkerPool_Template_Volumes_Secret_ItemsFields: FieldMap = {
  mode: "mode",
  path: "path",
  version: "version",
};

const RunV2WorkerPool_Template_Volumes_SecretFields: FieldMap = {
  defaultMode: "default_mode",
  secret: "secret",
  items: {
    wireName: "items",
    kind: "list",
    fields: RunV2WorkerPool_Template_Volumes_Secret_ItemsFields,
  },
};

const RunV2WorkerPool_Template_VolumesFields: FieldMap = {
  name: "name",
  cloudSqlInstance: {
    wireName: "cloud_sql_instance",
    kind: "list",
    fields: RunV2WorkerPool_Template_Volumes_CloudSqlInstanceFields,
  },
  emptyDir: {
    wireName: "empty_dir",
    kind: "list",
    fields: RunV2WorkerPool_Template_Volumes_EmptyDirFields,
  },
  gcs: {
    wireName: "gcs",
    kind: "list",
    fields: RunV2WorkerPool_Template_Volumes_GcsFields,
  },
  nfs: {
    wireName: "nfs",
    kind: "list",
    fields: RunV2WorkerPool_Template_Volumes_NfsFields,
  },
  secret: {
    wireName: "secret",
    kind: "list",
    fields: RunV2WorkerPool_Template_Volumes_SecretFields,
  },
};

const RunV2WorkerPool_Template_VpcAccess_NetworkInterfacesFields: FieldMap = {
  network: "network",
  subnetwork: "subnetwork",
  tags: "tags",
};

const RunV2WorkerPool_Template_VpcAccessFields: FieldMap = {
  connector: "connector",
  egress: "egress",
  networkInterfaces: {
    wireName: "network_interfaces",
    kind: "list",
    fields: RunV2WorkerPool_Template_VpcAccess_NetworkInterfacesFields,
  },
};

const RunV2WorkerPool_TemplateFields: FieldMap = {
  annotations: "annotations",
  client: "client",
  clientVersion: "client_version",
  encryptionKey: "encryption_key",
  encryptionKeyRevocationAction: "encryption_key_revocation_action",
  encryptionKeyShutdownDuration: "encryption_key_shutdown_duration",
  gpuZonalRedundancyDisabled: "gpu_zonal_redundancy_disabled",
  labels: "labels",
  revision: "revision",
  serviceAccount: "service_account",
  containers: {
    wireName: "containers",
    kind: "list",
    fields: RunV2WorkerPool_Template_ContainersFields,
  },
  nodeSelector: {
    wireName: "node_selector",
    kind: "list",
    fields: RunV2WorkerPool_Template_NodeSelectorFields,
  },
  volumes: {
    wireName: "volumes",
    kind: "list",
    fields: RunV2WorkerPool_Template_VolumesFields,
  },
  vpcAccess: {
    wireName: "vpc_access",
    kind: "list",
    fields: RunV2WorkerPool_Template_VpcAccessFields,
  },
};

const RunV2WorkerPool_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface RunV2WorkerPoolConfig {
  annotations?: Record<string, string> | Computed<Record<string, string>>;
  client?: string | Computed<string>;
  clientVersion?: string | Computed<string>;
  customAudiences?: string[] | Computed<string[]>;
  deletionPolicy?: string | Computed<string>;
  deletionProtection?: boolean | Computed<boolean>;
  description?: string | Computed<string>;
  id?: string | Computed<string>;
  labels?: Record<string, string> | Computed<Record<string, string>>;
  launchStage?: string | Computed<string>;
  location: string | Computed<string>;
  name: string | Computed<string>;
  project?: string | Computed<string>;
  binaryAuthorization?: RunV2WorkerPool_BinaryAuthorization[] | Computed<RunV2WorkerPool_BinaryAuthorization[]>;
  instanceSplits?: RunV2WorkerPool_InstanceSplitStatuses[] | Computed<RunV2WorkerPool_InstanceSplitStatuses[]>;
  scaling?: RunV2WorkerPool_Scaling[] | Computed<RunV2WorkerPool_Scaling[]>;
  template?: RunV2WorkerPool_Template[] | Computed<RunV2WorkerPool_Template[]>;
  timeouts?: RunV2WorkerPool_Timeouts | Computed<RunV2WorkerPool_Timeouts>;
}

export interface RunV2WorkerPoolAttrs {
  annotations: Record<string, string>;
  client: string;
  clientVersion: string;
  conditions: RunV2WorkerPool_Conditions[];
  createTime: string;
  creator: string;
  customAudiences: string[];
  deleteTime: string;
  deletionPolicy: string;
  deletionProtection: boolean;
  description: string;
  effectiveAnnotations: Record<string, string>;
  effectiveLabels: Record<string, string>;
  etag: string;
  expireTime: string;
  generation: string;
  id: string;
  instanceSplitStatuses: RunV2WorkerPool_InstanceSplitStatuses[];
  labels: Record<string, string>;
  lastModifier: string;
  latestCreatedRevision: string;
  latestReadyRevision: string;
  launchStage: string;
  location: string;
  name: string;
  observedGeneration: string;
  project: string;
  reconciling: boolean;
  terminalCondition: RunV2WorkerPool_Conditions[];
  terraformLabels: Record<string, string>;
  uid: string;
  updateTime: string;
  binaryAuthorization: RunV2WorkerPool_BinaryAuthorization[];
  instanceSplits: RunV2WorkerPool_InstanceSplitStatuses[];
  scaling: RunV2WorkerPool_Scaling[];
  template: RunV2WorkerPool_Template[];
  timeouts: RunV2WorkerPool_Timeouts;
}

export const RunV2WorkerPool: ResourceBinding<RunV2WorkerPoolConfig, RunV2WorkerPoolAttrs> = {
  wireType: "google_cloud_run_v2_worker_pool",
  fields: {
    annotations: "annotations",
    client: "client",
    clientVersion: "client_version",
    customAudiences: "custom_audiences",
    deletionPolicy: "deletion_policy",
    deletionProtection: "deletion_protection",
    description: "description",
    id: "id",
    labels: "labels",
    launchStage: "launch_stage",
    location: "location",
    name: "name",
    project: "project",
    binaryAuthorization: {
      wireName: "binary_authorization",
      kind: "list",
      fields: RunV2WorkerPool_BinaryAuthorizationFields,
    },
    instanceSplits: {
      wireName: "instance_splits",
      kind: "list",
      fields: RunV2WorkerPool_InstanceSplitStatusesFields,
    },
    scaling: {
      wireName: "scaling",
      kind: "list",
      fields: RunV2WorkerPool_ScalingFields,
    },
    template: {
      wireName: "template",
      kind: "list",
      fields: RunV2WorkerPool_TemplateFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: RunV2WorkerPool_TimeoutsFields,
    },
  },
};
