// Code generated by `ubx sdk gen` from google_cloud_security_compliance_framework. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValue_StringListValue {
  values: string[];
}

export interface SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValue {
  boolValue: boolean;
  numberValue: number;
  stringValue: string;
  stringListValue: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValue_StringListValue[];
}

export interface SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue {
  name: string;
  parameterValue: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValue[];
}

export interface SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue {
  boolValue: boolean;
  numberValue: number;
  stringValue: string;
  oneofValue: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue[];
  stringListValue: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValue_StringListValue[];
}

export interface SecurityComplianceFramework_CloudControlDetails_Parameters {
  name: string;
  parameterValue: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue[];
}

export interface SecurityComplianceFramework_CloudControlDetails {
  majorRevisionId: string;
  name: string;
  parameters: SecurityComplianceFramework_CloudControlDetails_Parameters[];
}

export interface SecurityComplianceFramework_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValue_StringListValueFields: FieldMap = {
  values: "values",
};

const SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValueFields: FieldMap = {
  boolValue: "bool_value",
  numberValue: "number_value",
  stringValue: "string_value",
  stringListValue: {
    wireName: "string_list_value",
    kind: "list",
    fields: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValue_StringListValueFields,
  },
};

const SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValueFields: FieldMap = {
  name: "name",
  parameterValue: {
    wireName: "parameter_value",
    kind: "list",
    fields: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValueFields,
  },
};

const SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValueFields: FieldMap = {
  boolValue: "bool_value",
  numberValue: "number_value",
  stringValue: "string_value",
  oneofValue: {
    wireName: "oneof_value",
    kind: "list",
    fields: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValueFields,
  },
  stringListValue: {
    wireName: "string_list_value",
    kind: "list",
    fields: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValue_OneofValue_ParameterValue_StringListValueFields,
  },
};

const SecurityComplianceFramework_CloudControlDetails_ParametersFields: FieldMap = {
  name: "name",
  parameterValue: {
    wireName: "parameter_value",
    kind: "list",
    fields: SecurityComplianceFramework_CloudControlDetails_Parameters_ParameterValueFields,
  },
};

const SecurityComplianceFramework_CloudControlDetailsFields: FieldMap = {
  majorRevisionId: "major_revision_id",
  name: "name",
  parameters: {
    wireName: "parameters",
    kind: "list",
    fields: SecurityComplianceFramework_CloudControlDetails_ParametersFields,
  },
};

const SecurityComplianceFramework_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SecurityComplianceFrameworkConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  frameworkId: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  organization?: string | Computed<string>;
  parent?: string | Computed<string>;
  cloudControlDetails?: SecurityComplianceFramework_CloudControlDetails[] | Computed<SecurityComplianceFramework_CloudControlDetails[]>;
  timeouts?: SecurityComplianceFramework_Timeouts | Computed<SecurityComplianceFramework_Timeouts>;
}

export interface SecurityComplianceFrameworkAttrs {
  category: string[];
  deletionPolicy: string;
  description: string;
  displayName: string;
  frameworkId: string;
  id: string;
  location: string;
  majorRevisionId: string;
  name: string;
  organization: string;
  parent: string;
  supportedCloudProviders: string[];
  supportedEnforcementModes: string[];
  supportedTargetResourceTypes: string[];
  type: string;
  cloudControlDetails: SecurityComplianceFramework_CloudControlDetails[];
  timeouts: SecurityComplianceFramework_Timeouts;
}

export const SecurityComplianceFramework: ResourceBinding<SecurityComplianceFrameworkConfig, SecurityComplianceFrameworkAttrs> = {
  wireType: "google_cloud_security_compliance_framework",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    frameworkId: "framework_id",
    id: "id",
    location: "location",
    organization: "organization",
    parent: "parent",
    cloudControlDetails: {
      wireName: "cloud_control_details",
      kind: "list",
      fields: SecurityComplianceFramework_CloudControlDetailsFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SecurityComplianceFramework_TimeoutsFields,
    },
  },
};
