// Code generated by `ubx sdk gen` from google_cloud_security_compliance_cloud_control. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue_StringListValue {
  values: string[];
}

export interface SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue {
  boolValue: boolean;
  numberValue: number;
  stringValue: string;
  stringListValue: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue_StringListValue[];
}

export interface SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue {
  name: string;
  parameterValue: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue[];
}

export interface SecurityComplianceCloudControl_ParameterSpec_DefaultValue {
  boolValue: boolean;
  numberValue: number;
  stringValue: string;
  oneofValue: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue[];
  stringListValue: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue_StringListValue[];
}

export interface SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules_AttributeSubstitutionRule {
  attribute: string;
}

export interface SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules {
  attributeSubstitutionRule: SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules_AttributeSubstitutionRule[];
  placeholderSubstitutionRule: SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules_AttributeSubstitutionRule[];
}

export interface SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_AllowedValues {
  values: SecurityComplianceCloudControl_ParameterSpec_DefaultValue[];
}

export interface SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_IntRange {
  max: string;
  min: string;
}

export interface SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_RegexpPattern {
  pattern: string;
}

export interface SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation {
  allowedValues: SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_AllowedValues[];
  intRange: SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_IntRange[];
  regexpPattern: SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_RegexpPattern[];
}

export interface SecurityComplianceCloudControl_ParameterSpec_SubParameters {
  description: string;
  displayName: string;
  isRequired: boolean;
  name: string;
  valueType: string;
  defaultValue: SecurityComplianceCloudControl_ParameterSpec_DefaultValue[];
  substitutionRules: SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules[];
  validation: SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation[];
}

export interface SecurityComplianceCloudControl_ParameterSpec {
  description: string;
  displayName: string;
  isRequired: boolean;
  name: string;
  valueType: string;
  defaultValue: SecurityComplianceCloudControl_ParameterSpec_DefaultValue[];
  subParameters: SecurityComplianceCloudControl_ParameterSpec_SubParameters[];
  substitutionRules: SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules[];
  validation: SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation[];
}

export interface SecurityComplianceCloudControl_Rules_CelExpression {
  expression: string;
  resourceTypesValues: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue_StringListValue[];
}

export interface SecurityComplianceCloudControl_Rules {
  description: string;
  ruleActionTypes: string[];
  celExpression: SecurityComplianceCloudControl_Rules_CelExpression[];
}

export interface SecurityComplianceCloudControl_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue_StringListValueFields: FieldMap = {
  values: "values",
};

const SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValueFields: FieldMap = {
  boolValue: "bool_value",
  numberValue: "number_value",
  stringValue: "string_value",
  stringListValue: {
    wireName: "string_list_value",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue_StringListValueFields,
  },
};

const SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValueFields: FieldMap = {
  name: "name",
  parameterValue: {
    wireName: "parameter_value",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValueFields,
  },
};

const SecurityComplianceCloudControl_ParameterSpec_DefaultValueFields: FieldMap = {
  boolValue: "bool_value",
  numberValue: "number_value",
  stringValue: "string_value",
  oneofValue: {
    wireName: "oneof_value",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValueFields,
  },
  stringListValue: {
    wireName: "string_list_value",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue_StringListValueFields,
  },
};

const SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules_AttributeSubstitutionRuleFields: FieldMap = {
  attribute: "attribute",
};

const SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRulesFields: FieldMap = {
  attributeSubstitutionRule: {
    wireName: "attribute_substitution_rule",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules_AttributeSubstitutionRuleFields,
  },
  placeholderSubstitutionRule: {
    wireName: "placeholder_substitution_rule",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRules_AttributeSubstitutionRuleFields,
  },
};

const SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_AllowedValuesFields: FieldMap = {
  values: {
    wireName: "values",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_DefaultValueFields,
  },
};

const SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_IntRangeFields: FieldMap = {
  max: "max",
  min: "min",
};

const SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_RegexpPatternFields: FieldMap = {
  pattern: "pattern",
};

const SecurityComplianceCloudControl_ParameterSpec_SubParameters_ValidationFields: FieldMap = {
  allowedValues: {
    wireName: "allowed_values",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_AllowedValuesFields,
  },
  intRange: {
    wireName: "int_range",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_IntRangeFields,
  },
  regexpPattern: {
    wireName: "regexp_pattern",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_Validation_RegexpPatternFields,
  },
};

const SecurityComplianceCloudControl_ParameterSpec_SubParametersFields: FieldMap = {
  description: "description",
  displayName: "display_name",
  isRequired: "is_required",
  name: "name",
  valueType: "value_type",
  defaultValue: {
    wireName: "default_value",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_DefaultValueFields,
  },
  substitutionRules: {
    wireName: "substitution_rules",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRulesFields,
  },
  validation: {
    wireName: "validation",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_ValidationFields,
  },
};

const SecurityComplianceCloudControl_ParameterSpecFields: FieldMap = {
  description: "description",
  displayName: "display_name",
  isRequired: "is_required",
  name: "name",
  valueType: "value_type",
  defaultValue: {
    wireName: "default_value",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_DefaultValueFields,
  },
  subParameters: {
    wireName: "sub_parameters",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParametersFields,
  },
  substitutionRules: {
    wireName: "substitution_rules",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_SubstitutionRulesFields,
  },
  validation: {
    wireName: "validation",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_SubParameters_ValidationFields,
  },
};

const SecurityComplianceCloudControl_Rules_CelExpressionFields: FieldMap = {
  expression: "expression",
  resourceTypesValues: {
    wireName: "resource_types_values",
    kind: "list",
    fields: SecurityComplianceCloudControl_ParameterSpec_DefaultValue_OneofValue_ParameterValue_StringListValueFields,
  },
};

const SecurityComplianceCloudControl_RulesFields: FieldMap = {
  description: "description",
  ruleActionTypes: "rule_action_types",
  celExpression: {
    wireName: "cel_expression",
    kind: "list",
    fields: SecurityComplianceCloudControl_Rules_CelExpressionFields,
  },
};

const SecurityComplianceCloudControl_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface SecurityComplianceCloudControlConfig {
  categories?: string[] | Computed<string[]>;
  cloudControlId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName?: string | Computed<string>;
  findingCategory?: string | Computed<string>;
  id?: string | Computed<string>;
  location: string | Computed<string>;
  organization?: string | Computed<string>;
  parent?: string | Computed<string>;
  remediationSteps?: string | Computed<string>;
  severity?: string | Computed<string>;
  supportedCloudProviders?: string[] | Computed<string[]>;
  parameterSpec?: SecurityComplianceCloudControl_ParameterSpec[] | Computed<SecurityComplianceCloudControl_ParameterSpec[]>;
  rules?: SecurityComplianceCloudControl_Rules[] | Computed<SecurityComplianceCloudControl_Rules[]>;
  timeouts?: SecurityComplianceCloudControl_Timeouts | Computed<SecurityComplianceCloudControl_Timeouts>;
}

export interface SecurityComplianceCloudControlAttrs {
  categories: string[];
  cloudControlId: string;
  createTime: string;
  deletionPolicy: string;
  description: string;
  displayName: string;
  findingCategory: string;
  id: string;
  location: string;
  majorRevisionId: string;
  name: string;
  organization: string;
  parent: string;
  relatedFrameworks: string[];
  remediationSteps: string;
  severity: string;
  supportedCloudProviders: string[];
  supportedEnforcementModes: string[];
  supportedTargetResourceTypes: string[];
  parameterSpec: SecurityComplianceCloudControl_ParameterSpec[];
  rules: SecurityComplianceCloudControl_Rules[];
  timeouts: SecurityComplianceCloudControl_Timeouts;
}

export const SecurityComplianceCloudControl: ResourceBinding<SecurityComplianceCloudControlConfig, SecurityComplianceCloudControlAttrs> = {
  wireType: "google_cloud_security_compliance_cloud_control",
  fields: {
    categories: "categories",
    cloudControlId: "cloud_control_id",
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    findingCategory: "finding_category",
    id: "id",
    location: "location",
    organization: "organization",
    parent: "parent",
    remediationSteps: "remediation_steps",
    severity: "severity",
    supportedCloudProviders: "supported_cloud_providers",
    parameterSpec: {
      wireName: "parameter_spec",
      kind: "list",
      fields: SecurityComplianceCloudControl_ParameterSpecFields,
    },
    rules: {
      wireName: "rules",
      kind: "list",
      fields: SecurityComplianceCloudControl_RulesFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: SecurityComplianceCloudControl_TimeoutsFields,
    },
  },
};
