// Code generated by `ubx sdk gen` from google_chronicle_data_table. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataTable_ColumnInfo {
  columnIndex: number;
  columnType: string;
  keyColumn: boolean;
  mappedColumnPath: string;
  originalColumn: string;
  repeatedValues: boolean;
}

export interface DataTable_ScopeInfo {
  dataAccessScopes: string[];
}

export interface DataTable_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const DataTable_ColumnInfoFields: FieldMap = {
  columnIndex: "column_index",
  columnType: "column_type",
  keyColumn: "key_column",
  mappedColumnPath: "mapped_column_path",
  originalColumn: "original_column",
  repeatedValues: "repeated_values",
};

const DataTable_ScopeInfoFields: FieldMap = {
  dataAccessScopes: "data_access_scopes",
};

const DataTable_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface DataTableConfig {
  dataTableId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  description: string | Computed<string>;
  id?: string | Computed<string>;
  instance: string | Computed<string>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  rowTimeToLive?: string | Computed<string>;
  columnInfo?: DataTable_ColumnInfo[] | Computed<DataTable_ColumnInfo[]>;
  scopeInfo?: DataTable_ScopeInfo[] | Computed<DataTable_ScopeInfo[]>;
  timeouts?: DataTable_Timeouts | Computed<DataTable_Timeouts>;
}

export interface DataTableAttrs {
  approximateRowCount: number;
  createTime: string;
  dataTableId: string;
  dataTableUuid: string;
  deletionPolicy: string;
  description: string;
  displayName: string;
  id: string;
  instance: string;
  location: string;
  name: string;
  project: string;
  rowTimeToLive: string;
  rowTimeToLiveUpdateTime: string;
  ruleAssociationsCount: number;
  rules: string[];
  updateSource: string;
  updateTime: string;
  columnInfo: DataTable_ColumnInfo[];
  scopeInfo: DataTable_ScopeInfo[];
  timeouts: DataTable_Timeouts;
}

export const DataTable: ResourceBinding<DataTableConfig, DataTableAttrs> = {
  wireType: "google_chronicle_data_table",
  fields: {
    dataTableId: "data_table_id",
    deletionPolicy: "deletion_policy",
    description: "description",
    id: "id",
    instance: "instance",
    location: "location",
    project: "project",
    rowTimeToLive: "row_time_to_live",
    columnInfo: {
      wireName: "column_info",
      kind: "list",
      fields: DataTable_ColumnInfoFields,
    },
    scopeInfo: {
      wireName: "scope_info",
      kind: "list",
      fields: DataTable_ScopeInfoFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DataTable_TimeoutsFields,
    },
  },
};
