// Code generated by `ubx sdk gen` from google_chronicle_data_table_row. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface DataTableRow_Timeouts {
  create: string;
  delete: string;
  update: string;
}

const DataTableRow_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

export interface DataTableRowConfig {
  dataTableId: string | Computed<string>;
  deletionPolicy?: string | Computed<string>;
  id?: string | Computed<string>;
  instance: string | Computed<string>;
  location: string | Computed<string>;
  project?: string | Computed<string>;
  rowTimeToLive?: string | Computed<string>;
  values: string[] | Computed<string[]>;
  timeouts?: DataTableRow_Timeouts | Computed<DataTableRow_Timeouts>;
}

export interface DataTableRowAttrs {
  createTime: string;
  dataTableId: string;
  dataTableRow: string;
  deletionPolicy: string;
  id: string;
  instance: string;
  location: string;
  name: string;
  project: string;
  rowTimeToLive: string;
  updateTime: string;
  values: string[];
  timeouts: DataTableRow_Timeouts;
}

export const DataTableRow: ResourceBinding<DataTableRowConfig, DataTableRowAttrs> = {
  wireType: "google_chronicle_data_table_row",
  fields: {
    dataTableId: "data_table_id",
    deletionPolicy: "deletion_policy",
    id: "id",
    instance: "instance",
    location: "location",
    project: "project",
    rowTimeToLive: "row_time_to_live",
    values: "values",
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: DataTableRow_TimeoutsFields,
    },
  },
};
