// Code generated by `ubx sdk gen` from google_chronicle_watchlist. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Watchlist_EntityCount {
  asset: number;
  user: number;
}

export interface Watchlist_EntityPopulationMechanism_Manual {
}

export interface Watchlist_EntityPopulationMechanism {
  manual: Watchlist_EntityPopulationMechanism_Manual[];
}

export interface Watchlist_Timeouts {
  create: string;
  delete: string;
  update: string;
}

export interface Watchlist_WatchlistUserPreferences {
  pinned: boolean;
}

const Watchlist_EntityPopulationMechanism_ManualFields: FieldMap = {
};

const Watchlist_EntityPopulationMechanismFields: FieldMap = {
  manual: {
    wireName: "manual",
    kind: "list",
    fields: Watchlist_EntityPopulationMechanism_ManualFields,
  },
};

const Watchlist_TimeoutsFields: FieldMap = {
  create: "create",
  delete: "delete",
  update: "update",
};

const Watchlist_WatchlistUserPreferencesFields: FieldMap = {
  pinned: "pinned",
};

export interface WatchlistConfig {
  deletionPolicy?: string | Computed<string>;
  description?: string | Computed<string>;
  displayName: string | Computed<string>;
  id?: string | Computed<string>;
  instance: string | Computed<string>;
  location: string | Computed<string>;
  multiplyingFactor?: number | Computed<number>;
  project?: string | Computed<string>;
  watchlistId?: string | Computed<string>;
  entityPopulationMechanism?: Watchlist_EntityPopulationMechanism[] | Computed<Watchlist_EntityPopulationMechanism[]>;
  timeouts?: Watchlist_Timeouts | Computed<Watchlist_Timeouts>;
  watchlistUserPreferences?: Watchlist_WatchlistUserPreferences[] | Computed<Watchlist_WatchlistUserPreferences[]>;
}

export interface WatchlistAttrs {
  createTime: string;
  deletionPolicy: string;
  description: string;
  displayName: string;
  entityCount: Watchlist_EntityCount[];
  id: string;
  instance: string;
  location: string;
  multiplyingFactor: number;
  name: string;
  project: string;
  updateTime: string;
  watchlistId: string;
  entityPopulationMechanism: Watchlist_EntityPopulationMechanism[];
  timeouts: Watchlist_Timeouts;
  watchlistUserPreferences: Watchlist_WatchlistUserPreferences[];
}

export const Watchlist: ResourceBinding<WatchlistConfig, WatchlistAttrs> = {
  wireType: "google_chronicle_watchlist",
  fields: {
    deletionPolicy: "deletion_policy",
    description: "description",
    displayName: "display_name",
    id: "id",
    instance: "instance",
    location: "location",
    multiplyingFactor: "multiplying_factor",
    project: "project",
    watchlistId: "watchlist_id",
    entityPopulationMechanism: {
      wireName: "entity_population_mechanism",
      kind: "list",
      fields: Watchlist_EntityPopulationMechanismFields,
    },
    timeouts: {
      wireName: "timeouts",
      kind: "object",
      fields: Watchlist_TimeoutsFields,
    },
    watchlistUserPreferences: {
      wireName: "watchlist_user_preferences",
      kind: "list",
      fields: Watchlist_WatchlistUserPreferencesFields,
    },
  },
};
